### ISSUE TITLE
Disconnecting while game is minimized and not paused disables the mouse

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#103]
This bug happens on Steam version only, since this is the only one with HTML MOTD.

Steps:

1. Join a server with HTML MOTD
2. Get kicked with HTML MOTD open
3. Reconnect and close MOTD
4. Try moving camera, won't move

**Comment by tmp64** [comment]
This happens every time when:
1. Game is minimized but not in the pause screen
2. Player is disconnected from the server (kicked, lost connection, etc)
3. Game is maximized and the player joins any server
4. Client only uses VGUI2 (`IClientVGUI::UseVGUI1` returns false).

Seems to be some obscure engine bug.
