### ISSUE TITLE
`loadauthid` not affecting some non-steam p48 players (only 8684)

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#105]
- Playing on Steam (8684): doesn't load **some (if not all)** non-steam p48 player's IDs, their real names are not shown,
- Playing on Non-Steam (p48, 4554): does load the same non-steam p48 players, their real names are shown.

I tested this bug and it seemed to work that way, but just to make sure I asked other players to test it on me.
I joined the game both with Non-Steam (p48) and Steam, they (Steam) couldn't see my Non-Steam. Asked them to join with Non-Steam and this time around they were able to see it.

Maybe it's caused by some RevEmu?

> ] version
> Protocol version 48
> Exe version 1.1.2.2/Stdio (valve)
> Exe build: 19:53:27 Aug  3 2020 (8684)

> ] about
> BugfixedHL-Rebased
> Bugfixed and improved Half-Life Client
> Version: 1.7.0+master.c313ba4
> Engine: 1.1.2.2/Stdio,48,8684

**Comment by tmp64** [comment]
Do the players show identical SteamIDs in the scoreboard in both Steam and Non-Steam clients?

**Comment by gundogfan** [comment]
No, I'll explain what I mean using an example:

- I join a server using my Non-Steam HL and there's a Non-Steam player who has this SteamID `STEAM_0:0:193678636`. Using loadauthid works well, it shows his realname which I have storaged in realnames.txt.

- But once I join the same server with my Steam HL, using loadauthid doesn't work on him. His SteamID is the same, `STEAM_0:0:193678636`, but his realname is not shown. And I do have the same realnames.txt in both HL.

- This bug happened with several users, can't tell if all Non-Steams but most of them at least.

**Comment by tmp64** [comment]
I changed realnames to always use SteamID from `status` requests (the one shown on the scoreboard). I think it should solve the problem.

**Comment by gundogfan** [comment]
Fixed!
