### ISSUE TITLE
Adding a different behaviour to Rainbow HUD

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#110]
So far, `hud_rainbow 1` applies all colors at the same time to the HUD. My idea is adding `hud_rainbow 2` that applies **only one color** that keeps on changing. EX: red > orange > yellow > green > cyan > blue > purple > pink > red. Obviously with a certain gradient or transition between a color and the other.

**Comment by tmp64** [comment]
Like with `hud_rainbow_xphase 0` and `hud_rainbow_yphase`?

**Comment by gundogfan** [comment]
Oh I didn't even see that. I'll close. Thanks!
