### ISSUE TITLE
installation guide innacuracy 

### ISSUE THREAD

**Issue by LeviOP** [tmp64/BugfixedHL-Rebased#112]
In [the installation guide](/tmp64/BugfixedHL-Rebased/wiki/Installation) under section 4.1, it states:
> Open game installation directory (where hl.exe is).

then
> Extract valve_addon to that directory.

This is incorrect. In the steam version of Half-Life, the folder where hl.exe is isn't the valve folder. Dragging the contents of valve_addon into that directory does nothing.

**Comment by tmp64** [comment]
I see what you mean. *valve_addon* needs to be extracted next to *valve*, not its contents. 

```
Half-Life
├── valve
├── valve_addon
├── valve_downloads
├── valve_hd
├── valve_russian
├── hl.exe
```
If "Allow custom addon content" is enabled in video options, the game will load files from *valve_addon* first and other directories next. 

I added a clarification to the guide. Thanks!
