### ISSUE TITLE
Crashed (with report)

### ISSUE THREAD

**Issue by The-Gmann** [tmp64/BugfixedHL-Rebased#122]
DMP file - https://drive.google.com/file/d/13rSwpHtpLkPvsOqx4ZQythNo8rwqmY82/view?usp=sharing
-------------------------------------------------------------------------
Technical information

Version: 1.7.2+master.12ddc7c
Engine version: 1.1.2.2/Stdio,48,8684
Local time: 2022-02-07 14:00:30
OS version: 10.0.19041.1466

Stack trace (may be incorrect since no engine PDBs are available):
  2D6D6130 (parabot_mm): (filename not available): GiveFnptrsToDll

Modules:
  Base     Size     Path (Exception Offset)
  01400000 0001A000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\hl.exe
  77600000 001A3000 C:\Windows\SYSTEM32\ntdll.dll
  774F0000 000F0000 C:\Windows\System32\KERNEL32.DLL
  75FF0000 00214000 C:\Windows\System32\KERNELBASE.dll
  59760000 0009F000 C:\Windows\SYSTEM32\apphelp.dll
  764C0000 001A0000 C:\Windows\System32\USER32.dll
  76E80000 00018000 C:\Windows\System32\win32u.dll
  75610000 00024000 C:\Windows\System32\GDI32.dll
  6E100000 00008000 C:\Windows\SYSTEM32\WSOCK32.dll
  754E0000 000DE000 C:\Windows\System32\gdi32full.dll
  756A0000 000BF000 C:\Windows\System32\msvcrt.dll
  75BD0000 0007B000 C:\Windows\System32\msvcp_win.dll
  75E50000 00120000 C:\Windows\System32\ucrtbase.dll
  769D0000 00063000 C:\Windows\System32\WS2_32.dll
  757A0000 000BE000 C:\Windows\System32\RPCRT4.dll
  75DD0000 0007B000 C:\Windows\System32\ADVAPI32.dll
  758B0000 00076000 C:\Windows\System32\sechost.dll
  774C0000 00025000 C:\Windows\System32\IMM32.DLL
  79300000 00189000 D:\Program Files (x86)\Steam\gameoverlayrenderer.dll
  75CE0000 000E3000 C:\Windows\System32\ole32.dll
  75940000 00281000 C:\Windows\System32\combase.dll
  76660000 00096000 C:\Windows\System32\OLEAUT32.dll
  75C50000 00006000 C:\Windows\System32\PSAPI.DLL
  72210000 00028000 C:\Windows\SYSTEM32\WINMM.dll
  10000000 0001F000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\filesystem_stdio.dll
  03840000 01259000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\hw.dll
  739E0000 00008000 C:\Windows\SYSTEM32\VERSION.dll
  5C3E0000 00103000 C:\Windows\SYSTEM32\OPENGL32.dll
  77810000 000E9000 C:\Windows\SYSTEM32\DDRAW.dll
  58210000 00026000 C:\Windows\SYSTEM32\DINPUT.dll
  7AAB0000 000AD000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\SDL2.dll
  50010000 00082000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\mss32.dll
  77AA0000 0001D000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\steam_api.dll
  5C3A0000 0003F000 C:\Windows\SYSTEM32\GLU32.dll
  73660000 0000F000 C:\Windows\SYSTEM32\kernel.appcore.dll
  72260000 000C3000 C:\Windows\SYSTEM32\dxgi.dll
  59060000 00007000 C:\Windows\SYSTEM32\DCIMAN32.dll
  012E0000 00063000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\vgui.dll
  04AA0000 005B6000 C:\Windows\System32\SHELL32.dll
  68A80000 000ED000 C:\Windows\SYSTEM32\inputhost.dll
  76700000 00087000 C:\Windows\System32\shcore.dll
  6E570000 0009B000 C:\Windows\SYSTEM32\CoreMessaging.dll
  6E210000 000DB000 C:\Windows\SYSTEM32\wintypes.dll
  6ABD0000 000C2000 C:\Windows\SYSTEM32\PROPSYS.dll
  6E2F0000 0027E000 C:\Windows\SYSTEM32\CoreUIComponents.dll
  75C80000 0005F000 C:\Windows\System32\bcryptPrimitives.dll
  71CF0000 00029000 C:\Windows\SYSTEM32\ntmarta.dll
  5AC10000 011AD000 D:\Program Files (x86)\Steam\steamclient.dll
  755C0000 00045000 C:\Windows\System32\SHLWAPI.dll
  76790000 000FA000 C:\Windows\System32\CRYPT32.dll
  754C0000 00019000 C:\Windows\System32\imagehlp.dll
  76A40000 0043C000 C:\Windows\System32\SETUPAPI.dll
  739A0000 00032000 C:\Windows\SYSTEM32\IPHLPAPI.DLL
  75760000 0003B000 C:\Windows\System32\cfgmgr32.dll
  75C60000 00019000 C:\Windows\System32\bcrypt.dll
  65470000 0009A000 D:\Program Files (x86)\Steam\tier0_s.dll
  65210000 00063000 D:\Program Files (x86)\Steam\vstdlib_s.dll
  70100000 00052000 C:\Windows\SYSTEM32\MSWSOCK.dll
  72610000 0000A000 C:\Windows\SYSTEM32\Secur32.dll
  71D60000 00021000 C:\Windows\SYSTEM32\SSPICLI.DLL
  72020000 0000A000 C:\Windows\SYSTEM32\CRYPTBASE.DLL
  68CF0000 000A7000 D:\Program Files (x86)\Steam\crashhandler.dll
  6E6D0000 00456000 C:\Windows\SYSTEM32\WININET.dll
  6D5C0000 00074000 C:\Windows\system32\uxtheme.dll
  75F70000 0007E000 C:\Windows\System32\clbcatq.dll
  7ABE0000 0008B000 C:\Windows\System32\XAudio2_5.dll
  651D0000 00037000 C:\Windows\System32\dinput8.dll
  65710000 0000A000 C:\Windows\SYSTEM32\HID.DLL
  70060000 0002B000 C:\Windows\System32\DEVOBJ.dll
  75860000 00047000 C:\Windows\System32\WINTRUST.dll
  73650000 0000E000 C:\Windows\System32\MSASN1.dll
  65460000 0000D000 C:\Windows\SYSTEM32\XInput1_4.dll
  763E0000 000D4000 C:\Windows\System32\MSCTF.dll
  59900000 000BA000 C:\Windows\System32\AppXDeploymentClient.dll
  777E0000 00023000 C:\Windows\System32\DriverStore\FileRepository\u0373652.inf_amd64_97d024528a122d1a\B372726\atiglpxx.dll
  08760000 025C4000 C:\Windows\System32\DriverStore\FileRepository\u0373652.inf_amd64_97d024528a122d1a\B372726\atioglxx.dll
  6D790000 0001C000 C:\Windows\SYSTEM32\dxva2.dll
  6D670000 00026000 C:\Windows\SYSTEM32\dwmapi.dll
  7B320000 00034000 C:\Windows\System32\DriverStore\FileRepository\u0373652.inf_amd64_97d024528a122d1a\B372726\atigktxx.dll
  7A190000 0015A000 C:\Windows\SYSTEM32\atiadlxy.dll
  79F80000 0003F000 C:\Windows\SYSTEM32\pdh.dll
  727B0000 0060D000 C:\Windows\SYSTEM32\windows.storage.dll
  71D90000 00025000 C:\Windows\SYSTEM32\Wldp.dll
  6E160000 0002C000 C:\Windows\SYSTEM32\dxcore.dll
  6E610000 000B9000 C:\Windows\SYSTEM32\textinputframework.dll
  6DF60000 00053000 C:\Windows\system32\Oleacc.dll
  68970000 0006B000 C:\Windows\System32\MMDevApi.dll
  65830000 00136000 C:\Windows\SYSTEM32\AUDIOSES.DLL
  72DF0000 00044000 C:\Windows\SYSTEM32\powrprof.dll
  72DC0000 0000D000 C:\Windows\SYSTEM32\UMPDC.dll
  68BF0000 000F3000 C:\Windows\System32\Windows.UI.dll
  68B70000 00073000 C:\Windows\System32\WindowManagementAPI.dll
  6BFF0000 0018F000 C:\Windows\SYSTEM32\twinapi.appcore.dll
  7BA00000 004C4000 d:\program files (x86)\steam\steamapps\common\half-life\valve_addon\cl_dlls\client.dll
  72620000 00188000 C:\Windows\SYSTEM32\dbghelp.dll
  78D40000 0005C000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\tier0.dll
  7AE10000 00057000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\vstdlib.dll
  70770000 00026000 C:\Windows\SYSTEM32\dbgcore.DLL
  0FC50000 0003D000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\vgui2.dll
  7C270000 000DC000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\chromehtml.dll
  26BF0000 0138F000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\libcef.dll
  69150000 00017000 C:\Windows\SYSTEM32\USP10.dll
  75350000 000CB000 C:\Windows\SYSTEM32\WINHTTP.dll
  6F4B0000 0008D000 C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_c0da534e38c01f4d\COMCTL32.dll
  65A90000 00072000 C:\Windows\SYSTEM32\WINSPOOL.DRV
  75420000 00025000 C:\Windows\SYSTEM32\USERENV.dll
  72030000 001A8000 C:\Windows\SYSTEM32\urlmon.dll
  6E0F0000 00006000 C:\Windows\SYSTEM32\MSIMG32.dll
  72000000 0001D000 C:\Windows\SYSTEM32\srvcli.dll
  71DC0000 0022B000 C:\Windows\SYSTEM32\iertutil.dll
  71FF0000 0000B000 C:\Windows\SYSTEM32\netutils.dll
  10B20000 000AF000 C:\Windows\System32\COMDLG32.dll
  28270000 000E3000 d:\program files (x86)\steam\steamapps\common\half-life\valve\cl_dlls\GameUI.dll
  4AD00000 0097F000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\icudt.dll
  7A800000 001B2000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\avcodec-53.dll
  777B0000 00027000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\avutil-51.dll
  7C5B0000 00033000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\avformat-53.dll
  75930000 00007000 C:\Windows\System32\NSI.dll
  703B0000 00016000 C:\Windows\system32\NLAapi.dll
  5AB90000 0007F000 C:\Windows\SYSTEM32\dsound.dll
  655A0000 0001D000 C:\Windows\SYSTEM32\winmmbase.dll
  65430000 0000F000 C:\Windows\SYSTEM32\resourcepolicyclient.dll
  6DE90000 00008000 C:\Windows\SYSTEM32\avrt.dll
  7B380000 00016000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\mssmp3.asi
  79990000 0002A000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\mssvoice.asi
  65560000 0003A000 C:\Windows\SYSTEM32\wdmaud.drv
  65550000 00007000 C:\Windows\SYSTEM32\ksuser.dll
  65540000 0000A000 C:\Windows\SYSTEM32\msacm32.drv
  65520000 00019000 C:\Windows\SYSTEM32\MSACM32.dll
  65510000 00008000 C:\Windows\SYSTEM32\midimap.dll
  2B860000 00028000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\demoplayer.dll
  2B910000 0004C000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\core.dll
  7ACF0000 0008E000 d:\program files (x86)\steam\steamapps\common\half-life\platform\servers\serverbrowser.dll
  70540000 00091000 C:\Windows\SYSTEM32\DNSAPI.dll
  70050000 00008000 C:\Windows\System32\rasadhlp.dll
  6FFF0000 00058000 C:\Windows\System32\fwpuclnt.dll
  707D0000 00013000 C:\Windows\SYSTEM32\CRYPTSP.dll
  707A0000 0002F000 C:\Windows\system32\rsaenh.dll
  700D0000 00011000 C:\Windows\system32\napinsp.dll
  700B0000 00016000 C:\Windows\system32\pnrpnsp.dll
  700A0000 00010000 C:\Windows\system32\wshbth.dll
  70090000 0000E000 C:\Windows\System32\winrnr.dll
  791F0000 000C3000 d:\program files (x86)\steam\steamapps\common\half-life\valve\addons\metamod\dlls\metamod.dll
  2D3C0000 001DB000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\valve\dlls\hl.dll
  2D5B0000 000B9000 d:\program files (x86)\steam\steamapps\common\half-life\valve\addons\amxmodx\dlls\amxmodx_mm.dll
  79840000 00088000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\valve\addons\amxmodx\modules\bugfixedapi_amxx.dll
=>2D6D0000 000C3000 d:\program files (x86)\steam\steamapps\common\half-life\valve\addons\metamod\dlls\parabot_mm.dll  <==  00006130
  7A030000 0002F000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\valve\addons\amxmodx\modules\hamsandwich_amxx.dll
  7A060000 00048000 D:\Program Files (x86)\Steam\steamapps\common\Half-Life\valve\addons\amxmodx\modules\fakemeta_amxx.dll
  70480000 00014000 C:\Windows\SYSTEM32\dhcpcsvc6.DLL
  72DD0000 00016000 C:\Windows\SYSTEM32\dhcpcsvc.DLL
  655C0000 0005A000 C:\Windows\SYSTEM32\Wlanapi.dll
  71D20000 00018000 C:\Windows\SYSTEM32\profapi.dll
  6F300000 0000D000 C:\Windows\system32\wbem\wbemprox.dll
  6F280000 00072000 C:\Windows\SYSTEM32\wbemcomn.dll
  6D770000 00010000 C:\Windows\system32\wbem\wbemsvc.dll
  6D6A0000 000C9000 C:\Windows\system32\wbem\fastprox.dll
  6F490000 00012000 C:\Windows\SYSTEM32\amsi.dll
  6F420000 0006B000 C:\ProgramData\Microsoft\Windows Defender\platform\4.18.2105.4-0\X86\MpOav.dll

Validating heap
CRT heap: validated successfully
Process heap: validated successfully

**Comment by The-Gmann** [comment]
The crash happened when i tried to escape the crossfire nuke by going up with a gauss

**Comment by tmp64** [comment]
The crash is caused by Parabot, which is known to be unstable
