### ISSUE TITLE
Half-Life still open after quitting/getting a crash in steam.

### ISSUE THREAD

**Issue by The-Gmann** [tmp64/BugfixedHL-Rebased#126]
Steam still thinks the game is open after i quit the game, the hl.exe is not open. I fix it by restarting steam, but does this happen to anyone else?

**Comment by tmp64** [comment]
It always happens to me in Half-Life Alyx Workshop Tools but I never noticed it in Half-Life. It's probably a Steam bug. Can you disable BHL (untick 'Allow custom addon content' in video settings) and see if the issue persists?

**Comment by The-Gmann** [comment]
Doesn't seem to happen anymore, odd
