### ISSUE TITLE
Crosshair bug in thickness

### ISSUE THREAD

**Issue by DonCrazy123** [tmp64/BugfixedHL-Rebased#128]
When trying to customize my crosshair in thickness, the crosshair do not have equal sides and this makes trying to aim at someone too difficult, does it happen to someone else?

**Comment by tmp64** [comment]
Could you post all crosshair settings, screen resolution you use in the game and native resolution of the monitor?

**Comment by gustavomassa** [comment]
I have the same issue, any value less than 2.0 for thickness will cause this issue, I think it also depends on the cross_size and resolution

It happens for all resolutions 1920* til 1280, I did not test on lower resolutions

My monitor's native resolution is Full HD (Benq XL2420T) playing on 120/144 Hz

![image](https://user-images.githubusercontent.com/16235598/169476746-a734c3b3-afca-4e47-8e1b-64e54a38305b.png)
![image](https://user-images.githubusercontent.com/16235598/169476949-f2f82ca2-34e0-4e9a-a613-edad1f9c82d5.png)
![image](https://user-images.githubusercontent.com/16235598/169477096-703dd1d7-65fa-4f20-a4c1-218d8aeeb3f3.png)

```
cl_cross_enable		    "1"
cl_cross_size		"4"
cl_cross_gap 		"0"
cl_cross_t 				"0"
cl_cross_thickness 	"2.25"
cl_cross_outline_thickness 	"0"
cl_cross_red        "255"
cl_cross_green        "0"
cl_cross_blue        "0"
```
