### ISSUE TITLE
Client + command realnames 

### ISSUE THREAD

**Issue by CaptainStrom** [tmp64/BugfixedHL-Rebased#13]
This client is great. I would like you to add the command "realmanes" to the client, please. 
Thanks.

**Comment by Berzerk3r** [comment]
> Thanks for the suggestion. Realnames file stores player's SteamID, name and country code. All players in the list will have their name from realnames file instead of in-game name, right? But what do country codes do?

country code is a part of nickname

**Comment by tmp64** [comment]
I added support for realnames. They will be used instead of server names everywhere except the chat. The chat requires a bit more work, I'll add it later. Please, test the it works correctly.

**Comment by tmp64** [comment]
Added realnames to chat

**Comment by SmileyAG** [comment]
> 
> 
> I added support for realnames. They will be used instead of server names everywhere except the chat. The chat requires a bit more work, I'll add it later. Please, test the it works correctly.

That works correctly, thank you for that.

*btw sorry for wrong linking to 1st issue, i did it by accident.*
