### ISSUE TITLE
Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005)

### ISSUE THREAD

**Issue by luciferua** [tmp64/BugfixedHL-Rebased#134]
BugfixedHL Crash Log
  Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005) at address 0x049AB66E (hw.dll).

Please post contents of this log file and file crash-2022-03-26-12-03-42.dmp on
https://github.com/tmp64/BugfixedHL-Rebased/issues

-------------------------------------------------------------------------
Technical information

Version: 1.7.2+master.12ddc7c
Engine version: 1.1.2.1,48,4554
Local time: 2022-03-26 12:03:42
OS version: 10.0.19041.1566

Stack trace (may be incorrect since no engine PDBs are available):
  049AB66E (hw): (filename not available): glVertex3fv

Modules:
  Base     Size     Path (Exception Offset)
  01400000 02117000 C:\Games\Counter-Strike Half-Life\hl.exe
  77A10000 001A3000 C:\Windows\SYSTEM32\ntdll.dll
  76AB0000 000F0000 C:\Windows\System32\KERNEL32.DLL
  777E0000 00214000 C:\Windows\System32\KERNELBASE.dll
  701B0000 0009F000 C:\Windows\SYSTEM32\apphelp.dll
  76130000 0019C000 C:\Windows\System32\USER32.dll
  767D0000 00018000 C:\Windows\System32\win32u.dll
  76090000 00024000 C:\Windows\System32\GDI32.dll
  75A30000 000DC000 C:\Windows\System32\gdi32full.dll
  76DE0000 0007B000 C:\Windows\System32\msvcp_win.dll
  76CC0000 00120000 C:\Windows\System32\ucrtbase.dll
  76750000 0007B000 C:\Windows\System32\ADVAPI32.dll
  77630000 000BF000 C:\Windows\System32\msvcrt.dll
  77420000 00076000 C:\Windows\System32\sechost.dll
  767F0000 000BE000 C:\Windows\System32\RPCRT4.dll
  748E0000 00008000 C:\Windows\SYSTEM32\WSOCK32.dll
  760C0000 00063000 C:\Windows\System32\WS2_32.dll
  774A0000 00025000 C:\Windows\System32\IMM32.DLL
  10000000 0001F000 C:\Games\Counter-Strike Half-Life\filesystem_stdio.dll
=>04930000 01229A8E C:\Games\Counter-Strike Half-Life\hw.dll  <==  0007B66E
  774E0000 000E3000 C:\Windows\System32\ole32.dll
  76360000 00280000 C:\Windows\System32\combase.dll
  75990000 00096000 C:\Windows\System32\OLEAUT32.dll
  748B0000 00026000 C:\Windows\SYSTEM32\DINPUT.dll
  747C0000 000E9000 C:\Windows\SYSTEM32\DDRAW.dll
  735E0000 00028000 C:\Windows\SYSTEM32\WINMM.dll
  758D0000 00008000 C:\Windows\SYSTEM32\VERSION.dll
  21100000 0005E000 C:\Games\Counter-Strike Half-Life\mss32.dll
  74210000 00454000 C:\Windows\SYSTEM32\WININET.dll
  74E90000 0000F000 C:\Windows\SYSTEM32\kernel.appcore.dll
  71EA0000 000C2000 C:\Windows\SYSTEM32\dxgi.dll
  747B0000 00007000 C:\Windows\SYSTEM32\DCIMAN32.dll
  010C0000 00058000 C:\Games\Counter-Strike Half-Life\vgui.dll
  00D20000 00015000 C:\Games\Counter-Strike Half-Life\steam_api_c.dll
  74750000 00055000 C:\Games\Counter-Strike Half-Life\Steam.dll
  76E60000 005B5000 C:\Windows\System32\SHELL32.dll
  74040000 00188000 C:\Windows\SYSTEM32\DbgHelp.dll
  74010000 00026000 C:\Windows\SYSTEM32\dbgcore.DLL
  762D0000 00087000 C:\Windows\System32\shcore.dll
  74720000 0002C000 C:\Games\Counter-Strike Half-Life\hwpatcher.dll
  72560000 00167000 C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.1566_none_d951c72fe1040d0f\gdiplus.dll
  05C70000 000F8000 C:\Games\Counter-Strike Half-Life\Steam86.dll
  71FE0000 00011000 C:\Windows\system32\napinsp.dll
  71FC0000 00016000 C:\Windows\system32\pnrpnsp.dll
  71FB0000 00010000 C:\Windows\system32\wshbth.dll
  71F90000 00016000 C:\Windows\system32\NLAapi.dll
  75550000 00032000 C:\Windows\SYSTEM32\IPHLPAPI.DLL
  73230000 00052000 C:\Windows\System32\mswsock.dll
  74BA0000 00090000 C:\Windows\SYSTEM32\DNSAPI.dll
  774D0000 00007000 C:\Windows\System32\NSI.dll
  71F80000 0000E000 C:\Windows\System32\winrnr.dll
  71E40000 00058000 C:\Windows\System32\fwpuclnt.dll
  76A70000 00019000 C:\Windows\System32\bcrypt.dll
  71F70000 00008000 C:\Windows\System32\rasadhlp.dll
  717F0000 000ED000 C:\Windows\SYSTEM32\inputhost.dll
  71A60000 0009B000 C:\Windows\SYSTEM32\CoreMessaging.dll
  732F0000 000C2000 C:\Windows\SYSTEM32\PROPSYS.dll
  72D70000 000DB000 C:\Windows\SYSTEM32\wintypes.dll
  76C60000 0005F000 C:\Windows\System32\bcryptPrimitives.dll
  71B00000 0027E000 C:\Windows\SYSTEM32\CoreUIComponents.dll
  758A0000 00029000 C:\Windows\SYSTEM32\ntmarta.dll
  74670000 00074000 C:\Windows\system32\uxtheme.dll
  73FA0000 00066000 c:\games\counter-strike half-life\steamclient.dll
  73F70000 0002F000 C:\Games\Counter-Strike Half-Life\revSrvBrowser.dll
  77700000 000D4000 C:\Windows\System32\MSCTF.dll
  765E0000 000FA000 C:\Windows\System32\crypt32.dll
  75BA0000 0004D000 C:\Windows\System32\WINTRUST.DLL
  75890000 0000E000 C:\Windows\SYSTEM32\MSASN1.dll
  76A90000 00019000 C:\Windows\System32\imagehlp.dll
  75870000 00013000 C:\Windows\SYSTEM32\CRYPTSP.dll
  75840000 0002F000 C:\Windows\system32\rsaenh.dll
  75830000 0000A000 C:\Windows\SYSTEM32\CRYPTBASE.dll
  74ED0000 0060C000 C:\Windows\SYSTEM32\windows.storage.dll
  74EA0000 00024000 C:\Windows\SYSTEM32\Wldp.dll
  76A20000 00045000 C:\Windows\System32\shlwapi.dll
  6DBF0000 0002C000 C:\Windows\SYSTEM32\dxcore.dll
  76C20000 0003B000 C:\Windows\System32\cfgmgr32.dll
  71D80000 000B9000 C:\Windows\SYSTEM32\textinputframework.dll
  70350000 000C5000 C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_c1a085cc86772d3f\nvldumd.dll
  6B560000 00ED8000 C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_c1a085cc86772d3f\nvd3dum.dll
  732A0000 00044000 C:\Windows\system32\powrprof.dll
  73290000 0000D000 C:\Windows\SYSTEM32\UMPDC.dll
  76BA0000 0007E000 C:\Windows\System32\clbcatq.dll
  73F10000 00055000 C:\Windows\SYSTEM32\D3DIM.DLL
  67E40000 004C4000 c:\games\counter-strike half-life\valve\cl_dlls\client.dll
  766E0000 00006000 C:\Windows\System32\PSAPI.DLL
  73ED0000 00037000 C:\Windows\SYSTEM32\DINPUT8.dll
  063C0000 00015000 C:\Games\Counter-Strike Half-Life\steam_api.dll
  06440000 00059000 C:\Games\Counter-Strike Half-Life\tier0.dll
  064A0000 0005A000 C:\Games\Counter-Strike Half-Life\vstdlib.dll
  0E490000 00040000 C:\Games\Counter-Strike Half-Life\vgui2.dll
  0E9C0000 000E4000 c:\games\counter-strike half-life\valve\cl_dlls\GameUI.dll
  73E50000 0007F000 C:\Windows\SYSTEM32\dsound.dll
  73E30000 0001D000 C:\Windows\SYSTEM32\winmmbase.dll
  726E0000 0006B000 C:\Windows\System32\MMDevApi.dll
  754E0000 00029000 C:\Windows\System32\DEVOBJ.dll
  69030000 00136000 C:\Windows\SYSTEM32\AUDIOSES.DLL
  68CD0000 0000F000 C:\Windows\SYSTEM32\resourcepolicyclient.dll
  71960000 000F3000 C:\Windows\System32\Windows.UI.dll
  718E0000 00073000 C:\Windows\System32\WindowManagementAPI.dll
  72E50000 0018F000 C:\Windows\SYSTEM32\twinapi.appcore.dll
  72790000 00008000 C:\Windows\SYSTEM32\avrt.dll
  73DF0000 0003A000 C:\Windows\SYSTEM32\wdmaud.drv
  695C0000 00007000 C:\Windows\SYSTEM32\ksuser.dll
  74710000 0000A000 C:\Windows\SYSTEM32\msacm32.drv
  73DD0000 00019000 C:\Windows\SYSTEM32\MSACM32.dll
  73DC0000 00008000 C:\Windows\SYSTEM32\midimap.dll
  0FF60000 0001E000 C:\Games\Counter-Strike Half-Life\demoplayer.dll
  0FFB0000 00048000 C:\Games\Counter-Strike Half-Life\core.dll
  73DB0000 0000A000 C:\Windows\SYSTEM32\HID.DLL
  75C50000 0043A000 C:\Windows\System32\SETUPAPI.DLL
  22050000 0008D000 c:\games\counter-strike half-life\platform\Servers\serverbrowser.dll
  727A0000 00026000 C:\Windows\SYSTEM32\dwmapi.dll
  67800000 00639000 C:\Windows\System32\ieframe.dll
  675D0000 0022C000 C:\Windows\System32\iertutil.dll
  74D30000 00015000 C:\Windows\System32\NETAPI32.dll
  74CE0000 00025000 C:\Windows\System32\USERENV.dll
  75590000 000C9000 C:\Windows\System32\WINHTTP.dll
  741F0000 00011000 C:\Windows\System32\WKSCLI.DLL
  741E0000 0000B000 C:\Windows\System32\NETUTILS.DLL
  74960000 00210000 C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_a8625c1886757984\comctl32.dll
  70310000 00031000 C:\Windows\system32\dataexchange.dll
  70420000 001E0000 C:\Windows\system32\d3d11.dll
  6F650000 00164000 C:\Windows\system32\dcomp.dll
  67420000 001A8000 C:\Windows\SYSTEM32\urlmon.dll
  71200000 0001D000 C:\Windows\SYSTEM32\srvcli.dll
  73D20000 00088000 C:\Windows\SYSTEM32\sxs.dll
  70250000 00021000 C:\Windows\SYSTEM32\SspiCli.dll
  757F0000 00018000 C:\Windows\SYSTEM32\profapi.dll
  73D00000 00012000 C:\Windows\SYSTEM32\ondemandconnroutehelper.dll
  69B50000 00008000 C:\Windows\SYSTEM32\WINNSI.DLL
  26F00000 0002A000 C:\Games\Counter-Strike Half-Life\Mp3dec.asi
  26600000 00027000 C:\Games\Counter-Strike Half-Life\Mssv12.asi
  26400000 0002C000 C:\Games\Counter-Strike Half-Life\Mssv29.asi
  0F9F0000 00023000 C:\Games\Counter-Strike Half-Life\voice_speex.dll

Validating heap
CRT heap: validated successfully
Process heap: validated successfully

**Comment by tmp64** [comment]
Closed: no crash dump provided (which I missed initially), no report that it has happened again.
