### ISSUE TITLE
Lots of "Unknown command"

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#139]
For some reason, whenever I use HL Steam (8684) (this **does not happen** in 4554) server can't read certain things while I'm playing. For example, selecting a new weapon, sending a message, zooming in/out with crossbow or enabling/disabling RPG laser may end up in "Unknown command: tW0" (or any other random letters and numbers) and my action is not executed. 
Someone stated it could be ReChecker but I disabled it and this same bug happens anyways, so it is not.

This has been tested on a server running on Linux with `BugfixedHL-1.7.2-dev-server-linux-03ebbec` and `ReHLDS 3.11.0.776-dev`. Client is Bugfixed 1.7.2.

Can't provide much info about this one because I have no idea what causes it, but I can help testing in different scenarios if needed.

**Comment by tmp64** [comment]
Update the server to BHL v1.8.0. There was a critical bug fixed that may or may not be related.

Try disabling Metamod plugins one by one. You can also try testing without BHL (with original hl.so)

**Comment by gundogfan** [comment]
Turns out it's HLGuard, and it happens with both BHL versions and with original hl.so
