### ISSUE TITLE
Suggestion: adding client CVARs to Advanced Options panel

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#14]
It'd be really helpful for mostly new players if these CVARs were added to Advanced Options panel.

As booleans:
"engine_fix_fpsbug"
"cl_hidecorpses"
"hud_scores"
"hud_takesshots"
"results_log_chat"
"results_log_other"

As strings:
"cl_forceenemymodels"
"cl_forceenemycolors"
"cl_forceteammatesmodel"
"cl_forceteammatescolors"
"con_color"
"con_say_color"

As list:
"hud_colortext"

I added them to Options->Advanced->Multiplayer but I think they look better in Advanced Options panel.

![none-02102020-103523](https://user-images.githubusercontent.com/70611792/94929761-e8604f80-049b-11eb-9d64-62f6b95c7429.jpg)

![none-02102020-103512](https://user-images.githubusercontent.com/70611792/94929758-e72f2280-049b-11eb-8b87-26837c733d2b.jpg)

Also, for forceenemycolors and forceenemymodel it'd be nice if they have the same feature as in the default options-multiplayer where you can actually see how your model look like.

**Comment by tmp64** [comment]
I added most of the available cvars to the options dialog in the latest commits.
