### ISSUE TITLE
Steam profile pictures on Spectator UI bug

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#141]
Sometimes players who didn't set their profile picture or non steam players (they should be shown as "?") are shown on Spectator UI with someone else's profile picture.

I think it's not related to who was connected previously to that specific server, maybe those profile pictures belong to someone you where on the same server with but not necessarily the same one.

**Comment by tmp64** [comment]
Might be an avatar caching issue on the client

**Comment by tmp64** [comment]
Nope, it just wasn't being reset if no SteamID is available
