### ISSUE TITLE
Proposals for the next update.

### ISSUE THREAD

**Issue by fatchiiii** [tmp64/BugfixedHL-Rebased#145]
I would like if possible - to be able to change the sound or sounds of different weapons for example: 9mm.
                                      - have a blue and red model list included in the menu.
                                      - develop a transparent crossfire board if possible.
                                     thank you very much for your work

**Comment by tmp64** [comment]
You can put your own sounds, models, sprites, etc into `valve_addon` to replace the original ones. Models and maps are outside the scope of this project.
