### ISSUE TITLE
Crash after clicking test microphone

### ISSUE THREAD

**Issue by BillyJoeTodd** [tmp64/BugfixedHL-Rebased#146]
Looks like it was just a one-off thing but thought I might as well make an account just to post this.
[crash-2022-10-09-01-14-30.zip](https://github.com/tmp64/BugfixedHL-Rebased/files/9741009/crash-2022-10-09-01-14-30.zip)

**Comment by gundogfan** [comment]
I posted this in #89 and it was fixed. Do you have your client up-to-date?

**Comment by BillyJoeTodd** [comment]
Yeah, my client is up to date, 1.8.0

**Comment by tmp64** [comment]
Repro:
1. Start the game.
2. Create local server.
3. Disconnect from the server.
4. Press "Test microphone"
5. Crash.

This happens because `gEngfuncs.GetLocalPlayer()` returns a garbage pointer for some reason.
