### ISSUE TITLE
Fatal Error & Automatic Update

### ISSUE THREAD

**Issue by HLAG-Golden** [tmp64/BugfixedHL-Rebased#148]
This started to happen when I installed the server and client zips. So when I try to open the game, it appears Fatal Error and it says: 

"Could not load library d:\program files (x86)\steam\steamapps\common\half-life\valve_addon\cl_dlls\client.dll"

![fatalerror](https://user-images.githubusercontent.com/117566992/200183235-03c99e66-222c-412e-bc82-5ac9e9a10707.png)

Before I installed the server and client zip files (and it appeared the fatal error), I tried to use the automatic update... So I downloaded the update inside the game, but it crashed the game everytime and  I have to install it again.

**Comment by tmp64** [comment]
Fixed. It was caused by the client linking to zlib via vcpkg instead of using the static version in the repo and was obscured by the fact that zlib1.dll is installed system-wide for whatever reason on my machine.

**Comment by HLAG-Golden** [comment]
> Fixed. It was caused by the client linking to zlib via vcpkg instead of using the static version in the repo and was obscured by the fact that zlib1.dll is installed system-wide for whatever reason on my machine.

Thank you! BugfixedHL-Rebased rocks! :D
