### ISSUE TITLE
 Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005) at address 0x7055E8B6 (parabot.dll).

### ISSUE THREAD

**Issue by Verculaz** [tmp64/BugfixedHL-Rebased#152]
Hello, it's kind of crash error ...
BugfixedHL Crash Log
  Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005) at address 0x7055E8B6 (parabot.dll).

Please post contents of this log file and file crash-2022-11-28-00-47-20.dmp on
https://github.com/tmp64/BugfixedHL-Rebased/issues

-------------------------------------------------------------------------
Technical information

Version: 1.9.1+master.c47a5ab
Engine version: 1.1.2.1,48,4554
Local time: 2022-11-28 00:47:20
OS version: 10.0.19041.1706

Stack trace (may be incorrect since no engine PDBs are available):
  7055E8B6 (parabot): (filename not available): Meta_Query
  7055EB8E (parabot): (filename not available): Meta_Query
  7054DAA5 (parabot): (filename not available): Meta_Query
  6C5015B2 (metamod): (filename not available): (function-name not available)
  61ACF244 (client): (filename not available): ApplyMultiDamage
  049A3F76 (hw): (filename not available): CreateInterface
  6C5045F2 (metamod): (filename not available): (function-name not available)
  04992D33 (hw): (filename not available): (function-name not available)
  049F64A2 (hw): (filename not available): F
  049F5926 (hw): (filename not available): F
  049F5A50 (hw): (filename not available): F
  01401BB5 (hl): (filename not available): CreateInterface
  01404C5E (hl): (filename not available): CreateInterface
  76F9FA29 (KERNEL32): (filename not available): BaseThreadInitThunk
  77467A7E (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath
  77467A4E (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath

**Comment by tmp64** [comment]
The crash is most likely caused by Parabot. It is known to crash often.
