### ISSUE TITLE
Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005) at address 0x76FF733D (ntdll.dll).

### ISSUE THREAD

**Issue by BillyJoeTodd** [tmp64/BugfixedHL-Rebased#159]
Content of log file:

			BugfixedHL Crash Log
  Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005) at address 0x76FF733D (ntdll.dll).

Please post contents of this log file and file crash-2023-01-24-01-13-09.dmp on
https://github.com/tmp64/BugfixedHL-Rebased/issues

-------------------------------------------------------------------------
Technical information

Version: 1.9.1+master.c47a5ab
Engine version: 1.1.2.2/Stdio,48,8684
Local time: 2023-01-24 01:13:09
OS version: 10.0.22621.1105

Stack trace (may be incorrect since no engine PDBs are available):
  76FF733D (ntdll): (filename not available): LdrpResGetMappingSize
  76FFA7AE (ntdll): (filename not available): RtlInitializeCriticalSectionEx
  76FF7B82 (ntdll): (filename not available): LdrpResGetMappingSize
  76FEFF67 (ntdll): (filename not available): RtlGetCurrentServiceSessionId
  7703040D (ntdll): (filename not available): RtlRemovePropertyStore
  76FEF2C6 (ntdll): (filename not available): RtlFreeHeap
  03947447 (hw): (filename not available): vgui::Frame::operator=
  038A355C (hw): (filename not available): CreateInterface
  03852E34 (hw): (filename not available): (function-name not available)
  0385E586 (hw): (filename not available): (function-name not available)
  03857375 (hw): (filename not available): (function-name not available)
  038976E8 (hw): (filename not available): (function-name not available)
  03897833 (hw): (filename not available): (function-name not available)
  038ED38E (hw): (filename not available): F
  038EC79D (hw): (filename not available): F
  038EC91A (hw): (filename not available): F
  01401A7A (hl): (filename not available): CreateInterface
  014053D1 (hl): (filename not available): CreateInterface
  753F7D69 (KERNEL32): (filename not available): BaseThreadInitThunk
  7700BB9B (ntdll): (filename not available): RtlInitializeExceptionChain
  7700BB1F (ntdll): (filename not available): RtlClearBits

Modules:
  Base     Size     Path (Exception Offset)
  01400000 0001A000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\hl.exe
=>76FA0000 001AF000 C:\WINDOWS\SYSTEM32\ntdll.dll  <==  0005733D
  753E0000 000F0000 C:\WINDOWS\System32\KERNEL32.DLL
  74CC0000 0026B000 C:\WINDOWS\System32\KERNELBASE.dll
  71940000 000A5000 C:\WINDOWS\SYSTEM32\apphelp.dll
  76600000 001A6000 C:\WINDOWS\System32\USER32.dll
  76850000 0001A000 C:\WINDOWS\System32\win32u.dll
  755A0000 00022000 C:\WINDOWS\System32\GDI32.dll
  76000000 000DD000 C:\WINDOWS\System32\gdi32full.dll
  71B40000 00008000 C:\WINDOWS\SYSTEM32\WSOCK32.dll
  76920000 00079000 C:\WINDOWS\System32\msvcp_win.dll
  755D0000 00112000 C:\WINDOWS\System32\ucrtbase.dll
  74F30000 000C4000 C:\WINDOWS\System32\msvcrt.dll
  750C0000 0005F000 C:\WINDOWS\System32\WS2_32.dll
  75520000 0007C000 C:\WINDOWS\System32\ADVAPI32.dll
  756F0000 000B9000 C:\WINDOWS\System32\RPCRT4.dll
  75F00000 00082000 C:\WINDOWS\System32\sechost.dll
  754E0000 00026000 C:\WINDOWS\System32\IMM32.DLL
  6A660000 00149000 C:\Program Files (x86)\Steam\gameoverlayrenderer.dll
  76CD0000 0014D000 C:\WINDOWS\System32\ole32.dll
  76A50000 0027C000 C:\WINDOWS\System32\combase.dll
  76880000 0009C000 C:\WINDOWS\System32\OLEAUT32.dll
  754D0000 00006000 C:\WINDOWS\System32\PSAPI.DLL
  70B90000 00031000 C:\WINDOWS\SYSTEM32\WINMM.dll
  10000000 0001F000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\filesystem_stdio.dll
  03840000 01259000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\hw.dll
  5E480000 000E0000 C:\WINDOWS\SYSTEM32\OPENGL32.dll
  6A570000 000EB000 C:\WINDOWS\SYSTEM32\DDRAW.dll
  74BA0000 00008000 C:\WINDOWS\SYSTEM32\VERSION.dll
  6A540000 00027000 C:\WINDOWS\SYSTEM32\DINPUT.dll
  6E910000 00042000 C:\WINDOWS\SYSTEM32\GLU32.dll
  6A520000 0001D000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\steam_api.dll
  757B0000 00661000 C:\WINDOWS\System32\SHELL32.dll
  6CFE0000 000CA000 C:\WINDOWS\SYSTEM32\dxgi.dll
  6F4E0000 00007000 C:\WINDOWS\SYSTEM32\DCIMAN32.dll
  6CD50000 0002D000 C:\WINDOWS\SYSTEM32\dxcore.dll
  6A470000 000AD000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\SDL2.dll
  6A3E0000 00082000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mss32.dll
  01370000 00063000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\vgui.dll
  6C290000 00146000 C:\WINDOWS\SYSTEM32\inputhost.dll
  6C1C0000 000CD000 C:\WINDOWS\SYSTEM32\CoreMessaging.dll
  5CB40000 0124A000 C:\Program Files (x86)\Steam\steamclient.dll
  76100000 0004B000 C:\WINDOWS\System32\SHLWAPI.dll
  76E80000 00103000 C:\WINDOWS\System32\CRYPT32.dll
  760E0000 0001B000 C:\WINDOWS\System32\imagehlp.dll
  761B0000 00441000 C:\WINDOWS\System32\SETUPAPI.dll
  6F410000 00024000 C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
  6F170000 00099000 C:\Program Files (x86)\Steam\tier0_s.dll
  6F0E0000 00088000 C:\Program Files (x86)\Steam\vstdlib_s.dll
  71A30000 0001A000 C:\WINDOWS\SYSTEM32\bcrypt.dll
  6E3B0000 00051000 C:\WINDOWS\SYSTEM32\MSWSOCK.dll
  6F6E0000 0000A000 C:\WINDOWS\SYSTEM32\Secur32.dll
  70C70000 00025000 C:\WINDOWS\SYSTEM32\SSPICLI.DLL
  75000000 000C0000 C:\WINDOWS\System32\shcore.dll
  71A70000 0000B000 C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
  75F90000 00062000 C:\WINDOWS\System32\bcryptPrimitives.dll
  6F300000 000A7000 C:\Program Files (x86)\Steam\crashhandler.dll
  6E960000 00488000 C:\WINDOWS\SYSTEM32\WININET.dll
  74BB0000 00013000 C:\WINDOWS\SYSTEM32\kernel.appcore.dll
  6EDF0000 0007F000 C:\WINDOWS\system32\uxtheme.dll
  75120000 00087000 C:\WINDOWS\System32\clbcatq.dll
  6A350000 0008B000 C:\WINDOWS\System32\XAudio2_5.dll
  6CA40000 00038000 C:\Windows\System32\dinput8.dll
  6F6F0000 0000B000 C:\WINDOWS\SYSTEM32\HID.DLL
  719F0000 0003D000 C:\WINDOWS\System32\cfgmgr32.DLL
  6F700000 0002A000 C:\WINDOWS\SYSTEM32\DEVOBJ.dll
  751B0000 00058000 C:\WINDOWS\System32\WINTRUST.dll
  70810000 0000E000 C:\WINDOWS\SYSTEM32\MSASN1.dll
  71B30000 0000D000 C:\WINDOWS\SYSTEM32\XInput1_4.dll
  08230000 000DB000 C:\WINDOWS\System32\MSCTF.dll
  6A270000 000DF000 C:\Windows\System32\AppXDeploymentClient.dll
  64E10000 02786000 C:\WINDOWS\System32\DriverStore\FileRepository\nvddi.inf_amd64_b89984cea0fe0a20\nvoglv32.dll
  71B10000 0000F000 C:\WINDOWS\SYSTEM32\WTSAPI32.dll
  6E300000 00027000 C:\WINDOWS\SYSTEM32\cryptnet.dll
  6E1F0000 00109000 C:\WINDOWS\SYSTEM32\drvstore.dll
  70C00000 00043000 C:\WINDOWS\SYSTEM32\wldp.dll
  70A10000 00029000 C:\WINDOWS\SYSTEM32\ntmarta.dll
  73C30000 006CD000 C:\WINDOWS\SYSTEM32\windows.storage.dll
  73B60000 000C7000 C:\WINDOWS\SYSTEM32\wintypes.dll
  6A040000 00228000 C:\WINDOWS\system32\nvspcap.dll
  71A50000 00019000 C:\WINDOWS\SYSTEM32\profapi.dll
  677C0000 00024000 C:\WINDOWS\SYSTEM32\dwmapi.dll
  6E410000 00046000 C:\WINDOWS\SYSTEM32\powrprof.dll
  70B80000 0000E000 C:\WINDOWS\SYSTEM32\UMPDC.dll
  6B030000 0004F000 C:\WINDOWS\SYSTEM32\WINSTA.dll
  6B700000 000E3000 C:\WINDOWS\SYSTEM32\textinputframework.dll
  68EA0000 00290000 C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
  6B4D0000 0007C000 C:\WINDOWS\System32\MMDevApi.dll
  678C0000 0018A000 C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
  6B5F0000 0010A000 C:\Windows\System32\Windows.UI.dll
  696B0000 0048E000 c:\program files (x86)\steam\steamapps\common\half-life\valve\cl_dlls\client.dll
  6E460000 001D2000 C:\WINDOWS\SYSTEM32\dbghelp.dll
  69650000 00057000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\vstdlib.dll
  69550000 0005C000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\tier0.dll
  69520000 00029000 C:\WINDOWS\SYSTEM32\dbgcore.DLL
  0EE10000 0003D000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\vgui2.dll
  69440000 000DC000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\chromehtml.dll
  622D0000 0138F000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\libcef.dll
  769A0000 000B0000 C:\WINDOWS\System32\COMDLG32.dll
  6F570000 000D6000 C:\WINDOWS\SYSTEM32\WINHTTP.dll
  69420000 00017000 C:\WINDOWS\SYSTEM32\USP10.dll
  695B0000 00091000 C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_42d541138da2ebd2\COMCTL32.dll
  693A0000 00075000 C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
  70B60000 0001F000 C:\WINDOWS\SYSTEM32\USERENV.dll
  71750000 001A2000 C:\WINDOWS\SYSTEM32\urlmon.dll
  71B00000 00006000 C:\WINDOWS\SYSTEM32\MSIMG32.dll
  714F0000 0022E000 C:\WINDOWS\SYSTEM32\iertutil.dll
  71730000 0001D000 C:\WINDOWS\SYSTEM32\srvcli.dll
  71720000 0000B000 C:\WINDOWS\SYSTEM32\netutils.dll
  0F450000 000E3000 c:\program files (x86)\steam\steamapps\common\half-life\valve\cl_dlls\GameUI.dll
  4AD00000 0097F000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\icudt.dll
  691E0000 001B2000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\avcodec-53.dll
  691B0000 00027000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\avutil-51.dll
  69170000 00033000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\avformat-53.dll
  75510000 00007000 C:\WINDOWS\System32\NSI.dll
  67CA0000 011F2000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\steamclient.dll
  6F4C0000 00018000 C:\WINDOWS\system32\nlansp_c.dll
  5CAC0000 00072000 C:\WINDOWS\SYSTEM32\dsound.dll
  67890000 0001F000 C:\WINDOWS\SYSTEM32\winmmbase.dll
  5CA20000 00099000 C:\WINDOWS\SYSTEM32\ResampleDmo.DLL
  67B80000 00009000 C:\WINDOWS\SYSTEM32\msdmo.dll
  69160000 00010000 C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
  6F3C0000 00009000 C:\WINDOWS\SYSTEM32\avrt.dll
  69140000 00016000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mssmp3.asi
  67C70000 0002A000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mssvoice.asi
  67850000 0003B000 C:\WINDOWS\SYSTEM32\wdmaud.drv
  67840000 00007000 C:\WINDOWS\SYSTEM32\ksuser.dll
  67C50000 00016000 C:\WINDOWS\SYSTEM32\mcicda.dll
  67830000 0000B000 C:\WINDOWS\SYSTEM32\msacm32.drv
  67810000 00019000 C:\WINDOWS\SYSTEM32\MSACM32.dll
  67800000 00008000 C:\WINDOWS\SYSTEM32\midimap.dll
  27920000 00028000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\demoplayer.dll
  27990000 0004C000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\core.dll
  67BC0000 0008E000 c:\program files (x86)\steam\steamapps\common\half-life\platform\servers\serverbrowser.dll
  6C100000 000B9000 C:\WINDOWS\SYSTEM32\DNSAPI.dll
  6C480000 00008000 C:\Windows\System32\rasadhlp.dll
  6C420000 0005D000 C:\WINDOWS\System32\fwpuclnt.dll
  71AB0000 00015000 C:\WINDOWS\SYSTEM32\CRYPTSP.dll
  71A80000 00030000 C:\WINDOWS\system32\rsaenh.dll
  71920000 00012000 C:\WINDOWS\system32\napinsp.dll
  6E8F0000 00016000 C:\WINDOWS\system32\pnrpnsp.dll
  6F250000 0000E000 C:\WINDOWS\System32\winrnr.dll
  6E8D0000 00011000 C:\WINDOWS\system32\wshbth.dll

Validating heap
CRT heap: validated successfully
Process heap: validated successfully

.dmp file:

https://drive.google.com/file/d/1A9ZYMXkrM78Zq8XuPZUhBbMxcgAd1KFU/view?usp=sharing

**Comment by tmp64** [comment]
An engine crash. Can't debug this one.
