### ISSUE TITLE
BHL not able to read .loc files bigger than [8192] bytes

### ISSUE THREAD

**Issue by andreiseverin** [tmp64/BugfixedHL-Rebased#162]
Hello,

I am currently working on a plugin to automatically create locs file for the maps where we do not have one.
The system is simple : 3x3 grid named after the compass directions. For each BIG GRID ZONE, I redo a 3x3 adding a zone number. Finally, I am comparing the map height and I am adding the level of the loc.
![image](https://user-images.githubusercontent.com/39212135/217385003-d78cdb85-1797-4921-a874-0df5f5b84cba.png)

The final buffer I used is defined as `new buffer[16384];` but I see the BHL isn't capable of displaying more that `8192`.
Taking into account that the loc file is on the client side, I suppose the size can be increased.

Test file to add for the map bootbox - > `bootbox.loc`
```South-West - Zone 1 - Bottom#171.8#171.4#328.6#South-West - Zone 1 - Middle#171.8#171.4#878.0#South-West - Zone 1 - Top#171.8#171.4#1427.3#South-West - Zone 2 - Bottom#171.8#447.9#328.6#South-West - Zone 2 - Middle#171.8#447.9#878.0#South-West - Zone 2 - Top#171.8#447.9#1427.3#South-West - Zone 3 - Bottom#171.8#724.3#328.6#South-West - Zone 3 - Middle#171.8#724.3#878.0#South-West - Zone 3 - Top#171.8#724.3#1427.3#South-West - Zone 4 - Bottom#448.9#171.4#328.6#South-West - Zone 4 - Middle#448.9#171.4#878.0#South-West - Zone 4 - Top#448.9#171.4#1427.3#South-West - Zone 5 - Bottom#448.9#447.9#328.6#South-West - Zone 5 - Middle#448.9#447.9#878.0#South-West - Zone 5 - Top#448.9#447.9#1427.3#South-West - Zone 6 - Bottom#448.9#724.3#328.6#South-West - Zone 6 - Middle#448.9#724.3#878.0#South-West - Zone 6 - Top#448.9#724.3#1427.3#South-West - Zone 7 - Bottom#726.0#171.4#328.6#South-West - Zone 7 - Middle#726.0#171.4#878.0#South-West - Zone 7 - Top#726.0#171.4#1427.3#South-West - Zone 8 - Bottom#726.0#447.9#328.6#South-West - Zone 8 - Middle#726.0#447.9#878.0#South-West - Zone 8 - Top#726.0#447.9#1427.3#South-West - Zone 9 - Bottom#726.0#724.3#328.6#South-West - Zone 9 - Middle#726.0#724.3#878.0#South-West - Zone 9 - Top#726.0#724.3#1427.3#West - Zone 1 - Bottom#171.8#1000.7#328.6#West - Zone 1 - Middle#171.8#1000.7#878.0#West - Zone 1 - Top#171.8#1000.7#1427.3#West - Zone 2 - Bottom#171.8#1277.1#328.6#West - Zone 2 - Middle#171.8#1277.1#878.0#West - Zone 2 - Top#171.8#1277.1#1427.3#West - Zone 3 - Bottom#171.8#1553.6#328.6#West - Zone 3 - Middle#171.8#1553.6#878.0#West - Zone 3 - Top#171.8#1553.6#1427.3#West - Zone 4 - Bottom#448.9#1000.7#328.6#West - Zone 4 - Middle#448.9#1000.7#878.0#West - Zone 4 - Top#448.9#1000.7#1427.3#West - Zone 5 - Bottom#448.9#1277.1#328.6#West - Zone 5 - Middle#448.9#1277.1#878.0#West - Zone 5 - Top#448.9#1277.1#1427.3#West - Zone 6 - Bottom#448.9#1553.6#328.6#West - Zone 6 - Middle#448.9#1553.6#878.0#West - Zone 6 - Top#448.9#1553.6#1427.3#West - Zone 7 - Bottom#726.0#1000.7#328.6#West - Zone 7 - Middle#726.0#1000.7#878.0#West - Zone 7 - Top#726.0#1000.7#1427.3#West - Zone 8 - Bottom#726.0#1277.1#328.6#West - Zone 8 - Middle#726.0#1277.1#878.0#West - Zone 8 - Top#726.0#1277.1#1427.3#West - Zone 9 - Bottom#726.0#1553.6#328.6#West - Zone 9 - Middle#726.0#1553.6#878.0#West - Zone 9 - Top#726.0#1553.6#1427.3#North-West - Zone 1 - Bottom#171.8#1830.0#328.6#North-West - Zone 1 - Middle#171.8#1830.0#878.0#North-West - Zone 1 - Top#171.8#1830.0#1427.3#North-West - Zone 2 - Bottom#171.8#2106.4#328.6#North-West - Zone 2 - Middle#171.8#2106.4#878.0#North-West - Zone 2 - Top#171.8#2106.4#1427.3#North-West - Zone 3 - Bottom#171.8#2382.9#328.6#North-West - Zone 3 - Middle#171.8#2382.9#878.0#North-West - Zone 3 - Top#171.8#2382.9#1427.3#North-West - Zone 4 - Bottom#448.9#1830.0#328.6#North-West - Zone 4 - Middle#448.9#1830.0#878.0#North-West - Zone 4 - Top#448.9#1830.0#1427.3#North-West - Zone 5 - Bottom#448.9#2106.4#328.6#North-West - Zone 5 - Middle#448.9#2106.4#878.0#North-West - Zone 5 - Top#448.9#2106.4#1427.3#North-West - Zone 6 - Bottom#448.9#2382.9#328.6#North-West - Zone 6 - Middle#448.9#2382.9#878.0#North-West - Zone 6 - Top#448.9#2382.9#1427.3#North-West - Zone 7 - Bottom#726.0#1830.0#328.6#North-West - Zone 7 - Middle#726.0#1830.0#878.0#North-West - Zone 7 - Top#726.0#1830.0#1427.3#North-West - Zone 8 - Bottom#726.0#2106.4#328.6#North-West - Zone 8 - Middle#726.0#2106.4#878.0#North-West - Zone 8 - Top#726.0#2106.4#1427.3#North-West - Zone 9 - Bottom#726.0#2382.9#328.6#North-West - Zone 9 - Middle#726.0#2382.9#878.0#North-West - Zone 9 - Top#726.0#2382.9#1427.3#South - Zone 1 - Bottom#1003.1#171.4#328.6#South - Zone 1 - Middle#1003.1#171.4#878.0#South - Zone 1 - Top#1003.1#171.4#1427.3#South - Zone 2 - Bottom#1003.1#447.9#328.6#South - Zone 2 - Middle#1003.1#447.9#878.0#South - Zone 2 - Top#1003.1#447.9#1427.3#South - Zone 3 - Bottom#1003.1#724.3#328.6#South - Zone 3 - Middle#1003.1#724.3#878.0#South - Zone 3 - Top#1003.1#724.3#1427.3#South - Zone 4 - Bottom#1280.2#171.4#328.6#South - Zone 4 - Middle#1280.2#171.4#878.0#South - Zone 4 - Top#1280.2#171.4#1427.3#South - Zone 5 - Bottom#1280.2#447.9#328.6#South - Zone 5 - Middle#1280.2#447.9#878.0#South - Zone 5 - Top#1280.2#447.9#1427.3#South - Zone 6 - Bottom#1280.2#724.3#328.6#South - Zone 6 - Middle#1280.2#724.3#878.0#South - Zone 6 - Top#1280.2#724.3#1427.3#South - Zone 7 - Bottom#1557.3#171.4#328.6#South - Zone 7 - Middle#1557.3#171.4#878.0#South - Zone 7 - Top#1557.3#171.4#1427.3#South - Zone 8 - Bottom#1557.3#447.9#328.6#South - Zone 8 - Middle#1557.3#447.9#878.0#South - Zone 8 - Top#1557.3#447.9#1427.3#South - Zone 9 - Bottom#1557.3#724.3#328.6#South - Zone 9 - Middle#1557.3#724.3#878.0#South - Zone 9 - Top#1557.3#724.3#1427.3#Center - Zone 1 - Bottom#1003.1#1000.7#328.6#Center - Zone 1 - Middle#1003.1#1000.7#878.0#Center - Zone 1 - Top#1003.1#1000.7#1427.3#Center - Zone 2 - Bottom#1003.1#1277.1#328.6#Center - Zone 2 - Middle#1003.1#1277.1#878.0#Center - Zone 2 - Top#1003.1#1277.1#1427.3#Center - Zone 3 - Bottom#1003.1#1553.6#328.6#Center - Zone 3 - Middle#1003.1#1553.6#878.0#Center - Zone 3 - Top#1003.1#1553.6#1427.3#Center - Zone 4 - Bottom#1280.2#1000.7#328.6#Center - Zone 4 - Middle#1280.2#1000.7#878.0#Center - Zone 4 - Top#1280.2#1000.7#1427.3#Center - Zone 5 - Bottom#1280.2#1277.1#328.6#Center - Zone 5 - Middle#1280.2#1277.1#878.0#Center - Zone 5 - Top#1280.2#1277.1#1427.3#Center - Zone 6 - Bottom#1280.2#1553.6#328.6#Center - Zone 6 - Middle#1280.2#1553.6#878.0#Center - Zone 6 - Top#1280.2#1553.6#1427.3#Center - Zone 7 - Bottom#1557.3#1000.7#328.6#Center - Zone 7 - Middle#1557.3#1000.7#878.0#Center - Zone 7 - Top#1557.3#1000.7#1427.3#Center - Zone 8 - Bottom#1557.3#1277.1#328.6#Center - Zone 8 - Middle#1557.3#1277.1#878.0#Center - Zone 8 - Top#1557.3#1277.1#1427.3#Center - Zone 9 - Bottom#1557.3#1553.6#328.6#Center - Zone 9 - Middle#1557.3#1553.6#878.0#Center - Zone 9 - Top#1557.3#1553.6#1427.3#North - Zone 1 - Bottom#1003.1#1830.0#328.6#North - Zone 1 - Middle#1003.1#1830.0#878.0#North - Zone 1 - Top#1003.1#1830.0#1427.3#North - Zone 2 - Bottom#1003.1#2106.4#328.6#North - Zone 2 - Middle#1003.1#2106.4#878.0#North - Zone 2 - Top#1003.1#2106.4#1427.3#North - Zone 3 - Bottom#1003.1#2382.9#328.6#North - Zone 3 - Middle#1003.1#2382.9#878.0#North - Zone 3 - Top#1003.1#2382.9#1427.3#North - Zone 4 - Bottom#1280.2#1830.0#328.6#North - Zone 4 - Middle#1280.2#1830.0#878.0#North - Zone 4 - Top#1280.2#1830.0#1427.3#North - Zone 5 - Bottom#1280.2#2106.4#328.6#North - Zone 5 - Middle#1280.2#2106.4#878.0#North - Zone 5 - Top#1280.2#2106.4#1427.3#North - Zone 6 - Bottom#1280.2#2382.9#328.6#North - Zone 6 - Middle#1280.2#2382.9#878.0#North - Zone 6 - Top#1280.2#2382.9#1427.3#North - Zone 7 - Bottom#1557.3#1830.0#328.6#North - Zone 7 - Middle#1557.3#1830.0#878.0#North - Zone 7 - Top#1557.3#1830.0#1427.3#North - Zone 8 - Bottom#1557.3#2106.4#328.6#North - Zone 8 - Middle#1557.3#2106.4#878.0#North - Zone 8 - Top#1557.3#2106.4#1427.3#North - Zone 9 - Bottom#1557.3#2382.9#328.6#North - Zone 9 - Middle#1557.3#2382.9#878.0#North - Zone 9 - Top#1557.3#2382.9#1427.3#South-East - Zone 1 - Bottom#1834.4#171.4#328.6#South-East - Zone 1 - Middle#1834.4#171.4#878.0#South-East - Zone 1 - Top#1834.4#171.4#1427.3#South-East - Zone 2 - Bottom#1834.4#447.9#328.6#South-East - Zone 2 - Middle#1834.4#447.9#878.0#South-East - Zone 2 - Top#1834.4#447.9#1427.3#South-East - Zone 3 - Bottom#1834.4#724.3#328.6#South-East - Zone 3 - Middle#1834.4#724.3#878.0#South-East - Zone 3 - Top#1834.4#724.3#1427.3#South-East - Zone 4 - Bottom#2111.5#171.4#328.6#South-East - Zone 4 - Middle#2111.5#171.4#878.0#South-East - Zone 4 - Top#2111.5#171.4#1427.3#South-East - Zone 5 - Bottom#2111.5#447.9#328.6#South-East - Zone 5 - Middle#2111.5#447.9#878.0#South-East - Zone 5 - Top#2111.5#447.9#1427.3#South-East - Zone 6 - Bottom#2111.5#724.3#328.6#South-East - Zone 6 - Middle#2111.5#724.3#878.0#South-East - Zone 6 - Top#2111.5#724.3#1427.3#South-East - Zone 7 - Bottom#2388.6#171.4#328.6#South-East - Zone 7 - Middle#2388.6#171.4#878.0#South-East - Zone 7 - Top#2388.6#171.4#1427.3#South-East - Zone 8 - Bottom#2388.6#447.9#328.6#South-East - Zone 8 - Middle#2388.6#447.9#878.0#South-East - Zone 8 - Top#2388.6#447.9#1427.3#South-East - Zone 9 - Bottom#2388.6#724.3#328.6#South-East - Zone 9 - Middle#2388.6#724.3#878.0#South-East - Zone 9 - Top#2388.6#724.3#1427.3#East - Zone 1 - Bottom#1834.4#1000.7#328.6#East - Zone 1 - Middle#1834.4#1000.7#878.0#East - Zone 1 - Top#1834.4#1000.7#1427.3#East - Zone 2 - Bottom#1834.4#1277.1#328.6#East - Zone 2 - Middle#1834.4#1277.1#878.0#East - Zone 2 - Top#1834.4#1277.1#1427.3#East - Zone 3 - Bottom#1834.4#1553.6#328.6#East - Zone 3 - Middle#1834.4#1553.6#878.0#East - Zone 3 - Top#1834.4#1553.6#1427.3#East - Zone 4 - Bottom#2111.5#1000.7#328.6#East - Zone 4 - Middle#2111.5#1000.7#878.0#East - Zone 4 - Top#2111.5#1000.7#1427.3#East - Zone 5 - Bottom#2111.5#1277.1#328.6#East - Zone 5 - Middle#2111.5#1277.1#878.0#East - Zone 5 - Top#2111.5#1277.1#1427.3#East - Zone 6 - Bottom#2111.5#1553.6#328.6#East - Zone 6 - Middle#2111.5#1553.6#878.0#East - Zone 6 - Top#2111.5#1553.6#1427.3#East - Zone 7 - Bottom#2388.6#1000.7#328.6#East - Zone 7 - Middle#2388.6#1000.7#878.0#East - Zone 7 - Top#2388.6#1000.7#1427.3#East - Zone 8 - Bottom#2388.6#1277.1#328.6#East - Zone 8 - Middle#2388.6#1277.1#878.0#East - Zone 8 - Top#2388.6#1277.1#1427.3#East - Zone 9 - Bottom#2388.6#1553.6#328.6#East - Zone 9 - Middle#2388.6#1553.6#878.0#East - Zone 9 - Top#2388.6#1553.6#1427.3#North-East - Zone 1 - Bottom#1834.4#1830.0#328.6#North-East - Zone 1 - Middle#1834.4#1830.0#878.0#North-East - Zone 1 - Top#1834.4#1830.0#1427.3#North-East - Zone 2 - Bottom#1834.4#2106.4#328.6#North-East - Zone 2 - Middle#1834.4#2106.4#878.0#North-East - Zone 2 - Top#1834.4#2106.4#1427.3#North-East - Zone 3 - Bottom#1834.4#2382.9#328.6#North-East - Zone 3 - Middle#1834.4#2382.9#878.0#North-East - Zone 3 - Top#1834.4#2382.9#1427.3#North-East - Zone 4 - Bottom#2111.5#1830.0#328.6#North-East - Zone 4 - Middle#2111.5#1830.0#878.0#North-East - Zone 4 - Top#2111.5#1830.0#1427.3#North-East - Zone 5 - Bottom#2111.5#2106.4#328.6#North-East - Zone 5 - Middle#2111.5#2106.4#878.0#North-East - Zone 5 - Top#2111.5#2106.4#1427.3#North-East - Zone 6 - Bottom#2111.5#2382.9#328.6#North-East - Zone 6 - Middle#2111.5#2382.9#878.0#North-East - Zone 6 - Top#2111.5#2382.9#1427.3#North-East - Zone 7 - Bottom#2388.6#1830.0#328.6#North-East - Zone 7 - Middle#2388.6#1830.0#878.0#North-East - Zone 7 - Top#2388.6#1830.0#1427.3#North-East - Zone 8 - Bottom#2388.6#2106.4#328.6#North-East - Zone 8 - Middle#2388.6#2106.4#878.0#North-East - Zone 8 - Top#2388.6#2106.4#1427.3#North-East - Zone 9 - Bottom#2388.6#2382.9#328.6#North-East - Zone 9 - Middle#2388.6#2382.9#878.0#North-East - Zone 9 - Top#2388.6#2382.9#1427.3#```

**Comment by tmp64** [comment]
Yeah, it's hardcoded to 8 KiB. I'll fix it a bit later (hopefully even today)
https://github.com/tmp64/BugfixedHL-Rebased/blob/fc7061c1771cb4f5d0e983c3e970f1cef450ee5b/src/game/client/hud/ag/ag_location.cpp#L181

**Comment by tmp64** [comment]
I changed the code to use a heap buffer with exact file size. The limit is now 4 MiB (just so the game doesn't run out of memory when loading the file).

Please, test that it works with your file as well as any other location files.

**Comment by andreiseverin** [comment]
I confirm it's covering the last region written in the buffer `#North-East - Zone 9 - Top` -> so it's reading more than 8KiB

![image](https://user-images.githubusercontent.com/39212135/217854506-c2fe02a7-bc50-4cff-81ba-86253320f969.png)

Thank you for your help and keep going the good work!
