### ISSUE TITLE
Using BugfixedHl with RT

### ISSUE THREAD

**Issue by Mehmet-I** [tmp64/BugfixedHL-Rebased#164]
Hello Bro,

I recently saw the RayTracing mod for Half-Life come out. I tried this mod a bit. It was really enjoyable. 
But unfortunately it doesn't work with bugfixedhl :( 
I wanted to use Bugfixedhl client with this mod :) Is that possible?

RT Mod: https://github.com/sultim-t/xash-rt/releases/tag/1.0.5

Thanks for everything

**Comment by tmp64** [comment]
The RT mod uses Xash. BHL doesn't work on Xash because it doesn't support VGUI2.
