### ISSUE TITLE
 Translation into Russian in ScoreBoard

### ISSUE THREAD

**Issue by DJMayroN** [tmp64/BugfixedHL-Rebased#17]
Here's another thing you can do, is it possible to implement a translation into Russian in a .res file?

Also in version 1.5, the dedicated strip for your nickname ((

How about this?
You can put it somehow.

Thanks to Dmitry for the answer!

![1](https://user-images.githubusercontent.com/45271533/90967645-ceba0880-e4ea-11ea-95a6-bde8a3ee5ee8.jpg)
![7bf4a1ff8fd2](https://user-images.githubusercontent.com/45271533/90967646-d083cc00-e4ea-11ea-93c6-987bff61300e.jpg)

**Comment by tmp64** [comment]
Russian translation added by @EzicMan
Language indicator tracked in https://github.com/tmp64/hl1_source_sdk/issues/3
