### ISSUE TITLE
DLSS Support?

### ISSUE THREAD

**Issue by Mehmet-I** [tmp64/BugfixedHL-Rebased#171]
Hi Bro,

Is it possible to get dlss support using the bugfixedhl client? I'm asking because I don't know the technical part of this job.
Thx

**Comment by tmp64** [comment]
It's not possible.
1. DLSS doesn't support OpenGL.
2. The game is so old DLSS is completely unnecessary. All performance problems are caused by the game's renderer that doesn't use modern features. Fixing them would basically mean rewriting the renderer.
