### ISSUE TITLE
New 25th Anniversary build support

### ISSUE THREAD

**Issue by andreiseverin** [tmp64/BugfixedHL-Rebased#180]
Hello,

Following the 25th Anniversary update, they modified a lot of things in the client build and also on the server side.
Will BHL support in the future these changes?

**Comment by Supded** [comment]
After update 
[crash-2023-11-17-21-39-19.txt](https://github.com/tmp64/BugfixedHL-Rebased/files/13396538/crash-2023-11-17-21-39-19.txt)

**Comment by andreiseverin** [comment]
I confirm. I updated too, and game crashes whe retrying to add BHL

**Comment by lolface992** [comment]
@tmp64 Any way to make it work for new version? Would love to play on that one instead on moving back to previous:-)

**Comment by tmp64** [comment]
I'm working on it

**Comment by NEOKARTOXA** [comment]
[crash-2023-11-18-09-25-37.txt](https://github.com/tmp64/BugfixedHL-Rebased/files/13399225/crash-2023-11-18-09-25-37.txt)

**Comment by stylez1989** [comment]
When you do work on the client, see if you can fix the fonts from the new client to format correctly. I'm using the legacy one which fixes it but valve decided to make a mess with the fonts that everything with amxx is squished. 

Thank you so much!

**Comment by andreiseverin** [comment]
@tmp64  Thank you for your work!

**Comment by stylez1989** [comment]
> Client now works correctly on the updated version. SDK updates are tracked at #191

Does that mean the release is available? I'm unable to find it.
