### ISSUE TITLE
client crashed 

### ISSUE THREAD

**Issue by dragon-jpg** [tmp64/BugfixedHL-Rebased#183]
im new to this game so i dont know what cause it to crash sorry

crash report:
[crash-2023-11-21-17-48-00.txt](https://github.com/tmp64/BugfixedHL-Rebased/files/13424615/crash-2023-11-21-17-48-00.txt)

**Comment by dragon-jpg** [comment]
heres the .dmp file:
[crash-2023-11-21-17-48-00.dmp](https://github.com/tmp64/BugfixedHL-Rebased/files/13424646/crash-2023-11-21-17-48-00.dmp)

**Comment by tmp64** [comment]
Stack trace in the crash dump is unreadable. Can't debug this crash
