### ISSUE TITLE
Improve Steam player detection

### ISSUE THREAD

**Issue by Safety1st** [tmp64/BugfixedHL-Rebased#19]
![image](https://user-images.githubusercontent.com/1483401/89459260-085fe500-d771-11ea-8bfe-c76973aa4d20.png)
Both players are NOT Steam ones, both use emulators: saku – RevEmu, player – RevEmu2013. On CS 1.6 servers there is no such problem. I know that correct detection provided by Steam client itself there. But what if we could do pretty the same thing in BHL? It could be optional. Without that current detection is useless on non-Steam servers. As a fast fix I recommend checking 1st prefix. If it isn't equal to 0 it is NOT Steam player. It is true if DProto/ReUnion set to use prefix '0' only for Steam players.

```status
hostname:  AIMaster HL DM 2 | Classic
version :  48/1.1.2.2/Stdio 1501 secure  (70)
tcp/ip  :  89.223.32.156:27012
map     :  crossfire at: 0 x, 0 y, 0 z
players :  8 active (20 max)

#      name userid uniqueid frag time ping loss
# 1 "[PS] aligemar" 3665 STEAM_ID_LAN   3 04:26  115    0
# 2 "[BY] iPlayer" 3664 STEAM_1:0:497342880  12 05:00   37    0
# 3 "[UZ] player" 3660 STEAM_1:0:327059450  26 13:26   57    0
# 4 "[AR] Jam Gamer A-4872" 3666 STEAM_ID_LAN   2 02:24  257    0
# 5 "[RU] saku" 3652 STEAM_3:0:789662137  65 24:13   31    0
# 6 "[DE] MaMBA42" 3647 STEAM_ID_LAN 120 35:20   59    0
# 7 "[RU] [non-steam.ru] Player" 3668 STEAM_3:0:413054725   0 00:10   41    0
# 8 "[RU] VASYA111_PUTIN" 3656 STEAM_ID_LAN  37 20:51   14    0
8 users

dp_clientinfo 5
dp_r_id_provider
"dp_r_id_provider" is "4"

dp_clientinfo 3
dp_r_id_provider
"dp_r_id_provider" is "10"

#define DP_AUTH_REVEMU		4
#define DP_AUTH_REVEMU2013	10

**Comment by tmp64** [comment]
I added a few SteamID checks
- SteamID from the engine is checked to have account type equal to 1 (individual)
- SteamID from `status` is checked to begin with `0:Y:ZZZZZZZ`. Valve wiki says Universe ID is guaranteed to be 0 on GoldSrc servers.
