### ISSUE TITLE
Верхняя палка на прицеле белая

### ISSUE THREAD

**Issue by SoMudge** [tmp64/BugfixedHL-Rebased#190]
![fucking_crosshair](https://github.com/tmp64/BugfixedHL-Rebased/assets/116156230/1f95df4a-ce44-4add-a992-474b4ae3462f)

У друга такой проблемы нет; он скинул все свои файлы мне, а проблема по прежнему осталась.
Комплектующие ПК у нас практически идентичны за исключением видеокарты: у него NVidia (RTX 2060), у меня AMD (RX 6600XT)

**Comment by SoMudge** [comment]
Это валвовцы виноваты оказались.

**Comment by tmp64** [comment]
Дубликат #179. Баг был до нового обновления этого года. В сегодняшнем обновлении что-то исправили на картах AMD. Возможно проблема связана и с #177.

Цвет HUD настроен белым или это тоже баг?

**Comment by ItsNeverLight** [comment]
Это точно происходит только на видеокартах AMD. Похоже, что оно было и до обновления про 25 летие. Т.к если вернутся на раннюю версию, то баг будет и там. Также и в модах к голдсурс. Например cstrike и czero. Можно ли пофиксить этот баг со стороны bugfixed раз valve не могут. Могут ли быть виноваты какие-нибудь новые драйвера AMD? Там можно тоже покапатся если есть такая возможность.
