### ISSUE TITLE
Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005) at address 0x628687C3 (hw.dll).

### ISSUE THREAD

**Issue by isdpteam** [tmp64/BugfixedHL-Rebased#196]
BugfixedHL Crash Log
  Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005) at address 0x628687C3 (hw.dll).

Please post contents of this log file and file crash-2023-12-08-18-56-10.dmp on
https://github.com/tmp64/BugfixedHL-Rebased/issues

-------------------------------------------------------------------------
Technical information

Version: 1.10.0+master.1233402
Engine version: 1.1.2.2/Stdio,48,9899
Local time: 2023-12-08 18:56:10
OS version: 10.0.19041.3570

Stack trace (may be incorrect since no engine PDBs are available):
  628687C3 (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  5F5F9DA5 (client): (filename not available): ApplyMultiDamage
  5F5F9C46 (client): (filename not available): ApplyMultiDamage
  628D46EF (hw): (filename not available): vgui::Frame::operator=
  628C1D8F (hw): (filename not available): vgui::Frame::operator=
  628ECF12 (hw): (filename not available): vgui::Frame::operator=
  628BABA6 (hw): (filename not available): vgui::Frame::operator=
  628BA769 (hw): (filename not available): vgui::Dar<vgui::DesktopIcon *>::setElementAt
  628646C2 (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  6286284E (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  628B0EA9 (hw): (filename not available): F
  628B05CB (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  628AFFA8 (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  0020159C (hl): (filename not available): (function-name not available)
  00202E48 (hl): (filename not available): CreateInterface
  7653FCC9 (KERNEL32): (filename not available): BaseThreadInitThunk
  770C7C6E (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath
  770C7C3E (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath

Modules:
  Base     Size     Path (Exception Offset)
  00200000 0000B000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\hl.exe
  77060000 001A4000 C:\WINDOWS\SYSTEM32\ntdll.dll
  76520000 000F0000 C:\WINDOWS\System32\KERNEL32.DLL
  75BD0000 0023A000 C:\WINDOWS\System32\KERNELBASE.dll
  63B30000 0009F000 C:\WINDOWS\SYSTEM32\apphelp.dll
  768A0000 00063000 C:\WINDOWS\System32\WS2_32.dll
  76A30000 000BF000 C:\WINDOWS\System32\RPCRT4.dll
  75390000 0019C000 C:\WINDOWS\System32\USER32.dll
  76400000 00018000 C:\WINDOWS\System32\win32u.dll
  764F0000 00024000 C:\WINDOWS\System32\GDI32.dll
  76660000 000E8000 C:\WINDOWS\System32\gdi32full.dll
  76CB0000 0007B000 C:\WINDOWS\System32\msvcp_win.dll
  76250000 00120000 C:\WINDOWS\System32\ucrtbase.dll
  769B0000 0007B000 C:\WINDOWS\System32\ADVAPI32.dll
  76AF0000 000BF000 C:\WINDOWS\System32\msvcrt.dll
  76420000 00076000 C:\WINDOWS\System32\sechost.dll
  704A0000 00014000 C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
  76610000 00025000 C:\WINDOWS\System32\IMM32.DLL
  65130000 00150000 C:\Program Files (x86)\Steam\gameoverlayrenderer.dll
  76F60000 000E3000 C:\WINDOWS\System32\ole32.dll
  750A0000 00280000 C:\WINDOWS\System32\combase.dll
  76910000 00096000 C:\WINDOWS\System32\OLEAUT32.dll
  74F90000 0003B000 C:\WINDOWS\System32\CFGMGR32.dll
  76EA0000 00006000 C:\WINDOWS\System32\PSAPI.DLL
  6E880000 00028000 C:\WINDOWS\SYSTEM32\WINMM.dll
  67FD0000 00103000 C:\WINDOWS\SYSTEM32\OPENGL32.dll
  75610000 005B7000 C:\WINDOWS\System32\SHELL32.dll
  67CD0000 0003F000 C:\WINDOWS\SYSTEM32\GLU32.dll
  75E10000 00438000 C:\WINDOWS\System32\SETUPAPI.dll
  76640000 00019000 C:\WINDOWS\System32\bcrypt.dll
  74DF0000 00008000 C:\WINDOWS\SYSTEM32\VERSION.dll
  76370000 00087000 C:\WINDOWS\System32\SHCORE.DLL
  65960000 00093000 C:\WINDOWS\SYSTEM32\mscms.dll
  71BE0000 00025000 C:\WINDOWS\SYSTEM32\USERENV.dll
  65950000 0000C000 C:\WINDOWS\SYSTEM32\ColorAdapterClient.dll
  65910000 0003E000 C:\WINDOWS\SYSTEM32\icm32.dll
  66290000 012EF000 C:\Program Files (x86)\Steam\steamclient.dll
  767A0000 000FF000 C:\WINDOWS\System32\CRYPT32.dll
  76BB0000 00019000 C:\WINDOWS\System32\imagehlp.dll
  70790000 00032000 C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
  68E00000 00088000 C:\Program Files (x86)\Steam\vstdlib_s.dll
  698F0000 0009A000 C:\Program Files (x86)\Steam\tier0_s.dll
  70650000 00052000 C:\WINDOWS\SYSTEM32\MSWSOCK.dll
  6D210000 0000A000 C:\WINDOWS\SYSTEM32\Secur32.dll
  04EE0000 00045000 C:\WINDOWS\System32\SHLWAPI.dll
  6FA80000 00021000 C:\WINDOWS\SYSTEM32\SSPICLI.DLL
  72980000 0000A000 C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
  74FE0000 0005F000 C:\WINDOWS\System32\bcryptPrimitives.dll
  6A400000 000A7000 C:\Program Files (x86)\Steam\crashhandler.dll
  6D9A0000 00455000 C:\WINDOWS\SYSTEM32\WININET.dll
  6F360000 00074000 C:\WINDOWS\system32\uxtheme.dll
  10000000 02DB7000 C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks.dll
  74E00000 0000F000 C:\WINDOWS\SYSTEM32\kernel.appcore.dll
  76C30000 0007E000 C:\WINDOWS\System32\clbcatq.dll
  66180000 0006B000 C:\WINDOWS\System32\MMDevApi.dll
  70620000 00029000 C:\WINDOWS\System32\DEVOBJ.dll
  081F0000 00008000 C:\WINDOWS\SYSTEM32\avrt.dll
  6C2F0000 0000A000 C:\WINDOWS\SYSTEM32\hid.dll
  76750000 0004C000 C:\WINDOWS\System32\WINTRUST.dll
  70610000 0000E000 C:\WINDOWS\SYSTEM32\MSASN1.dll
  6BFF0000 00037000 C:\Windows\System32\dinput8.dll
  6AA70000 000ED000 C:\WINDOWS\SYSTEM32\inputhost.dll
  6B8F0000 000DC000 C:\WINDOWS\SYSTEM32\wintypes.dll
  6C400000 0009B000 C:\WINDOWS\SYSTEM32\CoreMessaging.dll
  729E0000 000C2000 C:\WINDOWS\SYSTEM32\PROPSYS.dll
  6B3F0000 0027F000 C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
  71B90000 00029000 C:\WINDOWS\SYSTEM32\ntmarta.dll
  64E00000 00098000 C:\Windows\System32\Windows.Gaming.Input.dll
  6C680000 00194000 C:\Windows\System32\twinapi.appcore.dll
  67CC0000 0000D000 C:\WINDOWS\SYSTEM32\XInput1_4.dll
  64DA0000 00056000 C:\WINDOWS\System32\SensorsApi.dll
  64D70000 00022000 C:\WINDOWS\System32\SensorsUtilsV2.dll
  64D40000 0002E000 C:\WINDOWS\System32\SensorsNativeApi.V2.dll
  704E0000 00044000 C:\WINDOWS\SYSTEM32\powrprof.dll
  704D0000 0000D000 C:\WINDOWS\SYSTEM32\UMPDC.dll
  64CA0000 00027000 C:\Windows\System32\PortableDeviceTypes.dll
  64C70000 00030000 C:\Windows\System32\deviceaccess.dll
  75530000 000D4000 C:\WINDOWS\System32\MSCTF.dll
  6C0B0000 000C0000 C:\Windows\System32\AppXDeploymentClient.dll
  5FC10000 02A76000 C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_b58fa54b9732141a\nvoglv32.dll
  70910000 0000F000 C:\WINDOWS\SYSTEM32\WTSAPI32.dll
  6ECA0000 00026000 C:\WINDOWS\SYSTEM32\cryptnet.dll
  6AB60000 00100000 C:\WINDOWS\SYSTEM32\drvstore.dll
  73F00000 00024000 C:\WINDOWS\SYSTEM32\wldp.dll
  6C9D0000 0002C000 C:\WINDOWS\SYSTEM32\dxcore.dll
  73F30000 00613000 C:\WINDOWS\SYSTEM32\windows.storage.dll
  64A40000 0022A000 C:\WINDOWS\system32\nvspcap.dll
  71BC0000 0001C000 C:\WINDOWS\SYSTEM32\profapi.dll
  6ECE0000 00026000 C:\WINDOWS\SYSTEM32\dwmapi.dll
  708C0000 00047000 C:\WINDOWS\SYSTEM32\WINSTA.dll
  6C310000 000BA000 C:\WINDOWS\SYSTEM32\textinputframework.dll
  0A400000 0005E000 C:\Program Files (x86)\DisplayFusion\Hooks\AppHook32_4E04F6A4-50C0-4552-AE08-27AFAB75A2D9.dll
  70530000 0008D000 C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3570_none_c0ddcb7e38bd1f11\COMCTL32.dll
  6EEA0000 000C2000 C:\WINDOWS\SYSTEM32\dxgi.dll
  6EF70000 001E0000 C:\WINDOWS\SYSTEM32\d3d11.dll
  649A0000 00096000 C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_b58fa54b9732141a\nvldumd.dll
  729C0000 00013000 C:\WINDOWS\System32\CRYPTSP.dll
  72990000 0002F000 C:\WINDOWS\system32\rsaenh.dll
  5B130000 03893000 C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_b58fa54b9732141a\nvwgf2um.dll
  6AC60000 0069C000 C:\WINDOWS\SYSTEM32\nvapi.dll
  65FE0000 00136000 C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
  65EA0000 000F3000 C:\Windows\System32\Windows.UI.dll
  65E20000 00073000 C:\Windows\System32\WindowManagementAPI.dll
  6F590000 00236000 C:\WINDOWS\SYSTEM32\iertutil.dll
  6F7D0000 0001E000 C:\WINDOWS\SYSTEM32\srvcli.dll
  6FCA0000 0000B000 C:\WINDOWS\SYSTEM32\netutils.dll
  27ED0000 0097F000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\icudt.dll
  644A0000 001B2000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\avcodec-53.dll
  64780000 00027000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\avutil-51.dll
  64740000 00033000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\avformat-53.dll
  74FD0000 00007000 C:\WINDOWS\System32\NSI.dll
  64D10000 00016000 C:\WINDOWS\system32\NLAapi.dll
  66210000 0007F000 C:\WINDOWS\SYSTEM32\dsound.dll
  661F0000 0001D000 C:\WINDOWS\SYSTEM32\winmmbase.dll
  6FC20000 0000F000 C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
  66140000 0003A000 C:\WINDOWS\SYSTEM32\wdmaud.drv
  66120000 00007000 C:\WINDOWS\SYSTEM32\ksuser.dll
  65FD0000 0000A000 C:\WINDOWS\SYSTEM32\msacm32.drv
  65FB0000 00019000 C:\WINDOWS\SYSTEM32\MSACM32.dll
  65FA0000 00008000 C:\WINDOWS\SYSTEM32\midimap.dll
  646C0000 00011000 C:\WINDOWS\system32\napinsp.dll
  646A0000 00016000 C:\WINDOWS\system32\pnrpnsp.dll
  65470000 00010000 C:\WINDOWS\system32\wshbth.dll
  70700000 00090000 C:\WINDOWS\SYSTEM32\DNSAPI.dll
  64D00000 0000E000 C:\WINDOWS\System32\winrnr.dll
  6FDC0000 00059000 C:\WINDOWS\System32\fwpuclnt.dll
  6FE20000 00008000 C:\Windows\System32\rasadhlp.dll
  6D0A0000 0007C000 C:\WINDOWS\System32\schannel.dll
  6D080000 00010000 C:\WINDOWS\SYSTEM32\mskeyprotect.dll
  6F9F0000 00028000 C:\WINDOWS\SYSTEM32\NTASN1.dll
  6FA20000 00021000 C:\WINDOWS\SYSTEM32\ncrypt.dll
  6D060000 0001F000 C:\WINDOWS\system32\ncryptsslp.dll
  65B10000 0005C000 C:\WINDOWS\system32\ntshrui.dll
  65B00000 0000E000 C:\WINDOWS\SYSTEM32\cscapi.dll
  6F150000 00210000 C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.3570_none_a868611086700d20\comctl32.dll
  75040000 0005E000 C:\WINDOWS\System32\coml2.dll
  65B70000 0000B000 C:\WINDOWS\SYSTEM32\LINKINFO.dll
  64440000 00019000 C:\WINDOWS\SYSTEM32\MPR.dll
  5FB00000 0009D000 C:\WINDOWS\system32\Windows.Storage.Search.dll
  6C2D0000 0001B000 C:\WINDOWS\SYSTEM32\edputil.dll
  585A0000 02B88000 C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_b58fa54b9732141a\nvd3dum.dll
  71A80000 0001E000 C:\WINDOWS\SYSTEM32\gpapi.dll
  6D120000 00095000 C:\WINDOWS\SYSTEM32\TextShaping.dll
  64D30000 00009000 C:\WINDOWS\System32\drprov.dll
  64960000 00018000 C:\WINDOWS\System32\ntlanman.dll
  64940000 00019000 C:\WINDOWS\System32\davclnt.dll
  64930000 0000A000 C:\WINDOWS\System32\DAVHLPR.dll
  648D0000 00054000 C:\WINDOWS\System32\dokannp1.dll
  64860000 00063000 C:\WINDOWS\SYSTEM32\dokan1.dll
  6FC50000 00010000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\filesystem_stdio.dll
=>62690000 01499000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\hw.dll  <==  001D87C3
  64F30000 001F7000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\SDL2.dll
  6A4B0000 00008000 C:\WINDOWS\SYSTEM32\WSOCK32.dll
  654C0000 00042000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\steam_api.dll
  653D0000 00082000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mss32.dll
  64EA0000 00086000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\vgui.dll
  70430000 0006D000 C:\WINDOWS\SYSTEM32\MSVCP140.dll
  5F550000 00441000 c:\program files (x86)\steam\steamapps\common\half-life\valve_addon\cl_dlls\client.dll
  6FC30000 0001E000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\tier0.dll
  6FAB0000 00020000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\vstdlib.dll
  6F400000 00188000 C:\WINDOWS\SYSTEM32\dbghelp.dll
  64CD0000 0002B000 C:\WINDOWS\SYSTEM32\dbgcore.DLL
  647C0000 0002E000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\vgui2.dll
  5EC10000 000DC000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\chromehtml.dll
  57210000 0138F000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\libcef.dll
  76EB0000 000AF000 C:\WINDOWS\System32\COMDLG32.dll
  6EA90000 00017000 C:\WINDOWS\SYSTEM32\USP10.dll
  6D300000 000CA000 C:\WINDOWS\SYSTEM32\WINHTTP.dll
  6FCF0000 00076000 C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
  6F7F0000 001A9000 C:\WINDOWS\SYSTEM32\urlmon.dll
  6D090000 00006000 C:\WINDOWS\SYSTEM32\MSIMG32.dll
  5EB30000 000DF000 c:\program files (x86)\steam\steamapps\common\half-life\valve\cl_dlls\GameUI.dll
  64720000 00016000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mssmp3.asi
  646F0000 0002A000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mssvoice.asi
  65480000 0000C000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\demoplayer.dll
  64460000 00035000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\core.dll
  643C0000 00079000 c:\program files (x86)\steam\steamapps\common\half-life\platform\servers\serverbrowser.dll

Validating heap
CRT heap: validated successfully
Process heap: validated successfully

**Comment by tmp64** [comment]
Please, upload `crash-2023-12-08-18-56-10.dmp`. It will be in the game folder.

**Comment by isdpteam** [comment]
[crash-2023-12-15-15-39-53.dmp](https://github.com/tmp64/BugfixedHL-Rebased/files/13693573/crash-2023-12-15-15-39-53.dmp)
[crash-2023-12-15-15-39-53.txt](https://github.com/tmp64/BugfixedHL-Rebased/files/13693574/crash-2023-12-15-15-39-53.txt)
[crash-2023-12-16-09-59-04.dmp](https://github.com/tmp64/BugfixedHL-Rebased/files/13693575/crash-2023-12-16-09-59-04.dmp)
[crash-2023-12-16-09-59-04.txt](https://github.com/tmp64/BugfixedHL-Rebased/files/13693576/crash-2023-12-16-09-59-04.txt)
[crash-2023-12-08-07-13-28.dmp](https://github.com/tmp64/BugfixedHL-Rebased/files/13693577/crash-2023-12-08-07-13-28.dmp)
[crash-2023-12-08-07-13-28.txt](https://github.com/tmp64/BugfixedHL-Rebased/files/13693578/crash-2023-12-08-07-13-28.txt)
[crash-2023-12-08-18-56-10.dmp](https://github.com/tmp64/BugfixedHL-Rebased/files/13693579/crash-2023-12-08-18-56-10.dmp)
[crash-2023-12-08-18-56-10.txt](https://github.com/tmp64/BugfixedHL-Rebased/files/13693580/crash-2023-12-08-18-56-10.txt)
[crash-2023-12-09-10-43-15.dmp](https://github.com/tmp64/BugfixedHL-Rebased/files/13693581/crash-2023-12-09-10-43-15.dmp)
[crash-2023-12-09-10-43-15.txt](https://github.com/tmp64/BugfixedHL-Rebased/files/13693582/crash-2023-12-09-10-43-15.txt)
[crash-2023-12-13-22-59-19.dmp](https://github.com/tmp64/BugfixedHL-Rebased/files/13693583/crash-2023-12-13-22-59-19.dmp)
[crash-2023-12-13-22-59-19.txt](https://github.com/tmp64/BugfixedHL-Rebased/files/13693584/crash-2023-12-13-22-59-19.txt)

**Comment by tmp64** [comment]
Will be fixed in the next release (probably)
