### ISSUE TITLE
dont see time left

### ISSUE THREAD

**Issue by fatchiiii** [tmp64/BugfixedHL-Rebased#199]
hello i have bhl and when i click on the time i have left or the time spent nothing happens.... And I don't see the votemaps, the votes above on the left like before, it's a problem at the HUD level, thanks for your help

**Comment by tmp64** [comment]
Do you have an AMD Radeon RX 6000 or 7000 GPU? If so, [it's a driver bug](https://github.com/ValveSoftware/halflife/issues/3408#issuecomment-1841919844). You need to update the driver to `v23.12.1` or newer.

**Comment by fatchiiii** [comment]
Its my fault color has been put in black so i dont ses it .
Excuse me.
Fatchi
