### ISSUE TITLE
Mouse input breaks at certain angles

### ISSUE THREAD

**Issue by Fujinn981** [tmp64/BugfixedHL-Rebased#2]
So after the other day's issue I decided it might be easier to simply migrate my code to this SDK. And I think it will be since beforehand I was (And still am unless a workaround can be found for this bug) using the Xash3d SDK.

Mouse input breaks at certain angles never allowing me to turn 360 degrees. Forcing me to turn the other way, also applies to looking up and down.  Happens third person and first person. This is a bug I've seen in the Half-Life SDK, (I opened an issue there to no avail) and what prompted me to initially move to the Xash3d SDK as I've no clue what's causing it.

I've tested it with both Windows and Linux versions, the bug persists in both versions. Any insight into this bug is greatly appreciated as I would really love to be able to use this SDK.

**Comment by tmp64** [comment]
It only happens if mod name is not "valve", "cstrike" or other Valve game. For whatever reason, the engine only enables relative mouse input for these games. When it's not enabled, hidden mouse cursor will move around the window and will stop when it hits the edges of the window. That limits the angles for mouse movement.

There is a great PR by dtugend https://github.com/ValveSoftware/halflife/pull/1900 that fixes a lot of bugs in mouse input code but most of the fixes for WinAPI-based input method.

Instead of it, this SDK provides SDL2 raw input on Windows and Linux (`m_input 2`, equivalent to `m_rawinput 1`) and DirectInput API raw input on Windows (`m_input 1`). The value of `m_input` is chosen automatically and WinAPI input is never enabled that way.

I pushed a commit that fixes the issue but I only tested it on Windows. Please test it on Linux when you have a moment.

**Comment by Fujinn981** [comment]
> It only happens if mod name is not "valve", "cstrike" or other Valve game. For whatever reason, the engine only enables relative mouse input for these games. When it's not enabled, hidden mouse cursor will move around the window and will stop when it hits the edges of the window. That limits the angles for mouse movement.
> 
> There is a great PR by dtugend [ValveSoftware/halflife#1900](https://github.com/ValveSoftware/halflife/pull/1900) that fixes a lot of bugs in mouse input code but most of the fixes for WinAPI-based input method.
> 
> Instead of it, this SDK provides SDL2 raw input on Windows and Linux (`m_input 2`, equivalent to `m_rawinput 1`) and DirectInput API raw input on Windows (`m_input 1`). The value of `m_input` is chosen automatically and WinAPI input is never enabled that way.
> 
> I pushed a commit that fixes the issue but I only tested it on Windows. Please test it on Linux when you have a moment.

Unfortunately I can't test this as I'm getting a segmentation fault whenever I try to load a map.

Console output when loading the main menu:
```
LoadSchemeFromFile: Failed to open 'ui/resource/ClientSourceScheme.res'
Unable to access SteamHTMLSurface
Command Menu: Failed to parse commandmenu_default.txt.
HookConsoleColor: check failed.
  Expected: 216 222 211 255
  Got: 0 150 150 255.
Failed to hook console color.
Engine patch: unsupported platform.CClientSteamContext logged on = 1
LoadSchemeFromFile: 'ui/resource/ChatScheme.res' has changed, will be recompiled.
LoadSchemeFromFile: Failed to open 'ui/resource/ChatScheme.res'
LoadSchemeFromFile: 'ui/resource/ChatScheme.res' has changed, will be recompiled.
LoadSchemeFromFile: Failed to open 'ui/resource/ChatScheme.res'
SVC: Engine svc array not found, handlers not installed.
Set mouse input mode to Raw Input.
```

version:
```

Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 19:53:35 Aug  3 2020 (8684)

```

about:
```

BugfixedHL-NG
Bugfixed and improved Half-Life Client
Version: 0.1.0-dev+master.c4c0fd4.m

Github: https://github.com/tmp64/BugfixedHL-Rebased
Discussion forum: http://aghl.ru/forum/viewtopic.php?f=36&t=686

```
Some system information:
```
Distro: Archlinux
GPU: Nvidia RTX 2070
Nvidia driver: Proprietary
Driver version:  455.45.01
CPU: AMD

```

Relevant terminal output after crash:
```
/tmp/dumps/assert_20201231054528_1.dmp
>>> Adding process 1429696 for game ID 16777286
assert_20201231054528_1.dmp[1429697]: Finished uploading minidump (out-of-process): success = yes
assert_20201231054528_1.dmp[1429697]: response: Discarded=1
assert_20201231054528_1.dmp[1429697]: file ''/tmp/dumps/assert_20201231054528_1.dmp'', upload yes: ''Discarded=1''
pid 1429697 != 1429696, skipping destruction (fork without exec?)
<Half-Life path>/hl.sh: line 43: 1428480 Segmentation fault      (core dumped) ${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} $@

```

gdb output:
```
Core was generated by `<Half-Life path>/hl_linux -s'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xcd880647 in ClientConnect(edict_s*, char const*, char const*, char*) () from <Mod path>/dlls/hl.so

```

Some farther information that may be relevant is that I run a system with multiple drives, Half-Life being  on an old NTFS drive. While the rest of the system is EXT4. If there's anymore information you need, let me know.

**Comment by tmp64** [comment]
It turned out that I never actually tested server library on Linux. I fixed the problem in 14b299211b97d0653e2093cf81c0863d915c631e.

**Comment by Fujinn981** [comment]
> It turned out that I never actually tested server library on Linux. I fixed the problem in [14b2992](https://github.com/tmp64/BugfixedHL-Rebased/commit/14b299211b97d0653e2093cf81c0863d915c631e).

Crash is fixed. Mouse is still broken.

**Comment by tmp64** [comment]
Now mouse input is definitely fixed.

**Comment by Fujinn981** [comment]
> Now mouse input is definitely fixed.

I'm happy to report it is now possible to do 360 no scopes. Thank you very much for looking into these issues. :) I will let you know if there's anything else.
