### ISSUE TITLE
Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005) at address 0x594CF26F (client.dll)

### ISSUE THREAD

**Issue by headshoter** [tmp64/BugfixedHL-Rebased#201]
BugfixedHL Crash Log
  Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005) at address 0x594CF26F (client.dll).

Please post contents of this log file and file crash-2023-12-17-21-43-02.dmp on
https://github.com/tmp64/BugfixedHL-Rebased/issues

-------------------------------------------------------------------------
Technical information

Version: 1.10.2+master.6750a4c
Engine version: 1.1.2.2,48,9909
Local time: 2023-12-17 21:43:02
OS version: 10.0.19041.3636

Stack trace (may be incorrect since no engine PDBs are available):
  594CF26F (client): (filename not available): ApplyMultiDamage
  5948E168 (client): (filename not available): ApplyMultiDamage
  5947961B (client): (filename not available): ApplyMultiDamage
  57A16F5C (hw): (filename not available): CreateInterface
  57ADD306 (hw): (filename not available): vgui::Frame::operator=
  57AAAF36 (hw): (filename not available): vgui::Frame::operator=
  57AAAAF9 (hw): (filename not available): vgui::Dar<vgui::DesktopIcon *>::setElementAt
  57A54792 (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  57A5291E (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  57AA11F9 (hw): (filename not available): F
  57AA091B (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  57AA02F8 (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  00C3159C (hl): (filename not available): (function-name not available)
  00C32E48 (hl): (filename not available): CreateInterface
  7699FCC9 (KERNEL32): (filename not available): BaseThreadInitThunk
  775D7C6E (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath
  775D7C3E (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath

Modules:
  Base     Size     Path (Exception Offset)
  00C30000 0000B000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\hl.exe
  77570000 001A4000 C:\WINDOWS\SYSTEM32\ntdll.dll
  76980000 000F0000 C:\WINDOWS\System32\KERNEL32.DLL
  76740000 0023A000 C:\WINDOWS\System32\KERNELBASE.dll
  75190000 0009F000 C:\WINDOWS\SYSTEM32\apphelp.dll
  75BC0000 00063000 C:\WINDOWS\System32\WS2_32.dll
  76440000 000BF000 C:\WINDOWS\System32\RPCRT4.dll
  761A0000 0019C000 C:\WINDOWS\System32\USER32.dll
  76720000 00018000 C:\WINDOWS\System32\win32u.dll
  75E50000 00024000 C:\WINDOWS\System32\GDI32.dll
  75EA0000 000E8000 C:\WINDOWS\System32\gdi32full.dll
  75D90000 0007B000 C:\WINDOWS\System32\msvcp_win.dll
  76080000 00120000 C:\WINDOWS\System32\ucrtbase.dll
  76580000 0007C000 C:\WINDOWS\System32\ADVAPI32.dll
  76D80000 000BF000 C:\WINDOWS\System32\msvcrt.dll
  76500000 00076000 C:\WINDOWS\System32\sechost.dll
  64680000 00014000 C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
  76D50000 00025000 C:\WINDOWS\System32\IMM32.DLL
  64670000 00010000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\filesystem_stdio.dll
  57880000 014AA000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\hw.dll
  73D00000 00028000 C:\WINDOWS\SYSTEM32\WINMM.dll
  75170000 00008000 C:\WINDOWS\SYSTEM32\WSOCK32.dll
  64620000 00042000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\steam_api.dll
  66FF0000 00103000 C:\WINDOWS\SYSTEM32\OPENGL32.dll
  75600000 005B7000 C:\WINDOWS\System32\SHELL32.dll
  76A70000 00280000 C:\WINDOWS\System32\combase.dll
  64310000 001F7000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\SDL2.dll
  75410000 000E3000 C:\WINDOWS\System32\ole32.dll
  763A0000 00096000 C:\WINDOWS\System32\OLEAUT32.dll
  64280000 00086000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\vgui.dll
  76E40000 00438000 C:\WINDOWS\System32\SETUPAPI.dll
  75E10000 0003B000 C:\WINDOWS\System32\cfgmgr32.dll
  75E80000 00019000 C:\WINDOWS\System32\bcrypt.dll
  645B0000 0006D000 C:\WINDOWS\SYSTEM32\MSVCP140.dll
  6D7C0000 0003F000 C:\WINDOWS\SYSTEM32\GLU32.dll
  75180000 00008000 C:\WINDOWS\SYSTEM32\VERSION.dll
  641F0000 00082000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mss32.dll
  75F90000 00087000 C:\WINDOWS\System32\SHCORE.DLL
  71600000 00093000 C:\WINDOWS\SYSTEM32\mscms.dll
  750C0000 00025000 C:\WINDOWS\SYSTEM32\USERENV.dll
  71A60000 0000C000 C:\WINDOWS\SYSTEM32\ColorAdapterClient.dll
  5A0E0000 0003E000 C:\WINDOWS\SYSTEM32\icm32.dll
  5A330000 012EF000 C:\Program Files (x86)\Steam\steamclient.dll
  76340000 00045000 C:\WINDOWS\System32\SHLWAPI.dll
  75500000 000FF000 C:\WINDOWS\System32\CRYPT32.dll
  77380000 00019000 C:\WINDOWS\System32\imagehlp.dll
  76600000 00006000 C:\WINDOWS\System32\PSAPI.DLL
  74F60000 00032000 C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
  6D620000 0009A000 C:\Program Files (x86)\Steam\tier0_s.dll
  67300000 00088000 C:\Program Files (x86)\Steam\vstdlib_s.dll
  74FD0000 00052000 C:\WINDOWS\SYSTEM32\MSWSOCK.dll
  6BD50000 0000A000 C:\WINDOWS\SYSTEM32\Secur32.dll
  72120000 00021000 C:\WINDOWS\SYSTEM32\SSPICLI.DLL
  73D60000 0000A000 C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
  77320000 0005F000 C:\WINDOWS\System32\bcryptPrimitives.dll
  71A70000 000A7000 C:\Program Files (x86)\Steam\crashhandler.dll
  6C7A0000 00455000 C:\WINDOWS\SYSTEM32\WININET.dll
  63C40000 00150000 C:\Program Files (x86)\Steam\gameoverlayrenderer.dll
  75030000 00074000 C:\WINDOWS\system32\uxtheme.dll
  74D30000 0000F000 C:\WINDOWS\SYSTEM32\kernel.appcore.dll
  75C30000 0007E000 C:\WINDOWS\System32\clbcatq.dll
  70970000 0006B000 C:\WINDOWS\System32\MMDevApi.dll
  72700000 00029000 C:\WINDOWS\System32\DEVOBJ.dll
  6F1E0000 00008000 C:\WINDOWS\SYSTEM32\avrt.dll
  6EFC0000 0000A000 C:\WINDOWS\SYSTEM32\hid.dll
  77510000 0004C000 C:\WINDOWS\System32\WINTRUST.dll
  719F0000 0000E000 C:\WINDOWS\SYSTEM32\MSASN1.dll
  6D0D0000 00037000 C:\Windows\System32\dinput8.dll
  6E820000 000ED000 C:\WINDOWS\SYSTEM32\inputhost.dll
  6C090000 0009B000 C:\WINDOWS\SYSTEM32\CoreMessaging.dll
  72050000 000C2000 C:\WINDOWS\SYSTEM32\PROPSYS.dll
  6C130000 000DC000 C:\WINDOWS\SYSTEM32\wintypes.dll
  6BE10000 0027F000 C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
  72020000 00029000 C:\WINDOWS\SYSTEM32\ntmarta.dll
  64150000 00098000 C:\Windows\System32\Windows.Gaming.Input.dll
  6AA10000 00194000 C:\Windows\System32\twinapi.appcore.dll
  6EE90000 0000D000 C:\WINDOWS\SYSTEM32\XInput1_4.dll
  640F0000 00056000 C:\WINDOWS\System32\SensorsApi.dll
  640C0000 00022000 C:\WINDOWS\System32\SensorsUtilsV2.dll
  63ED0000 0002E000 C:\WINDOWS\System32\SensorsNativeApi.V2.dll
  71A10000 00044000 C:\WINDOWS\SYSTEM32\powrprof.dll
  71A00000 0000D000 C:\WINDOWS\SYSTEM32\UMPDC.dll
  63C10000 00027000 C:\Windows\System32\PortableDeviceTypes.dll
  63260000 00030000 C:\Windows\System32\deviceaccess.dll
  631D0000 00083000 C:\Windows\System32\PortableDeviceApi.dll
  75CB0000 000D4000 C:\WINDOWS\System32\MSCTF.dll
  59D40000 000C0000 C:\Windows\System32\AppXDeploymentClient.dll
  633A0000 00865000 C:\WINDOWS\SYSTEM32\ig75icd32.dll
  69560000 008CB000 C:\WINDOWS\SYSTEM32\igdusc32.dll
  74FA0000 0000F000 C:\WINDOWS\SYSTEM32\WTSAPI32.dll
  6BDE0000 00026000 C:\WINDOWS\SYSTEM32\dwmapi.dll
  6CEA0000 0002C000 C:\WINDOWS\SYSTEM32\dxcore.dll
  6E640000 001DD000 C:\Windows\System32\msxml6.dll
  6C210000 000BA000 C:\WINDOWS\SYSTEM32\textinputframework.dll
  6AE90000 000C2000 C:\WINDOWS\SYSTEM32\dxgi.dll
  6B7E0000 001E0000 C:\WINDOWS\SYSTEM32\d3d11.dll
  69E30000 00BD8000 C:\WINDOWS\SYSTEM32\igd10iumd32.dll
  6D040000 00021000 C:\WINDOWS\SYSTEM32\ncrypt.dll
  6D010000 00028000 C:\WINDOWS\SYSTEM32\NTASN1.dll
  6D8F0000 00136000 C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
  6E910000 000F3000 C:\Windows\System32\Windows.UI.dll
  71580000 00073000 C:\Windows\System32\WindowManagementAPI.dll
=>59430000 00441000 c:\program files (x86)\steam\steamapps\common\half-life\valve_addon\cl_dlls\client.dll  <==  0009F26F
  631B0000 0001E000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\tier0.dll
  63190000 00020000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\vstdlib.dll
  74DD0000 00188000 C:\WINDOWS\SYSTEM32\dbghelp.dll
  74480000 0002B000 C:\WINDOWS\SYSTEM32\dbgcore.DLL
  62DA0000 0002E000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\vgui2.dll
  59350000 000DC000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\chromehtml.dll
  564F0000 0138F000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\libcef.dll
  72270000 000CA000 C:\WINDOWS\SYSTEM32\WINHTTP.dll
  64F30000 00017000 C:\WINDOWS\SYSTEM32\USP10.dll
  721E0000 0008D000 C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_c0df324c38bbc0ce\COMCTL32.dll
  75230000 0007D000 C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
  65F50000 001A9000 C:\WINDOWS\SYSTEM32\urlmon.dll
  752B0000 00006000 C:\WINDOWS\SYSTEM32\MSIMG32.dll
  66740000 00236000 C:\WINDOWS\SYSTEM32\iertutil.dll
  74CF0000 0001D000 C:\WINDOWS\SYSTEM32\srvcli.dll
  73D30000 0000B000 C:\WINDOWS\SYSTEM32\netutils.dll
  22F20000 000AF000 C:\WINDOWS\System32\COMDLG32.dll
  59270000 000DF000 c:\program files (x86)\steam\steamapps\common\half-life\valve\cl_dlls\GameUI.dll
  233F0000 0097F000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\icudt.dll
  590B0000 001B2000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\avcodec-53.dll
  62D70000 00027000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\avutil-51.dll
  62D30000 00033000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\avformat-53.dll
  76390000 00007000 C:\WINDOWS\System32\NSI.dll
  6BD70000 00016000 C:\WINDOWS\system32\NLAapi.dll
  5A2B0000 0007F000 C:\WINDOWS\SYSTEM32\dsound.dll
  6D4C0000 0001D000 C:\WINDOWS\SYSTEM32\winmmbase.dll
  6EE80000 0000F000 C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
  63170000 00016000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mssmp3.asi
  59080000 0002A000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mssvoice.asi
  59060000 00015000 C:\WINDOWS\SYSTEM32\mcicda.dll
  5A270000 0003A000 C:\WINDOWS\SYSTEM32\wdmaud.drv
  6D7B0000 00007000 C:\WINDOWS\SYSTEM32\ksuser.dll
  6D7A0000 0000A000 C:\WINDOWS\SYSTEM32\msacm32.drv
  6D4E0000 00019000 C:\WINDOWS\SYSTEM32\MSACM32.dll
  6D790000 00008000 C:\WINDOWS\SYSTEM32\midimap.dll
  645A0000 0000C000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\demoplayer.dll
  59020000 00035000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\core.dll
  646D0000 00079000 c:\program files (x86)\steam\steamapps\common\half-life\platform\servers\serverbrowser.dll
  73C00000 00090000 C:\WINDOWS\SYSTEM32\DNSAPI.dll
  71420000 00008000 C:\Windows\System32\rasadhlp.dll
  71430000 00058000 C:\WINDOWS\System32\fwpuclnt.dll
  6CF90000 0007C000 C:\WINDOWS\System32\schannel.dll
  6CF50000 00010000 C:\WINDOWS\SYSTEM32\mskeyprotect.dll
  6CF30000 0001F000 C:\WINDOWS\system32\ncryptsslp.dll
  71330000 00011000 C:\WINDOWS\system32\napinsp.dll
  70950000 00016000 C:\WINDOWS\system32\pnrpnsp.dll
  71320000 00010000 C:\WINDOWS\system32\wshbth.dll
  6BD60000 0000E000 C:\WINDOWS\System32\winrnr.dll

Validating heap
CRT heap: validated successfully
Process heap: validated successfully
[crash-2023-12-17-21-43-02.dmp](https://github.com/tmp64/BugfixedHL-Rebased/files/13698389/crash-2023-12-17-21-43-02.dmp)

**Comment by tmp64** [comment]
Will be fixed in the next release
