### ISSUE TITLE
AG (.loc) location file cannot be found

### ISSUE THREAD

**Issue by kemalcom** [tmp64/BugfixedHL-Rebased#205]
A bug in new versions is unable to find the location even though the file exists, returning "%l" in chat as empty

![1111](https://github.com/tmp64/BugfixedHL-Rebased/assets/66857556/24e0bd33-f55f-4a48-ae4c-d65adb3c92d8)
![2222](https://github.com/tmp64/BugfixedHL-Rebased/assets/66857556/d248931d-5646-42a0-88d8-bec6ed3415e1)

**Comment by andreiseverin** [comment]
I have the same issue.

**Comment by tmp64** [comment]
Fixed. `fread` was returning 0 for whatever reason so I just replaced file reading with engine's `IFileSystem`
