### ISSUE TITLE
Support for other HL based games (Opposing Force, Blue Shift, etc.)

### ISSUE THREAD

**Issue by LukaTV939** [tmp64/BugfixedHL-Rebased#211]
From what I've seen this mod only works for base Half-Life, but I thought it would also work on other games like Opposing Force, Blue Shift and similar.

**Comment by LukaTV939** [comment]
If you rename the "valve_addon" folder to something like "cstrike_addon" the mod will work on the game you're playing, however the gui elements might be bugged so I'm going to make a separate issue on that.

**Comment by tmp64** [comment]
BHL only supports Half-Life and Adrenaline Gamer. Other games/mods have custom client code (HUD, weapon prediction, etc). BHL doesn't support them.
