### ISSUE TITLE
cl_bhopcap doesnt work.

### ISSUE THREAD

**Issue by craccbaccLMAO** [tmp64/BugfixedHL-Rebased#218]
when i put in the command "cl_bhopcap 0" in the console, the cap is still at 556. how do i fix this.

https://github.com/tmp64/BugfixedHL-Rebased/assets/149659800/69fe0046-392a-4ab3-946b-6f60fb490539

**Comment by tmp64** [comment]
`cl_bhopcap 0` only disables the client-side speed cap. It still exists on the local server. To disable it, install [BugfixedHL server](https://github.com/tmp64/BugfixedHL-Rebased/releases) and run command `mp_bunnyhop 1`.

**Comment by craccbaccLMAO** [comment]
thank you.
