### ISSUE TITLE
This happens and the application crashes completely..

### ISSUE THREAD

**Issue by telekinetic1** [tmp64/BugfixedHL-Rebased#219]
SYMPTOMS: WHEN I CLICK JOIN FOR JOINING A SERVER, PROGRESSBAR IS SLIGHTLY BEING FILLED AND THE PROGRAM CRASHES COMPLETELY. IT HAPPENS USUALLY WHEN MY PING IS RELATIVELY HIGH OR MY CONNECTION IS UNSTABLE.

BugfixedHL Crash Log
  Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005) at address 0x1AC3A140 (< module not found >).

Please post contents of this log file and file crash-2024-04-30-21-06-26.dmp on
https://github.com/tmp64/BugfixedHL-Rebased/issues

-------------------------------------------------------------------------
Technical information

Version: 1.10.4+master.1a1f601
Engine version: 1.1.2.1,48,4554
Local time: 2024-04-30 21:06:26
OS version: 10.0.19041.3155

Stack trace (may be incorrect since no engine PDBs are available):
  ERROR: SymGetModuleInfo64, GetLastError: 1114 (Address: 1AC3A140)
  1AC3A140 ((module-name not available)): (filename not available): (function-name not available)
  23F8C88B (serverbrowser): (filename not available): JoiningSecureServerCall
  721D7555 (revSrvBrowser): (filename not available): CreateInterface
  721D1013 (revSrvBrowser): (filename not available): (function-name not available)
  0F5F070C (GameUI): (filename not available): CreateInterface
  0F5E394F (GameUI): (filename not available): (function-name not available)

Modules:
  Base     Size     Path (Exception Offset)
  01400000 02118000 D:\cs16v2017_oyunyoneticisi\hl.exe
  77430000 001A4000 C:\Windows\SYSTEM32\ntdll.dll
  76B20000 000F0000 C:\Windows\System32\KERNEL32.DLL
  75210000 00015000 C:\Program Files\Avast Software\Avast\x86\aswhook.dll
  75850000 0023A000 C:\Windows\System32\KERNELBASE.dll
  75230000 000A0000 C:\Windows\SYSTEM32\apphelp.dll
  71560000 00253000 C:\Windows\SYSTEM32\AcGenral.DLL
  75CA0000 000BF000 C:\Windows\System32\msvcrt.dll
  76AA0000 00076000 C:\Windows\System32\sechost.dll
  75D60000 000BF000 C:\Windows\System32\RPCRT4.dll
  76CC0000 00045000 C:\Windows\System32\SHLWAPI.dll
  76D10000 0019C000 C:\Windows\System32\USER32.dll
  76C60000 00018000 C:\Windows\System32\win32u.dll
  76EB0000 00024000 C:\Windows\System32\GDI32.dll
  75360000 000E5000 C:\Windows\System32\gdi32full.dll
  77050000 0007B000 C:\Windows\System32\msvcp_win.dll
  76980000 00120000 C:\Windows\System32\ucrtbase.dll
  754E0000 000E3000 C:\Windows\System32\ole32.dll
  755D0000 00280000 C:\Windows\System32\combase.dll
  75A90000 00096000 C:\Windows\System32\OLEAUT32.dll
  75E80000 005B6000 C:\Windows\System32\SHELL32.dll
  76FD0000 0007C000 C:\Windows\System32\ADVAPI32.dll
  74E30000 00074000 C:\Windows\SYSTEM32\UxTheme.dll
  74D70000 00028000 C:\Windows\SYSTEM32\WINMM.dll
  751F0000 00015000 C:\Windows\SYSTEM32\samcli.dll
  751D0000 00019000 C:\Windows\SYSTEM32\MSACM32.dll
  75070000 00008000 C:\Windows\SYSTEM32\VERSION.dll
  75040000 00025000 C:\Windows\SYSTEM32\USERENV.dll
  751A0000 00026000 C:\Windows\SYSTEM32\dwmapi.dll
  72A80000 001A9000 C:\Windows\SYSTEM32\urlmon.dll
  74DB0000 00076000 C:\Windows\SYSTEM32\WINSPOOL.DRV
  77190000 00087000 C:\Windows\System32\shcore.dll
  732B0000 00019000 C:\Windows\SYSTEM32\MPR.dll
  74C70000 00021000 C:\Windows\SYSTEM32\SspiCli.dll
  75180000 0001D000 C:\Windows\SYSTEM32\winmmbase.dll
  72E70000 00236000 C:\Windows\SYSTEM32\iertutil.dll
  72A50000 0001E000 C:\Windows\SYSTEM32\srvcli.dll
  72A70000 0000B000 C:\Windows\SYSTEM32\netutils.dll
  712D0000 00285000 C:\Windows\SYSTEM32\AcLayers.DLL
  76440000 00438000 C:\Windows\System32\SETUPAPI.dll
  76C10000 0003B000 C:\Windows\System32\cfgmgr32.dll
  76EE0000 00019000 C:\Windows\System32\bcrypt.dll
  66680000 00003000 C:\Windows\SYSTEM32\sfc.dll
  728D0000 00010000 C:\Windows\SYSTEM32\sfc_os.DLL
  75170000 0000E000 C:\Windows\SYSTEM32\SortServer2003Compat.dll
  76C80000 00025000 C:\Windows\System32\IMM32.DLL
  73230000 00008000 C:\Windows\SYSTEM32\WSOCK32.dll
  77220000 00063000 C:\Windows\System32\WS2_32.dll
  10000000 0001F000 D:\cs16v2017_oyunyoneticisi\filesystem_stdio.dll
  04930000 01229A8E D:\cs16v2017_oyunyoneticisi\hw.dll
  72920000 000E9000 C:\Windows\SYSTEM32\DDRAW.dll
  750F0000 00026000 C:\Windows\SYSTEM32\DINPUT.dll
  21100000 0005E000 D:\cs16v2017_oyunyoneticisi\mss32.dll
  732D0000 00455000 C:\Windows\SYSTEM32\WININET.dll
  731F0000 0000F000 C:\Windows\SYSTEM32\kernel.appcore.dll
  724B0000 000C2000 C:\Windows\SYSTEM32\dxgi.dll
  75160000 00007000 C:\Windows\SYSTEM32\DCIMAN32.dll
  00E10000 00058000 D:\cs16v2017_oyunyoneticisi\vgui.dll
  00BE0000 00015000 D:\cs16v2017_oyunyoneticisi\steam_api_c.dll
  72C90000 00055000 D:\cs16v2017_oyunyoneticisi\Steam.dll
  74EB0000 00188000 C:\Windows\SYSTEM32\DbgHelp.dll
  71990000 0002B000 C:\Windows\SYSTEM32\dbgcore.DLL
  30000000 002C3000 D:\cs16v2017_oyunyoneticisi\Steam_orig.dll
  750D0000 0001B000 D:\cs16v2017_oyunyoneticisi\hwpatcher.dll
  723C0000 000ED000 C:\Windows\SYSTEM32\inputhost.dll
  72210000 0009B000 C:\Windows\SYSTEM32\CoreMessaging.dll
  722B0000 000DB000 C:\Windows\SYSTEM32\wintypes.dll
  73100000 000C2000 C:\Windows\SYSTEM32\PROPSYS.dll
  71050000 0027E000 C:\Windows\SYSTEM32\CoreUIComponents.dll
  77130000 0005F000 C:\Windows\System32\bcryptPrimitives.dll
  74500000 00029000 C:\Windows\SYSTEM32\ntmarta.dll
  71EA0000 00066000 d:\cs16v2017_oyunyoneticisi\steamclient.dll
  721D0000 00033000 D:\cs16v2017_oyunyoneticisi\revSrvBrowser.dll
  38000000 00361000 D:\cs16v2017_oyunyoneticisi\steamclient_orig.dll
  76880000 00100000 C:\Windows\System32\CRYPT32.dll
  3F000000 000A9000 D:\cs16v2017_oyunyoneticisi\tier0_s.dll
  3F600000 00074000 D:\cs16v2017_oyunyoneticisi\vstdlib_s.dll
  745F0000 00032000 C:\Windows\SYSTEM32\iphlpapi.dll
  75150000 0000A000 C:\Windows\SYSTEM32\Secur32.dll
  752D0000 00006000 C:\Windows\System32\psapi.dll
  76CB0000 00007000 C:\Windows\System32\NSI.dll
  72E30000 00016000 C:\Windows\SYSTEM32\dhcpcsvc.DLL
  72DD0000 00052000 C:\Windows\system32\mswsock.dll
  750B0000 00011000 C:\Windows\system32\napinsp.dll
  72C70000 00016000 C:\Windows\system32\pnrpnsp.dll
  74DA0000 00010000 C:\Windows\system32\wshbth.dll
  72900000 00016000 C:\Windows\system32\NLAapi.dll
  74560000 00090000 C:\Windows\SYSTEM32\DNSAPI.dll
  72C50000 0000E000 C:\Windows\System32\winrnr.dll
  71E40000 00059000 C:\Windows\System32\fwpuclnt.dll
  72C60000 00008000 C:\Windows\System32\rasadhlp.dll
  71D10000 0002C000 C:\Windows\SYSTEM32\dxcore.dll
  77340000 000D4000 C:\Windows\System32\MSCTF.dll
  71D80000 000BA000 C:\Windows\SYSTEM32\textinputframework.dll
  063F0000 00010000 D:\cs16v2017_oyunyoneticisi\opispn69.dll
  71D40000 0003F000 C:\Windows\SYSTEM32\GLU32.dll
  71A40000 00103000 C:\Windows\SYSTEM32\OPENGL32.dll
  752E0000 0007E000 C:\Windows\System32\clbcatq.dll
  6F930000 00DAF000 C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_d4c1a49b19ac3e59\igxelpicd32.dll
  71BA0000 000D0000 C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_d4c1a49b19ac3e59\igdml32.dll
  70D20000 0032A000 C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_d4c1a49b19ac3e59\igdgmm32.dll
  73200000 00029000 C:\Windows\SYSTEM32\DEVOBJ.dll
  77290000 0004C000 C:\Windows\System32\WINTRUST.dll
  744F0000 0000E000 C:\Windows\SYSTEM32\MSASN1.dll
  699D0000 03DD4000 C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_d4c1a49b19ac3e59\igc32.dll
  719F0000 00044000 C:\Windows\SYSTEM32\powrprof.dll
  723B0000 0000D000 C:\Windows\SYSTEM32\UMPDC.dll
  708D0000 00441000 d:\cs16v2017_oyunyoneticisi\valve\cl_dlls\client.dll
  71950000 00037000 C:\Windows\SYSTEM32\DINPUT8.dll
  09F00000 0005A000 D:\cs16v2017_oyunyoneticisi\vstdlib.dll
  09F60000 00059000 D:\cs16v2017_oyunyoneticisi\tier0.dll
  09990000 00015000 D:\cs16v2017_oyunyoneticisi\steam_api.dll
  0A020000 00040000 D:\cs16v2017_oyunyoneticisi\vgui2.dll
  0F5C0000 000E4000 d:\cs16v2017_oyunyoneticisi\valve\cl_dlls\GameUI.dll
  718D0000 0007F000 C:\Windows\SYSTEM32\dsound.dll
  71860000 0006B000 C:\Windows\System32\MMDevApi.dll
  6F4B0000 00136000 C:\Windows\SYSTEM32\AUDIOSES.DLL
  721C0000 0000F000 C:\Windows\SYSTEM32\resourcepolicyclient.dll
  6F830000 000F3000 C:\Windows\System32\Windows.UI.dll
  70710000 00073000 C:\Windows\System32\WindowManagementAPI.dll
  6F690000 00194000 C:\Windows\SYSTEM32\twinapi.appcore.dll
  721B0000 00008000 C:\Windows\SYSTEM32\avrt.dll
  210D0000 00028000 D:\cs16v2017_oyunyoneticisi\Clonn.dll
  71820000 0003A000 C:\Windows\SYSTEM32\wdmaud.drv
  71D00000 00007000 C:\Windows\SYSTEM32\ksuser.dll
  71CF0000 0000A000 C:\Windows\SYSTEM32\msacm32.drv
  719E0000 00008000 C:\Windows\SYSTEM32\midimap.dll
  21910000 0001E000 D:\cs16v2017_oyunyoneticisi\demoplayer.dll
  21AB0000 00048000 D:\cs16v2017_oyunyoneticisi\core.dll
  719D0000 0000A000 C:\Windows\SYSTEM32\HID.DLL
  6F5F0000 00094000 C:\Windows\SYSTEM32\TextShaping.dll
  23F80000 0008D000 d:\cs16v2017_oyunyoneticisi\platform\Servers\serverbrowser.dll
  70850000 0007C000 C:\Windows\System32\schannel.dll
  71800000 00011000 C:\Windows\SYSTEM32\mskeyprotect.dll
  70820000 00028000 C:\Windows\SYSTEM32\NTASN1.dll
  707F0000 00022000 C:\Windows\SYSTEM32\ncrypt.dll
  706F0000 0001F000 C:\Windows\system32\ncryptsslp.dll
  241C0000 0063D000 C:\Windows\System32\ieframe.dll
  75120000 00014000 C:\Windows\System32\NETAPI32.dll
  74CA0000 000CA000 C:\Windows\System32\WINHTTP.dll
  75090000 00013000 C:\Windows\System32\WKSCLI.DLL
  726C0000 00210000 C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_a8625c1886757984\comctl32.dll
  6F470000 00031000 C:\Windows\system32\dataexchange.dll
  6EB40000 001E0000 C:\Windows\system32\d3d11.dll
  6ED20000 00164000 C:\Windows\system32\dcomp.dll
  74640000 0060C000 C:\Windows\SYSTEM32\windows.storage.dll
  74530000 00025000 C:\Windows\SYSTEM32\Wldp.dll
  731D0000 0001C000 C:\Windows\SYSTEM32\profapi.dll
  6F450000 00012000 C:\Windows\SYSTEM32\ondemandconnroutehelper.dll
  706E0000 00008000 C:\Windows\SYSTEM32\WINNSI.DLL
  00D10000 00012000 D:\cs16v2017_oyunyoneticisi\Clonn.asi
  26F00000 0002A000 D:\cs16v2017_oyunyoneticisi\Mp3dec.asi
  26600000 00027000 D:\cs16v2017_oyunyoneticisi\Mssv12.asi
  26400000 0002C000 D:\cs16v2017_oyunyoneticisi\Mssv29.asi
  21070000 00034000 C:\Program Files\Cheat Engine 7.5\speedhack-i386.dll
  01140000 00023000 D:\cs16v2017_oyunyoneticisi\voice_speex.dll
  72E50000 00014000 C:\Windows\SYSTEM32\dhcpcsvc6.DLL

Validating heap
CRT heap: validated successfully
Process heap: validated successfully

**Comment by Safety1st** [comment]
@telekinetic1, you completely forgot about symptoms…

**Comment by telekinetic1** [comment]
What did i forget exactly? :d

**Comment by Safety1st** [comment]
May be dictionary…

**Comment by telekinetic1** [comment]
Okay updated.

**Comment by tmp64** [comment]
@telekinetic1 The crash is in `revSrvBrowser.dll`, a part of a No-Steam patch. You should buy the game on Steam. It's 90% off every sale

@Safety1st Please, be more polite on the issue tracker

**Comment by Safety1st** [comment]
@telekinetic1, if for some reason you are not able to buy the game I could gift it to your Steam account 👌
