### ISSUE TITLE
Random spawn point selection with items accounting

### ISSUE THREAD

**Issue by Safety1st** [tmp64/BugfixedHL-Rebased#221]
Feature request:
• optional the same spawn point randomization for those who uses pre-25th anniversary build at least for transition period (while we wait for updated VALVe's API, ReHLDS & AMXX support);
• optional modification of behavior for choosing next spawn like Lev [did](https://github.com/LevShisterov/BugfixedHL/commit/c545b8af131406b76fa97f9cc8384eba182ccca1) 1.5 years ago.

**Comment by tmp64** [comment]
Use `mp_spawntype`:
0. HL25
1. Pre-HL25
2. Random with item accounting
