### ISSUE TITLE
Crash when loading a server in AG

### ISSUE THREAD

**Issue by rtxa** [tmp64/BugfixedHL-Rebased#222]
Just trying to run BugfixedHL in AG with latest client, it used to work previous to 25th anniversary but now it just crashes when loading a server with the next log. By the way, trying to run older versions (after 25th anniversary) just gives me an already reported error by headshoter #220 with ApplyMultiDamage.

PD: Ismajjzx just reported me with the same issue and he find out the issue only happens when playing in 16:9, 4:3 works just fine, which I tested and it works.

<details> 
  <summary>My log</summary>
   BugfixedHL Crash Log
  Exception EXCEPTION_ACCESS_VIOLATION (0xC0000005) at address 0x655DE237 (client.dll).

Please post contents of this log file and file crash-2024-05-17-00-35-56.dmp on
https://github.com/tmp64/BugfixedHL-Rebased/issues

-------------------------------------------------------------------------
Technical information

Version: 1.10.4-dev+master.f52e560
Engine version: 1.1.2.2/Stdio,48,9920
Local time: 2024-05-17 00:35:56
OS version: 10.0.19041.4355

Stack trace (may be incorrect since no engine PDBs are available):
  655DE237 (client): (filename not available): HUD_VoiceStatus
  655CBB25 (client): (filename not available): HUD_VoiceStatus
  730BA2D5 (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  730B4F63 (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  730E46D7 (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  730E291E (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  731311F9 (hw): (filename not available): F
  7313091B (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  731302F8 (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount
  0082159C (hl): (filename not available): (function-name not available)
  00822E48 (hl): (filename not available): CreateInterface
  7644FCC9 (KERNEL32): (filename not available): BaseThreadInitThunk
  77DD7CBE (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath
  77DD7C8E (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath

Modules:
  Base     Size     Path (Exception Offset)
  00820000 0000B000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\hl.exe
  77D70000 001A4000 C:\Windows\SYSTEM32\ntdll.dll
  76430000 000F0000 C:\Windows\System32\KERNEL32.DLL
  77B20000 0023A000 C:\Windows\System32\KERNELBASE.dll
  6CBF0000 0009F000 C:\Windows\SYSTEM32\apphelp.dll
  75FF0000 00063000 C:\Windows\System32\WS2_32.dll
  76330000 000BC000 C:\Windows\System32\RPCRT4.dll
  75E20000 0019D000 C:\Windows\System32\USER32.dll
  77AA0000 00018000 C:\Windows\System32\win32u.dll
  75FC0000 00023000 C:\Windows\System32\GDI32.dll
  75BF0000 000E6000 C:\Windows\System32\gdi32full.dll
  75CE0000 0007B000 C:\Windows\System32\msvcp_win.dll
  761A0000 00120000 C:\Windows\System32\ucrtbase.dll
  77080000 0007D000 C:\Windows\System32\ADVAPI32.dll
  75D60000 000BF000 C:\Windows\System32\msvcrt.dll
  76D80000 00078000 C:\Windows\System32\sechost.dll
  762C0000 00019000 C:\Windows\System32\bcrypt.dll
  74530000 00015000 C:\Windows\SYSTEM32\VCRUNTIME140.dll
  76400000 00026000 C:\Windows\System32\IMM32.DLL
  743D0000 00153000 C:\Program Files (x86)\Steam\gameoverlayrenderer.dll
  77220000 000E3000 C:\Windows\System32\ole32.dll
  76E00000 00280000 C:\Windows\System32\combase.dll
  77180000 00096000 C:\Windows\System32\OLEAUT32.dll
  77410000 0003B000 C:\Windows\System32\CFGMGR32.dll
  763F0000 00006000 C:\Windows\System32\PSAPI.DLL
  75810000 00028000 C:\Windows\SYSTEM32\WINMM.dll
  743C0000 00010000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\filesystem_stdio.dll
  72F10000 014AA000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\hw.dll
  759D0000 00008000 C:\Windows\SYSTEM32\WSOCK32.dll
  72E80000 00082000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mss32.dll
  72E30000 00042000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\steam_api.dll
  765A0000 005D7000 C:\Windows\System32\SHELL32.dll
  72C30000 001F7000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\SDL2.dll
  6DB60000 00086000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\vgui.dll
  750F0000 00103000 C:\Windows\SYSTEM32\OPENGL32.dll
  77510000 00438000 C:\Windows\System32\SETUPAPI.dll
  6F630000 0006D000 C:\Windows\SYSTEM32\MSVCP140.dll
  74F10000 0003F000 C:\Windows\SYSTEM32\GLU32.dll
  75660000 00008000 C:\Windows\SYSTEM32\VERSION.dll
  76110000 00087000 C:\Windows\System32\SHCORE.DLL
  6D7E0000 00093000 C:\Windows\SYSTEM32\mscms.dll
  6DA80000 00025000 C:\Windows\SYSTEM32\USERENV.dll
  72C20000 0000C000 C:\Windows\SYSTEM32\ColorAdapterClient.dll
  6DB20000 0003E000 C:\Windows\SYSTEM32\icm32.dll
  6DC60000 01311000 C:\Program Files (x86)\Steam\steamclient.dll
  76060000 00045000 C:\Windows\System32\SHLWAPI.dll
  77310000 00100000 C:\Windows\System32\CRYPT32.dll
  76520000 00019000 C:\Windows\System32\imagehlp.dll
  757D0000 00032000 C:\Windows\SYSTEM32\IPHLPAPI.DLL
  756A0000 00086000 C:\Program Files (x86)\Steam\vstdlib_s.dll
  75730000 00098000 C:\Program Files (x86)\Steam\tier0_s.dll
  75970000 00052000 C:\Windows\SYSTEM32\MSWSOCK.dll
  6F9D0000 0000A000 C:\Windows\SYSTEM32\Secur32.dll
  6F9A0000 00021000 C:\Windows\SYSTEM32\SSPICLI.DLL
  72B90000 0000A000 C:\Windows\SYSTEM32\CRYPTBASE.DLL
  77A30000 0005F000 C:\Windows\System32\bcryptPrimitives.dll
  758C0000 000A7000 C:\Program Files (x86)\Steam\crashhandler.dll
  75200000 00455000 C:\Windows\SYSTEM32\WININET.dll
  75840000 00074000 C:\Windows\system32\uxtheme.dll
  74F00000 0000F000 C:\Windows\SYSTEM32\kernel.appcore.dll
  77100000 0007E000 C:\Windows\System32\clbcatq.dll
  6DBF0000 0006B000 C:\Windows\System32\MMDevApi.dll
  74B60000 00029000 C:\Windows\System32\DEVOBJ.dll
  6DAD0000 00008000 C:\Windows\SYSTEM32\avrt.dll
  75690000 0000A000 C:\Windows\SYSTEM32\hid.dll
  762E0000 0004C000 C:\Windows\System32\WINTRUST.dll
  076B0000 0000E000 C:\Windows\SYSTEM32\MSASN1.dll
  74B90000 00037000 C:\Windows\System32\dinput8.dll
  71000000 000ED000 C:\Windows\SYSTEM32\inputhost.dll
  70F60000 0009B000 C:\Windows\SYSTEM32\CoreMessaging.dll
  70DB0000 000DD000 C:\Windows\SYSTEM32\wintypes.dll
  70B30000 0027F000 C:\Windows\SYSTEM32\CoreUIComponents.dll
  70E90000 000C2000 C:\Windows\SYSTEM32\PROPSYS.dll
  74B30000 00029000 C:\Windows\SYSTEM32\ntmarta.dll
  6D730000 000A2000 C:\Windows\System32\Windows.Gaming.Input.dll
  6FC80000 00191000 C:\Windows\System32\twinapi.appcore.dll
  75670000 0000D000 C:\Windows\SYSTEM32\XInput1_4.dll
  6D6D0000 00056000 C:\Windows\System32\SensorsApi.dll
  72BF0000 0002E000 C:\Windows\System32\SensorsNativeApi.V2.dll
  6D6A0000 00022000 C:\Windows\System32\SensorsUtilsV2.dll
  6F910000 00044000 C:\Windows\SYSTEM32\powrprof.dll
  6F700000 0000D000 C:\Windows\SYSTEM32\UMPDC.dll
  6D670000 00027000 C:\Windows\System32\PortableDeviceTypes.dll
  6D640000 00030000 C:\Windows\System32\deviceaccess.dll
  08C10000 000D3000 C:\Windows\System32\MSCTF.dll
  6D0B0000 000C2000 C:\Windows\System32\AppXDeploymentClient.dll
  6A630000 0231C000 C:\Windows\System32\DriverStore\FileRepository\nvhm.inf_amd64_4a725c9a083cb6dc\nvoglv32.dll
  6F620000 0000F000 C:\Windows\SYSTEM32\WTSAPI32.dll
  6FA10000 00026000 C:\Windows\SYSTEM32\cryptnet.dll
  6F810000 00100000 C:\Windows\SYSTEM32\drvstore.dll
  70280000 00025000 C:\Windows\SYSTEM32\wldp.dll
  6F7E0000 0002C000 C:\Windows\SYSTEM32\dxcore.dll
  702B0000 00613000 C:\Windows\SYSTEM32\windows.storage.dll
  708D0000 00026000 C:\Windows\SYSTEM32\dwmapi.dll
  6CB30000 00047000 C:\Windows\SYSTEM32\WINSTA.dll
  749A0000 000B9000 C:\Windows\SYSTEM32\textinputframework.dll
  6FE20000 000C2000 C:\Windows\SYSTEM32\dxgi.dll
  70060000 001E0000 C:\Windows\SYSTEM32\d3d11.dll
  6D010000 0009D000 C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igd10iumd32.dll
  69F50000 006D5000 C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igd10um32gen11.DLL
  6CFE0000 00022000 C:\Windows\SYSTEM32\ncrypt.dll
  6CFB0000 00028000 C:\Windows\SYSTEM32\NTASN1.dll
  69C20000 00322000 C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igdgmm32.dll
  66CF0000 02F26000 C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igc32.dll
  666A0000 0064E000 C:\Windows\SYSTEM32\nvapi.dll
  6D8C0000 00136000 C:\Windows\SYSTEM32\AUDIOSES.DLL
  6CEB0000 000F3000 C:\Windows\System32\Windows.UI.dll
  6CE30000 00073000 C:\Windows\System32\WindowManagementAPI.dll
=>65580000 0045E000 c:\program files (x86)\steam\steamapps\common\half-life\ag_addon\cl_dlls\client.dll  <==  0005E237
  6CD40000 00020000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\vstdlib.dll
  6CD20000 0001E000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\tier0.dll
  653F0000 00188000 C:\Windows\SYSTEM32\dbghelp.dll
  6CCF0000 0002B000 C:\Windows\SYSTEM32\dbgcore.DLL
  6CCA0000 0002E000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\vgui2.dll
  65310000 000DC000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\chromehtml.dll
  62820000 0138F000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\libcef.dll
  77450000 000AF000 C:\Windows\System32\COMDLG32.dll
  652F0000 00017000 C:\Windows\SYSTEM32\USP10.dll
  6F710000 000CA000 C:\Windows\SYSTEM32\WINHTTP.dll
  6CD60000 0008D000 C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.4355_none_c0dc01d438beab35\COMCTL32.dll
  65270000 0007D000 C:\Windows\SYSTEM32\WINSPOOL.DRV
  64310000 001A9000 C:\Windows\SYSTEM32\urlmon.dll
  74AE0000 00006000 C:\Windows\SYSTEM32\MSIMG32.dll
  640D0000 00237000 C:\Windows\SYSTEM32\iertutil.dll
  640C0000 0000B000 C:\Windows\SYSTEM32\netutils.dll
  6CA60000 0001D000 C:\Windows\SYSTEM32\srvcli.dll
  65190000 000DF000 c:\program files (x86)\steam\steamapps\common\half-life\valve\cl_dlls\GameUI.dll
  23F00000 0097F000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\icudt.dll
  64FD0000 001B2000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\avcodec-53.dll
  64FA0000 00027000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\avutil-51.dll
  64F60000 00033000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\avformat-53.dll
  77500000 00007000 C:\Windows\System32\NSI.dll
  6F4E0000 00016000 C:\Windows\system32\NLAapi.dll
  6F590000 0007F000 C:\Windows\SYSTEM32\dsound.dll
  6F570000 0001D000 C:\Windows\SYSTEM32\winmmbase.dll
  6F560000 0000F000 C:\Windows\SYSTEM32\resourcepolicyclient.dll
  64F40000 00016000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mssmp3.asi
  64F10000 0002A000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\mssvoice.asi
  6DAE0000 0003A000 C:\Windows\SYSTEM32\wdmaud.drv
  6F550000 00007000 C:\Windows\SYSTEM32\ksuser.dll
  6D8B0000 0000A000 C:\Windows\SYSTEM32\msacm32.drv
  6D890000 00019000 C:\Windows\SYSTEM32\MSACM32.dll
  6D880000 00008000 C:\Windows\SYSTEM32\midimap.dll
  6CCE0000 0000C000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\demoplayer.dll
  64ED0000 00035000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\core.dll
  64E50000 00079000 c:\program files (x86)\steam\steamapps\common\half-life\platform\servers\serverbrowser.dll
  6F440000 00091000 C:\Windows\SYSTEM32\DNSAPI.dll
  6F610000 00008000 C:\Windows\System32\rasadhlp.dll
  6F6A0000 00058000 C:\Windows\System32\fwpuclnt.dll
  64DD0000 0007E000 C:\Windows\System32\schannel.dll
  6CC90000 00010000 C:\Windows\SYSTEM32\mskeyprotect.dll
  64DB0000 0001F000 C:\Windows\system32\ncryptsslp.dll
  64D00000 000AC000 c:\program files (x86)\steam\steamapps\common\half-life\ag\addons\metamod\dlls\metamod.dll
  047A0000 00127000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\ag\dlls\ag.dll
  64750000 00213000 c:\program files (x86)\steam\steamapps\common\half-life\ag\addons\amxmodx\dlls\amxmodx_mm.dll
  64CD0000 0002A000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\ag\addons\amxmodx\modules\debugger_amxx.dll
  63DF0000 002C7000 c:\program files (x86)\steam\steamapps\common\half-life\ag\addons\dproto\dproto.dll
  29EE0000 0014D000 c:\program files (x86)\steam\steamapps\common\half-life\ag\addons\rcbot\dlls\rcbot_mm.dll
  64C70000 0005B000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\ag\addons\amxmodx\modules\fakemeta_amxx.dll
  64C30000 00033000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\ag\addons\amxmodx\modules\engine_amxx.dll
  64C00000 00028000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\ag\addons\amxmodx\modules\fun_amxx.dll
  646E0000 0006B000 C:\Program Files (x86)\Steam\steamapps\common\Half-Life\ag\addons\amxmodx\modules\hamsandwich_amxx.dll
  72BD0000 00013000 C:\Windows\System32\CRYPTSP.dll
  72BA0000 0002F000 C:\Windows\system32\rsaenh.dll
  6F980000 00014000 C:\Windows\SYSTEM32\dhcpcsvc6.DLL
  6F960000 00016000 C:\Windows\SYSTEM32\dhcpcsvc.DLL
  64BF0000 0000D000 C:\Windows\system32\wbem\wbemprox.dll
  64670000 00070000 C:\Windows\SYSTEM32\wbemcomn.dll
  64BE0000 00010000 C:\Windows\system32\wbem\wbemsvc.dll
  645A0000 000CA000 C:\Windows\system32\wbem\fastprox.dll
  6DAB0000 00018000 C:\Windows\SYSTEM32\amsi.dll
  6F9F0000 0001B000 C:\Windows\SYSTEM32\profapi.dll
  64520000 00071000 C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.24040.4-0\X86\MpOav.dll
  6FA40000 0001E000 C:\Windows\SYSTEM32\gpapi.dll
  6F9E0000 00008000 C:\Windows\SYSTEM32\WINNSI.DLL
  74A60000 00073000 C:\Windows\SYSTEM32\webio.dll
  6F530000 00011000 C:\Windows\system32\napinsp.dll
  6F510000 00016000 C:\Windows\system32\pnrpnsp.dll
  6F500000 00010000 C:\Windows\system32\wshbth.dll
  6FA60000 0000E000 C:\Windows\System32\winrnr.dll

Validating heap
CRT heap: validated successfully
Process heap: validated successfully
</details>

<details>
<summary>Isma's log</summary>
Technical information
Version: 1.10.4+master.1a1f601
Engine version: 1.1.2.2/Stdio,48,9920
Local time: 2024-02-07 02:24:53
OS version: 10.0.19041.1889
Stack trace (may be incorrect since no engine PDBs are available):  ERROR: SymGetModuleInfo64, GetLastError: 1114 (Address: 181B6200)  181B6200 ((module-name not available)): (filename not available): (function-name not available)  62931154 (SimpleBaseDLL_[unknowncheats.me): (filename not available): (function-name not available)  5EABC7B3 (hw): (filename not available): vgui::Frame::operator=  58FE83A8 (GameUI): (filename not available): CreateInterface  58FE876E (GameUI): (filename not available): CreateInterface  5902B6D9 (GameUI): (filename not available): CreateInterface  62C370DB (vgui2): (filename not available): (function-name not available)  5EAD5EF4 (hw): (filename not available): vgui::Frame::operator=  62C370DB (vgui2): (filename not available): (function-name not available)  5EAD5EF4 (hw): (filename not available): vgui::Frame::operator=  62C370DB (vgui2): (filename not available): (function-name not available)  5EA8E6E9 (hw): (filename not available): vgui::Frame::operator=  5EA8C4EA (hw): (filename not available): vgui::Frame::operator=  5EA8BAEE (hw): (filename not available): vgui::Frame::operator=  5EAAD8AF (hw): (filename not available): vgui::Frame::operator=  5EA34792 (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount  5EA3291E (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount  5EA811F9 (hw): (filename not available): F  5EA8091B (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount  5EA802F8 (hw): (filename not available): vgui::Dar<vgui::InputSignal *>::getCount  0096159C (hl): (filename not available): (function-name not available)  00962E48 (hl): (filename not available): CreateInterface  76DEFA29 (KERNEL32): (filename not available): BaseThreadInitThunk  770A7BBE (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath  770A7B8E (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath
Modules:  Base     Size     Path (Exception Offset)  00960000 0000B000 F:\SteamLibrary\steamapps\common\Half-Life\hl.exe  77040000 001A4000 C:\Windows\SYSTEM32\ntdll.dll  76DD0000 000F0000 C:\Windows\System32\KERNEL32.DLL  74F00000 0021C000 C:\Windows\System32\KERNELBASE.dll  60C10000 000A0000 C:\Windows\SYSTEM32\apphelp.dll  76A40000 00063000 C:\Windows\System32\WS2_32.dll  75960000 000BE000 C:\Windows\System32\RPCRT4.dll  75A20000 0019D000 C:\Windows\System32\USER32.dll  75470000 00018000 C:\Windows\System32\win32u.dll  75120000 00023000 C:\Windows\System32\GDI32.dll  76F50000 000E0000 C:\Windows\System32\gdi32full.dll  76D50000 0007B000 C:\Windows\System32\msvcp_win.dll  75E50000 00120000 C:\Windows\System32\ucrtbase.dll  75290000 0007B000 C:\Windows\System32\ADVAPI32.dll  751A0000 000BF000 C:\Windows\System32\msvcrt.dll  75C00000 00076000 C:\Windows\System32\sechost.dll  631D0000 00015000 C:\Windows\SYSTEM32\VCRUNTIME140.dll  75260000 00025000 C:\Windows\System32\IMM32.DLL  60650000 00150000 C:\Program Files (x86)\Steam\gameoverlayrenderer.dll  75310000 000E3000 C:\Windows\System32\ole32.dll  76650000 00280000 C:\Windows\System32\combase.dll  765B0000 00096000 C:\Windows\System32\OLEAUT32.dll  75BC0000 0003B000 C:\Windows\System32\CFGMGR32.dll  75400000 00006000 C:\Windows\System32\PSAPI.DLL  745F0000 00028000 C:\Windows\SYSTEM32\WINMM.dll  62EF0000 00010000 F:\SteamLibrary\steamapps\common\Half-Life\filesystem_stdio.dll  5E860000 014AA000 F:\SteamLibrary\steamapps\common\Half-Life\hw.dll  5E660000 001F7000 F:\SteamLibrary\steamapps\common\Half-Life\SDL2.dll  73A50000 00008000 C:\Windows\SYSTEM32\WSOCK32.dll  62E10000 00042000 F:\SteamLibrary\steamapps\common\Half-Life\steam_api.dll  62E60000 00082000 F:\SteamLibrary\steamapps\common\Half-Life\mss32.dll  75490000 00439000 C:\Windows\System32\SETUPAPI.dll
75FF0000 005B5000 C:\Windows\System32\SHELL32.dll  67F40000 00104000 C:\Windows\SYSTEM32\OPENGL32.dll  76AB0000 00019000 C:\Windows\System32\bcrypt.dll  62940000 00086000 F:\SteamLibrary\steamapps\common\Half-Life\vgui.dll  671E0000 0003F000 C:\Windows\SYSTEM32\GLU32.dll  5E5F0000 0006D000 C:\Windows\SYSTEM32\MSVCP140.dll  73A20000 00008000 C:\Windows\SYSTEM32\VERSION.dll  76AD0000 00087000 C:\Windows\System32\SHCORE.DLL  6E310000 00093000 C:\Windows\SYSTEM32\mscms.dll  6DB20000 00025000 C:\Windows\SYSTEM32\USERENV.dll  6E300000 0000C000 C:\Windows\SYSTEM32\ColorAdapterClient.dll  63070000 0003E000 C:\Windows\SYSTEM32\icm32.dll  65740000 012F7000 C:\Program Files (x86)\Steam\steamclient.dll  75150000 00045000 C:\Windows\System32\SHLWAPI.dll  76B60000 000FA000 C:\Windows\System32\CRYPT32.dll  75F70000 00019000 C:\Windows\System32\imagehlp.dll  6D6B0000 00032000 C:\Windows\SYSTEM32\IPHLPAPI.DLL  68520000 0009A000 C:\Program Files (x86)\Steam\tier0_s.dll  68050000 00088000 C:\Program Files (x86)\Steam\vstdlib_s.dll  73B10000 00052000 C:\Windows\SYSTEM32\MSWSOCK.dll  6D6A0000 0000A000 C:\Windows\SYSTEM32\Secur32.dll  73BD0000 00021000 C:\Windows\SYSTEM32\SSPICLI.DLL  73560000 0000A000 C:\Windows\SYSTEM32\CRYPTBASE.DLL  75C80000 0005F000 C:\Windows\System32\bcryptPrimitives.dll  6EC90000 000A7000 C:\Program Files (x86)\Steam\crashhandler.dll  735C0000 00457000 C:\Windows\SYSTEM32\WININET.dll  74620000 00074000 C:\Windows\system32\uxtheme.dll  746A0000 0000F000 C:\Windows\SYSTEM32\kernel.appcore.dll  758D0000 00083000 C:\Windows\System32\clbcatq.dll  6E170000 0006B000 C:\Windows\System32\MMDevApi.dll  72C30000 00024000 C:\Windows\System32\DEVOBJ.dll  655C0000 00008000 C:\Windows\SYSTEM32\avrt.dll  671D0000 0000A000 C:\Windows\SYSTEM32\hid.dll  75420000 0004E000 C:\Windows\System32\WINTRUST.dll  72D90000 0000E000 C:\Windows\SYSTEM32\MSASN1.dll  67190000 00037000 C:\Windows\System32\dinput8.dll
</detail>

**Comment by tmp64** [comment]
Can you attach the `.dmp` files?

**Comment by rtxa** [comment]
[crash-2024-05-18-01-01-01.dmp](https://github.com/tmp64/BugfixedHL-Rebased/files/15365252/crash-2024-05-18-01-01-01.dmp)
[crash-2024-05-18-01-01-01.txt](https://github.com/tmp64/BugfixedHL-Rebased/files/15365255/crash-2024-05-18-01-01-01.txt)
Yeah, here are the latest logs.

**Comment by tmp64** [comment]
AG doesn't have the high-resolution sprites in `sprites/hud.txt`. As a workaround, you can set HUD scale to 100% in the advanced options
