### ISSUE TITLE
Game crashes when using "viewdemo"

### ISSUE THREAD

**Issue by viruspetya24** [tmp64/BugfixedHL-Rebased#224]
The game crashes when using "viewdemo". But this does not happen when using "playdemo".
I will attach logs and dump file:
[crash-2024-05-27-16-17-29.txt](https://github.com/tmp64/BugfixedHL-Rebased/files/15454894/crash-2024-05-27-16-17-29.txt)
[crash-2024-05-27-16-17-29.dmp](https://github.com/tmp64/BugfixedHL-Rebased/files/15454899/crash-2024-05-27-16-17-29.dmp)

**Comment by Safety1st** [comment]
It's ReHLDS issue 😞

**Comment by tmp64** [comment]
Crash is in the engine. I can't debug it

**Comment by Safety1st** [comment]
You are very skilled developer, we don't believe you 😉
