### ISSUE TITLE
"Center player name hint" option in the HUD menu doesn't seem to work

### ISSUE THREAD

**Issue by BillyJoeTodd** [tmp64/BugfixedHL-Rebased#230]
Tried hud_centerid but it doesn't work either.

**Comment by Safety1st** [comment]
It would be nice to also know how hint currently looks like. If there is no hint at all check whether `hud_playerid` CVar value = 1.

**Comment by tmp64** [comment]
It works fine for me. Type this in the console and post the result here
```
hud_playerid
hud_centerid
```

**Comment by BillyJoeTodd** [comment]
Sorry I've been gone for so long, I got busy for a bit. Playerid is 1 and centerid is 0.

**Comment by tmp64** [comment]
If `hud_centerid` is `0`, it means that it's disabled. Set it to `1` or enable the checkbox in the Advanced Options.

**Comment by BillyJoeTodd** [comment]
I understand that hud_centerid is set to 0, but the thing is that the id stays in the center no matter what it's set to. The same goes for Advanced settings.

**Comment by tmp64** [comment]
Both `hud_centerid 0` and `hud_centerid 1` work as intended on my side

**Comment by BillyJoeTodd** [comment]
Strange, I reinstalled the game along with the client and the problem persists. Maybe there's something I'm missing?

**Comment by tmp64** [comment]
This is what it's supposed to look like:

`hud_centerid 1`  
![image](https://github.com/tmp64/BugfixedHL-Rebased/assets/20199236/d7fa5b91-8f24-40c9-9546-2f54b03172e7)

`hud_centerid 0`  
![image](https://github.com/tmp64/BugfixedHL-Rebased/assets/20199236/3b9a2bf8-a9df-428d-93d3-2cf3dfb748f0)

**Comment by BillyJoeTodd** [comment]
Weird, it doesn't do that at all on my end. Here's a video of what it looks like for me.

https://github.com/tmp64/BugfixedHL-Rebased/assets/115393369/1a92f5e5-5c5a-406f-9377-a390c72b0cf1

**Comment by tmp64** [comment]
I think there's a server plugin that adds this text. Try on a different server.

**Comment by BillyJoeTodd** [comment]
Oh, I completely forgot about the possibility of that. Thanks so much for your help and I'm sorry I wasted your time at any point.
