### ISSUE TITLE
New application (:p)

### ISSUE THREAD

**Issue by fatchiiii** [tmp64/BugfixedHL-Rebased#251]
Hello, would it be possible to add a hardcore bot system to the BHLL system with the possibility that bots can bunny take control of the map like a real player.

For this there is a method to let the bots play on a server day and night that they learn by themselves as they did on rocket league (seer v4).

thank you in advance for all your work

**Comment by tmp64** [comment]
Creating bots is out of the scope of this project

**Comment by fatchiiii** [comment]
could it enter another project ?

**Comment by tmp64** [comment]
It could be. Just not mine :)
