### ISSUE TITLE
new meta 

### ISSUE THREAD

**Issue by fatchiiii** [tmp64/BugfixedHL-Rebased#253]
A new update has appeared and BHLL is no longer recognized in half life
Do you have a solution?
Thank you team

**Comment by tmp64** [comment]
1. Reinstall
2. Enable "Allow custom addon content"  
   ![image](https://github.com/user-attachments/assets/ce69afee-be84-4cf3-9dc8-67f275773ede)

**Comment by fatchiiii** [comment]
Thank you very much
