### ISSUE TITLE
EL CLIENT ME DA UN ERROR AL ENTRAR AL SV DE PERUHL EN ADRENALINE GAMER. 

### ISSUE THREAD

**Issue by fanaticAGHL** [tmp64/BugfixedHL-Rebased#255]
El ip del server es: 87.121.99.43:27727

esto es lo que me dice el error, adjunto bloc de notas
[crash-2024-11-07-01-54-59.txt](https://github.com/user-attachments/files/17656217/crash-2024-11-07-01-54-59.txt)

**Comment by tmp64** [comment]
Crash is in the engine
