### ISSUE TITLE
HL WeaponMod

### ISSUE THREAD

**Issue by xRiseless** [tmp64/BugfixedHL-Rebased#28]
Got these errors after installation:

```
[WEAPONMOD]: Start.
[WEAPONMOD]:  Version 0.9.241 Windows
[WEAPONMOD]:   Found hl.dll at 311A0000
[WEAPONMOD]:    Error: "ClearMultiDamage" not found
[WEAPONMOD]:    Error: "ApplyMultiDamage" not found
[WEAPONMOD]: Errors occurred. Please visit http://aghl.ru/forum/ for support.
L 03/19/2021 - 18:24:50: -------- Mapchange to crossfire --------
L 03/19/2021 - 18:24:50: [FAKEMETA] get/set_gamerules_* natives have been disabled because g_pGameRules address could not be found. 
L 03/19/2021 - 18:24:50: [AMXX] Plugin "wpnmod_spawn_editor.amxx" failed to load: Module/Library "weaponmod" required for plugin.  Check modules.ini.
```

MetaMod Version 1.21p38
AMX Mod X Version 1.9.0.5271
HL Weapon Mod Version 0.9.241
Parabot Reloaded Version ???

Don't have any custom modules\plugins except - HLWeaponMod module and wpnmod_spawn_editor plugin.

Also use this bugfixedHL (client + server) - https://github.com/tmp64/BugfixedHL-Rebased/releases/tag/v1.6.0-beta1

**Comment by tmp64** [comment]
Is this on Windows or Linux? I exported these functions, please check if [this version](https://github.com/tmp64/BugfixedHL-Rebased/actions/runs/668458098) fixed the problem.

**Comment by xRiseless** [comment]
> Is this on Windows or Linux? I exported these functions, please check if [this version](https://github.com/tmp64/BugfixedHL-Rebased/actions/runs/668458098) fixed the problem.

Windows, launched through local server (using client, not hlds)

**Comment by xRiseless** [comment]
> Is this on Windows or Linux? I exported these functions, please check if [this version](https://github.com/tmp64/BugfixedHL-Rebased/actions/runs/668458098) fixed the problem.

Still exist

```
[WEAPONMOD]: Start.
[WEAPONMOD]:  Version 0.9.241 Windows
[WEAPONMOD]:   Found hl.dll at 7AE80000
[WEAPONMOD]:    Error: "ClearMultiDamage" not found
[WEAPONMOD]:    Error: "ApplyMultiDamage" not found
[WEAPONMOD]: Errors occurred. Please visit http://aghl.ru/forum/ for support.
Usage:
Setmaster unavailable, start a server first.
L 03/19/2021 - 18:54:56: -------- Mapchange to crossfire --------
L 03/19/2021 - 18:54:56: [AMXX] Plugin "wpnmod_spawn_editor.amxx" failed to load: Module/Library "weaponmod" required for plugin.  Check modules.ini.
```

**Comment by xRiseless** [comment]
Also there is something with armor numbers position on client side

![image](https://user-images.githubusercontent.com/47669746/111808944-87abbe80-88e5-11eb-87cc-fc63327bf4a0.png)
![image](https://user-images.githubusercontent.com/47669746/111808957-8b3f4580-88e5-11eb-9d5e-461c0caa338f.png)

**Comment by tmp64** [comment]
WeaponMod on Windows uses binary analysis to find necessary functions. It doesn't work reliably any more since BHL uses a newer compiler.

I've modified WeaponMod to use exported symbols first. You can get the fixed version [here](https://github.com/tmp64/weaponmod/actions).

**Comment by xRiseless** [comment]
> WeaponMod on Windows uses binary analysis to find necessary functions. It doesn't work reliably any more since BHL uses a newer compiler.
> 
> I've modified WeaponMod to use exported symbols first. You can get the fixed version [here](https://github.com/tmp64/weaponmod/actions).

```
[WEAPONMOD]: Start.
[WEAPONMOD]:  Version 0.9.0 Windows
[WEAPONMOD]:   Found hw.dll at 03850000
[WEAPONMOD]:   Found [WEAPONMOD]:   Found hl.dll at 2F340000
[WEAPONMOD]:    Error: "ItemInfoArray (gamedll)" not found [1]
[WEAPONMOD]:    Error: "AmmoInfoArray (gamedll)" not found [1]
[WEAPONMOD]:    Error: failed to hook "CBasePlayerAmmo::Spawn (gamedll)"
[WEAPONMOD]:    Error: failed to hook "CItem::Spawn (gamedll)"
[WEAPONMOD]: Errors occurred. Please visit http://aghl.ru/forum/ for support.
```

![image](https://user-images.githubusercontent.com/47669746/111899102-71177b80-8a3b-11eb-97ca-ff98c324a288.png)

**Comment by tmp64** [comment]
You also need to update BugfixedHL server library to latest development version: https://github.com/tmp64/BugfixedHL-Rebased/actions

**Comment by xRiseless** [comment]
> You also need to update BugfixedHL server library to latest development version: https://github.com/tmp64/BugfixedHL-Rebased/actions

It works! Thanks!

**Comment by andreiseverin** [comment]
@tmp64 Can you please repost the fixed version of weapon mod? The download expired.

**Comment by tmp64** [comment]
I set the CI to run every month. Please, report any further issues related to the patched WeaponMod in [its issue tracker](https://github.com/tmp64/weaponmod/issues).
