### ISSUE TITLE
/reset command for servers

### ISSUE THREAD

**Issue by Mehmet-I** [tmp64/BugfixedHL-Rebased#29]
Hello Bro,

/reset command can be very useful. Because /reset plugins we tried in bugfixedhl do not work.
It can be activated with a cvar.
eg mp_resetscore 1

Thanks for your work.

**Comment by tmp64** [comment]
Hi! I'm not going to add any score reset functionality into the server. However, I can add [Server API](https://github.com/tmp64/BugfixedHL-Rebased/wiki/Server-API) functions to set player's score correctly.

**Comment by tmp64** [comment]
I added `SetPlayerScore` method to Server API. You can use it from AMXX like this:

```sma
/*
 * Demo plugin for BugfixedAPI SetPlayerScore.
 * Based on CS1.6 Reset Score plugin by Silenttt.
*/

#include <amxmodx>
#include <bugfixedapi>

public plugin_init()
{
	register_plugin("BHL Reset Score", "1.0", "tmp64 + Silenttt")
	register_clcmd("say /rs", "reset_score")
}

public reset_score(id)
{
	// Args: player index, kills, deaths
	bhl_set_player_score(id, 0, 0)
	client_print(id, print_chat, "Score reset.")
}
```

**Comment by Mehmet-I** [comment]
Thx bro.
