### ISSUE TITLE
Add Rainbow HUD

### ISSUE THREAD

**Issue by SmileyAG** [tmp64/BugfixedHL-Rebased#31]
https://github.com/YaLTeR/OpenAG/commit/fe501e725bc7b6deb83ea97a16738b87af5e55f2

**Comment by SmileyAG** [comment]
Can you add client/feature labels please? @tmp64

**Comment by tmp64** [comment]
I can't implement rainbowness in chat and scoreboard since they use VGUI2 panels for text rendering. Its code is in a separate submodule and I don't want to hack it into it.
