### ISSUE TITLE
Client: Not working demo autorecord, not working agrecord

### ISSUE THREAD

**Issue by Berzerk3r** [tmp64/BugfixedHL-Rebased#37]
forgot, is not working with hl (dll in valve_addons folder), in ag works fine (upd, not working)

reinstalled client, not works propertly in ag\valve (dll in *_addon folder)
P.S. maybe slash\backslash trouble? aka lin\win

**Comment by tmp64** [comment]
Seems to work fine when installed in either gamedir and gamedir_addon. Does it show any error?

**Comment by Berzerk3r** [comment]
recording to results\2021-06\crossfire-20210618-100110.dem.
Error: couldn't open demo file results\2021-06\crossfire-20210618-100110.dem, demo files must have .dem extension.

**Comment by tmp64** [comment]
Could you post `version` command output?

**Comment by Berzerk3r** [comment]
] version 
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 19:53:27 Aug  3 2020 (8684)

latest steam

**Comment by tmp64** [comment]
What language do you have set in the game?

**Comment by Berzerk3r** [comment]
> 
> 
> What language do you have set in the game?

Russian. Is this the problem?

**Comment by tmp64** [comment]
Can you check if `Half-Life/valve_russian/results` directory exists?

**Comment by Berzerk3r** [comment]
i have no valve_russian folder. I store russian localisation in gamedir_addon folder.
created valve_russian/results - no effect
exists in "valve" and "ag" directoires
but i'ts empty

**Comment by tmp64** [comment]
I added some debug output to this dll. You should see lines m_szFullGameDirPath and m_fsFullGameDirPath in the console. Please, post them.

[client_gamedirpath_test.zip](https://github.com/tmp64/BugfixedHL-Rebased/files/6675894/client_gamedirpath_test.zip)

**Comment by Berzerk3r** [comment]
> 
> 
> I added some debug output to this dll. You should see lines m_szFullGameDirPath and m_fsFullGameDirPath in the console. Please, post them.
> 
> [client_gamedirpath_test.zip](https://github.com/tmp64/BugfixedHL-Rebased/files/6675894/client_gamedirpath_test.zip)


m_szFullGameDirPath = d:\games\steam\steamapps\common\half-life\ag_addon\
m_fsFullGameDirPath = d:\games\steam\steamapps\common\half-life\ag_addon\

**Comment by tmp64** [comment]
Try removing all `results` directories, maybe that helps

**Comment by Berzerk3r** [comment]
> 
> 
> Try removing all `results` directories, maybe that helps

Did not help. A new results folder is created in gamedir_addon, but only the chat log is written to it 
same error

**Comment by tmp64** [comment]
I fixed slashes in the file path, but I don't think it would fix. I honestly have no idea why it may not work. Is it possible that gamedir is write-protected?

[client_fixed_slashes.zip](https://github.com/tmp64/BugfixedHL-Rebased/files/6676010/client_fixed_slashes.zip)

**Comment by Berzerk3r** [comment]
Did not help. There is no write protection.
Later I'll try a clean install again, adding only dll to the client half-life.

maybe I have an error somewhere (hard modified _addon folder)

**Comment by Berzerk3r** [comment]
Ok. I close this issue. 

Clean installed client + dll in empty _addon folder = all works.
Something went wrong in my mods )

Sorry 4 the false report
![изображение](https://user-images.githubusercontent.com/57665061/122543003-fe1aa280-d033-11eb-95cd-554263c119c9.png)
