### ISSUE TITLE
Command Menu not working on 4554

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#38]
Using +commandmenu seems to open a panel but it's invisible.

> ] version
> Protocol version 48
> Exe version 1.1.2.1 (valve)
> Exe build: 16:05:41 Jun 15 2009 (4554)

> ] about
> BugfixedHL-Rebased
> Bugfixed and improved Half-Life Client
> Version: 1.6.0-beta2+master.f40c7e6
> Engine: 1.1.2.1,48,4554

**Comment by tmp64** [comment]
Command menu uses a different file format (you should have an error in the console). See `commandmenu_default.txt` for an example.

Although, I should probably have used parsing code from VGUI1 command menu. I'll rewrite menu loading to use original syntax.

**Comment by tmp64** [comment]
I should've reused original syntax when I was rewriting command menu. It's so much more readable than Source's KeyValues.
