### ISSUE TITLE
cl_force team and enemy models not working properly

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#41]
It does work but not on all players. Can't provide more info since I haven't tested. But let's say it doesn't affect 25% percent of the players on a server.

> ] about
> BugfixedHL-Rebased
> Bugfixed and improved Half-Life Client
> Version: 1.6.0-beta2+master.f40c7e6
> Engine: 1.1.2.1,48
> 
> ] version
> Protocol version 48
> Exe version 1.1.2.1 (valve)
> Exe build: 16:05:41 Jun 15 2009 (4554)

**Comment by Berzerk3r** [comment]
confirm
doesn't work if enemy has unicode symbols in nickname

**Comment by tmp64** [comment]
I think I've found the issue. I put a call to `g_StudioRenderer.InitOnConnect()` next to `gHUD.VidInit()` in cdll_int.cpp assuming it's `HUD_VidInit()`. But instead I put it into `HUD_Reset()`.

This caused the model selection code to use an incorrect local player index (it remembered the index from first server).

da23f25899bf6afa180fb42629d2c317ac452882 resolves it. Please, test the dev build from Actions,

**Comment by Berzerk3r** [comment]
> 
> 
> I think I've found the issue. I put a call to `g_StudioRenderer.InitOnConnect()` next to `gHUD.VidInit()` in cdll_int.cpp assuming it's `HUD_VidInit()`. But instead I put it into `HUD_Reset()`.
> 
> This caused the model selection code to use an incorrect local player index (it remembered the index from first server).
> 
> [da23f25](https://github.com/tmp64/BugfixedHL-Rebased/commit/da23f25899bf6afa180fb42629d2c317ac452882) resolves it. Please, test the dev build from Actions,

seems to be working fine now

**Comment by tmp64** [comment]
Thanks for testing! If it happens again, please reopen the issue and post `dev_model_debug` command output.
