### ISSUE TITLE
Opening and closing console while MOTD is open makes cursor disappear, moving camera instead

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#42]
Small bug but this shouldn't be the default behaviour, I guess.

> ] version
> Protocol version 48
> Exe version 1.1.2.1 (valve)
> Exe build: 16:05:41 Jun 15 2009 (4554)
> 
> ] about
> BugfixedHL-Rebased
> Bugfixed and improved Half-Life Client
> Version: 1.6.0-beta2+master.f40c7e6
> Engine: 1.1.2.

**Comment by tmp64** [comment]
Fixed. Thanks!
