### ISSUE TITLE
hud_saytext_sound 1 doesn't play any sound

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#43]
Maybe I'm missing a sound file or something like that?

> ] version
> Protocol version 48
> Exe version 1.1.2.1 (valve)
> Exe build: 16:05:41 Jun 15 2009 (4554)
> 
> ] about
> BugfixedHL-Rebased
> Bugfixed and improved Half-Life Client
> Version: 1.6.0-beta2+master.f40c7e6
> Engine: 1.1.2.1,48,4554

**Comment by tmp64** [comment]
You need `sound/misc/talk.wav` which was added in SteamPipe update. I'll think how to add it without overwriting user's file if it was changed.
[talk.zip](https://github.com/tmp64/BugfixedHL-Rebased/files/6462842/talk.zip)

**Comment by gundogfan** [comment]
Thanks!
