### ISSUE TITLE
Suggestion: Console colors CVARs

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#48]
I'd like the ability to change the color of:
-Chat (bringing back con_say_color "R G B")
-Server messages (which seem to be the same as chat messages but maybe I'm wrong).
-Kill messages (when you kill or get killed)

**Comment by tmp64** [comment]
Added chat color property and death notice sprite cvars.

- Chat color can be changed in `ui/resource/ChatScheme.res` (ChatTextColor).
- Server messages use the same color.
- Color codes can be changed in `ui/resource/ClientScheme.res`
- Death notice text color is controlled by `con_color`. Sprite color can be changed with `hud_deathnotice_color` and `hud_deathnotice_color_tk`.
