### ISSUE TITLE
Suggestion: make speedometer read other players' speed while spectating

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#50]
In the following picture you can see two speedometers, [Kreedz gamemode by Yalter's](https://github.com/YaLTeR/hlkreedz/blob/master/scripting/hl_kreedz.sma) (showing the speed of the player I'm spectating) and BugfixedHL's (showing mine as a spectator, which is useless). Is it possible to make the speedometer read other players' speed just like in Kreedz?

![speedometer](https://user-images.githubusercontent.com/70611792/123030207-cbb4d080-d3b8-11eb-9f7a-faf9724f9896.png)

**Comment by tmp64** [comment]
It seems to be not possible since the client doesn't know spectatee's real speed. Instead, it calculates it as a difference between current and previous positions which is imprecise and jumps every frame. This makes it unusable.

**Comment by gundogfan** [comment]
Maybe this could be done server-side the way HL Kreedz does, and when one is spectating someone then server-side speedometer is gonna replace client-side one. Just an idea.
