### ISSUE TITLE
Request: render modes

### ISSUE THREAD

**Issue by Berzerk3r** [tmp64/BugfixedHL-Rebased#51]
Can you add this things from RezWaki's Sharp Client?

> r_noplayerlights	| 1/0	    | Remove playermodels light processing
> r_noitemlights	| 1/0	    | Remove all models light processing
> r_forcerendercolors | R G B	    | Your colors on models with disabled light proc.
> r_extrachrome	| 0/1/2	    | More fancy chrome render modes, 0 disable

he stores it in cdll_int.cpp and StudioModelRenderer.cpp

link to his repository https://github.com/RezWaki/Sharp_Client

**Comment by tmp64** [comment]
Sorry, but I'm not going to modify player model rendering as it may give an unfair advantage (e.g. in a dark room).
