### ISSUE TITLE
Results files are not changed on map change

### ISSUE THREAD

**Issue by thedrakehl** [tmp64/BugfixedHL-Rebased#52]
Good evening. There is a bug with the cl_autorecord 1 that causes the demos not to be recorded or to be recorded badly with the name of the previous map. That is, if I put stalkx, then crossfire and then stalkyard, it will happen that only the stalkx demo would be recorded and with an exorbitant weight. I have only seen this bug in this version 1.6

**Comment by tmp64** [comment]
Please, make separate GitHub issues for different problems.

**Comment by tmp64** [comment]
Fixed, thanks!
