### ISSUE TITLE
Command Menu: Exit submenu with ESC

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#55]
Once you open command menu you can only use it with numbers. Using the mouse will move the camera instead of navigating through the menu. The main issue about this is once you chose a submenu, you can't go back since there isn't a key/number for that. Tested on both 4554 and 8684 (Steam).

**Comment by tmp64** [comment]
You need to hold the button to use the mouse. If you click once, it would only be controlled with numbers. VGUI1 command menu has the same behavior.

As for a button to close a submenu, I'll make ESC do it.

**Comment by gundogfan** [comment]
Oh got it, by bad. Thanks!

**Comment by tmp64** [comment]
I couldn't make it just close on ESC because of GoldSrc spaghetti so it will close whenever the game menu is opened. That means that pressing ESC will close the command menu and open the game menu.
