### ISSUE TITLE
Remove crosshair when using tanks

### ISSUE THREAD

**Issue by Safety1st** [tmp64/BugfixedHL-Rebased#59]
It's default game behaviour. When you use such powerful weapons you loose the ability to aim well :)
![image](https://user-images.githubusercontent.com/1483401/126884150-80ec1cab-9d44-46cc-9881-952ed192d1ec.png)

**Comment by tmp64** [comment]
Being able to see the crosshair is compensated by the fact that it's imprecise \:)

This bug is a consequence of fix for #32. In multiplayer, it is always drawn so it doesn't disappear on demo start.

**Comment by Safety1st** [comment]
But it is easily possible to detect tank using and redraw crosshair after using...

**Comment by tmp64** [comment]
Nothing is easy in GoldSrc. When you enable a tank, the server just hides weapon HUD, just like when starting a demo on a buggy server.
