### ISSUE TITLE
Bug: binds get triggered while using vgui2 chat

### ISSUE THREAD

**Issue by Zly-u** [tmp64/BugfixedHL-Rebased#64]

**Comment by gundogfan** [comment]
Tested on 4554 and latest Steam build and it doesn't happen to me

**Comment by Zly-u** [comment]
> 
> 
> Tested on 4554 and latest Steam build and it doesn't happen to me

I use the latest version of the game on steam and this addon as well.

**Comment by tmp64** [comment]
1. Which binds are triggered?
2. Are WASD keys also triggered?
3. Bind `"clear; vgui_dumptree"` to a key, press it when chat is open and post the full console output here.

**Comment by Zly-u** [comment]
Only my custom binds gets triggered, and those are on `B`, `N` and `M` buttons, they just change models for enemies and for myself.
But for some reason i could not replicate it this time, will try a bit later again.
