### ISSUE TITLE
Dead boxes

### ISSUE THREAD

**Issue by Mehmet-I** [tmp64/BugfixedHL-Rebased#7]
![20201225221814_1](https://user-images.githubusercontent.com/63732211/103141003-36819980-46ff-11eb-826c-d57a773afda3.jpg)
Can a cvar be added to reduce the duration of the dead boxes or remove them? (in server)

**Comment by tmp64** [comment]
Added cvars
- `mp_weaponbox_time 120` - Dead player's weapons will stay for this many seconds, 0 disables them, -1 forever.
- `mp_weapondrop_time 0` - Manually dropped weapons will stay for this many seconds, 0 forever.
