### ISSUE TITLE
Suggestion: changing "cl_righthand" to "cl_lefthand"

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#77]
Being "1" enabled, sounds weird if "cl_righthand 1" enables left-handed mode. It should be named "cl_lefthand".

Tested both on 4554 and latest Steam build.

**Comment by SmileyAG** [comment]
> 
> 
> Being "1" enabled, sounds weird if "cl_righthand 1" enables left-handed mode. It should be named "cl_lefthand".
> 
> Tested both on 4554 and latest Steam build.

It cannot be done, because engine search for `cl_righthand` pointer, so close issue.

**Comment by tmp64** [comment]
Yeah, it's not possible because of the engine
