### ISSUE TITLE
Suggestion: adding more options for "cl_viewmodel_hltv"

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#81]
So far: 
-`cl_viewmodel_hltv 1` disables idle animation
-`cl_viewmodel_hltv 2` disables equip animation
-`cl_viewmodel_hltv 3` disables both idle and equip animation

My idea is having 2 more options:
-`cl_viewmodel_hltv 4` disabling idle, equip and **shoot** animation (including gauss's fidget/spin/spinup, only other weapons' reload animation would remain enabled)
-`cl_viewmodel_hltv 5` disabling **every single** animation 

Most players I know use the so called "_FULL_ HLTV" models which disable all animations or all animations except for reload one.

Also, I have no idea if it's possible disabling "shell" models, until now I've been using invisible shell models which is somehow helpful in order to focus more on your enemy rather than so many visual things going on on the screen. But a CVAR for this one would be great.

**Comment by tmp64** [comment]
I changed the cvar so it acts like a bitfield.
```cpp
ConVar cl_viewmodel_hltv("cl_viewmodel_hltv", "0", FCVAR_BHL_ARCHIVE,
    "Disables animations of the viewmodel\n"
    "   0 - nothing is disabled\n"
    "  +1 - disables idle animations\n"
    "  +2 - disables equip animations\n"
    "  +4 - disables shooting animations\n"
    "  +8 - disables reload animations\n"
    "   7 - disables all above but reloading\n"
    "  15 - disables all listed above");
```

**Comment by tmp64** [comment]
77932a4e155b41b1a94c8eaf7279290b5285ccd1 add `r_noshells`

**Comment by gundogfan** [comment]
Awesome feature! Thanks!
