### ISSUE TITLE
"hud_deathnotice_vgui 1" requires restarting the game to work

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#83]
Changing from 0 to 1 makes death notice completely disappear until you restart the game.

The only time this doesn't happen is when you change from 0 to 1 when you just open the game (without having joined any server yet).

Tested both on 4554 and latest Steam build.

**Comment by tmp64** [comment]
Can you provide the exact steps to reproduce the problem?

**Comment by gundogfan** [comment]
1. Open the game having already `hud_deathnotice_vgui 0` (if you set it to 1 then set it to 0 and restart the game).
2. Join a server and change it to `hud_deathnotice_vgui 1`.
3. Kill or get killed, you'll see no death notice at all.

The only two ways this doesn't happen is either:

1. You opened the game and you already had `hud_deathnotice_vgui 1` by the time you opened it.
2. You opened the game and changed from `hud_deathnotice_vgui 0` to `hud_deathnotice_vgui 1` without having joined any server yet.

**Comment by tmp64** [comment]
I can't repro it. Did you test on the latest dev version? If it still happens, post the output of `about` and `vgui_dumptree`

**Comment by gundogfan** [comment]
Yes, it's the latest dev version, this is Steam version's `vgui_dumptree`:

> ] version
> Protocol version 48
> Exe version 1.1.2.2/Stdio (valve)
> Exe build: 19:53:27 Aug  3 2020 (8684)

> ] about
> BugfixedHL-Rebased
> Bugfixed and improved Half-Life Client
> Version: 1.6.1-dev+master.8806780
> Engine: 1.1.2.2/Stdio,48,8684

> ] vgui_dumptree 
> Usage:
>     vgui_dumptree - show list of visible panels
>     vgui_dumptree all - show list of all panels
> Color coding:
>     Green - visible
>     Red - hidden
> 
> StaticPanel [Panel 1600 x 900] @ (0; 0) [KM] [Vis]
>     tooltip [TextEntry 64 x 24] @ (0; 0) [KMP]
>     BaseClientPanel [EditablePanel 1600 x 900] @ (0; 0) [K]
>     BaseGameUIPanel [EditablePanel 1600 x 900] @ (0; 0) [KM] [Vis]
>         BasePanel [Panel 1600 x 900] @ (0; 0) [KM] [Vis]
>             TaskBar [CTaskbar 1600 x 64] @ (0; 836) [KM] [Vis]
>                 GameMenuButton [Button 240 x 36] @ (32; 16) [KM] [Vis]
>                 PlatformMenuButton [Button 240 x 36] @ (1328; 6) [KM] [Vis]
>                     PlatformMenu [Menu 72 x 28] @ (1496; 808) [KMP] [Vis]
>                         MenuScrollBar [ScrollBar 64 x 24] @ (0; 0) [KM]
>                         #App_Servers [MenuItem 72 x 28] @ (0; 0) [KM] [Vis]
>                 CServerBrowserDialog [CServerBrowserDialog 800 x 495] @ (224; 182) [KMP] [Vis]
>                     < no name > [Panel 790 x 23] @ (0; 0) [KM] [Vis]
>                     < no name > [Button 18 x 18] @ (775; 8) [KM] [Vis]
>                     GameTabs [PropertySheet 784 x 417] @ (8; 44) [KM] [Vis]
>                         tab [Button 72 x 25] @ (73; 4) [KM] [Vis]
>                         FavoriteGames [CFavoriteGames 624 x 278] @ (0; 0) [KM]
>                         tab [Button 72 x 25] @ (146; 4) [KM] [Vis]
>                         HistoryGames [CHistoryGames 624 x 278] @ (0; 0) [KM]
>                         tab [Button 72 x 25] @ (219; 4) [KM] [Vis]
>                         SpectateGames [CInternetGames 624 x 278] @ (0; 0) [KM]
>                         tab [Button 72 x 25] @ (292; 4) [KM] [Vis]
>                         LanGames [CLanGames 624 x 278] @ (0; 0) [KM]
>                         tab [Button 72 x 25] @ (365; 4) [KM] [Vis]
>                         FriendsGames [CFriendsGames 624 x 278] @ (0; 0) [KM]
>                         tab [Button 72 x 27] @ (0; 2) [KM] [Vis]
>                         InternetGames [CInternetGames 784 x 389] @ (0; 28) [KM] [Vis]
>                             RefreshButton [Button 95 x 24] @ (605; 355) [KM] [Vis]
>                             RefreshQuickButton [Button 105 x 24] @ (494; 355) [KM] [Vis]
>                             AddServerButton [Button 98 x 24] @ (504; 355) [KM]
>                             AddCurrentServerButton [Button 142 x 24] @ (356; 355) [KM]
>                             AddToFavoritesButton [Button 64 x 24] @ (0; 0) [KM]
>                             Filter [ToggleButton 108 x 24] @ (8; 355) [KM] [Vis]
>                             FilterString [Label 238 x 24] @ (119; 355) [KM] [Vis]
>                             GameFilter [ComboBox 164 x 24] @ (60; 261) [KM]
>                             MapFilter [TextEntry 164 x 24] @ (60; 291) [KM]
>                             PingFilter [ComboBox 112 x 24] @ (311; 261) [KM]
>                             SecureFilter [ComboBox 112 x 24] @ (311; 321) [KM]
>                             ServerEmptyFilterCheck [CheckButton 184 x 24] @ (436; 285) [KM]
>                             ServerFullFilterCheck [CheckButton 184 x 24] @ (436; 261) [KM]
>                             NoPasswordFilterCheck [CheckButton 250 x 24] @ (436; 309) [KM]
>                             ValidSteamAccountFilterCheck [CheckButton 285 x 24] @ (436; 333) [KM]
>                             LocationFilter [ComboBox 112 x 24] @ (311; 291) [KM]
>                             ConnectButton [Button 75 x 24] @ (705; 355) [KM] [Vis]
>                             gamelist [CGameListPanel 784 x 337] @ (0; 8) [KM] [Vis]
>                                 HorizScrollBar [ScrollBar 64 x 24] @ (0; 0) [KM]
>                                 < no name > [Label 16 x 14] @ (2; 336) [KM]
>                                 Password [Button 16 x 18] @ (-1; 0) [KM] [Vis]
>                                 Bots [Button 20 x 18] @ (15; 0) [KM] [Vis]
>                                 Secure [Button 16 x 18] @ (35; 0) [KM] [Vis]
>                                 Players [Button 55 x 18] @ (51; 0) [KM] [Vis]
>                                 Name [Button 400 x 18] @ (106; 0) [KM] [Vis]
>                                 GameDesc [Button 112 x 18] @ (506; 0) [KM] [Vis]
>                                 Map [Button 90 x 18] @ (618; 0) [KM] [Vis]
>                                 Ping [Button 56 x 18] @ (708; 0) [KM] [Vis]
>                                 IPAddr [Button 64 x 24] @ (0; 0) [KM]
>                                 < no name > [Panel 64 x 24] @ (0; 0) [KM]
>                                 VertScrollBar [ScrollBar 18 x 335] @ (764; 0) [KM] [Vis]
>                                     < no name > [ScrollBarSlider 18 x 300] @ (0; 18) [KM] [Vis]
>                                     < no name > [Button 17 x 18] @ (0; 0) [KM] [Vis]
>                                     < no name > [Button 17 x 18] @ (0; 317) [KM] [Vis]
>                                 < no name > [Panel 8 x 18] @ (11; 0) [KM] [Vis]
>                                 < no name > [Panel 8 x 18] @ (31; 0) [KM] [Vis]
>                                 < no name > [Panel 8 x 18] @ (47; 0) [KM] [Vis]
>                                 < no name > [Panel 8 x 18] @ (102; 0) [KM] [Vis]
>                                 < no name > [Panel 8 x 18] @ (502; 0) [KM] [Vis]
>                                 < no name > [Panel 8 x 18] @ (614; 0) [KM] [Vis]
>                                 < no name > [Panel 8 x 18] @ (704; 0) [KM] [Vis]
>                                 < no name > [Panel 8 x 18] @ (760; 0) [KM]
>                     < no name > [Panel 784 x 5] @ (8; 0) [KM] [Vis]
>                     < no name > [Panel 774 x 5] @ (8; 490) [KM] [Vis]
>                     < no name > [Panel 5 x 479] @ (0; 8) [KM] [Vis]
>                     < no name > [Panel 5 x 469] @ (795; 8) [KM] [Vis]
>                     < no name > [Panel 8 x 8] @ (0; 0) [KM] [Vis]
>                     < no name > [Panel 8 x 8] @ (792; 0) [KM] [Vis]
>                     < no name > [Panel 8 x 8] @ (0; 487) [KM] [Vis]
>                     < no name > [Panel 18 x 18] @ (782; 477) [KM] [Vis]
>                     < no name > [Button 18 x 18] @ (0; 0) [KM]
>                     < no name > [FrameSystemButton 18 x 18] @ (7; 8) [KM] [Vis]
>                         < no name > [Menu 64 x 24] @ (0; 0) [KMP]
>                     < no name > [Button 18 x 18] @ (0; 0) [KM]
>                     < no name > [Button 18 x 18] @ (0; 0) [KM]
>                     StatusLabel [Label 704 x 24] @ (11; 467) [KM] [Vis]
>                     ServerContextMenu [Menu 64 x 24] @ (0; 0) [KMP]
>                 GameMenu [Menu 153 x 252] @ (32; 584) [KMP] [Vis]
>                     MenuScrollBar [ScrollBar 64 x 24] @ (0; 0) [KM]
>                     #GameUI_GameMenu_ResumeGame [MenuItem 153 x 28] @ (0; 0) [KM]
>                     #GameUI_GameMenu_Disconnect [MenuItem 153 x 28] @ (0; 28) [KM]
>                     #GameUI_GameMenu_LeaveGame [MenuItem 153 x 28] @ (0; 0) [KM]
>                     #GameUI_GameMenu_PlayerList [MenuItem 153 x 28] @ (0; 56) [KM]
>                     < no name > [MenuItem 153 x 28] @ (0; 84) [KM]
>                     #GameUI_GameMenu_NewGame [MenuItem 153 x 28] @ (0; 0) [KM] [Vis]
>                     #GameUI_GameMenu_LoadGame [MenuItem 153 x 28] @ (0; 28) [KM] [Vis]
>                     #GameUI_GameMenu_SaveGame [MenuItem 153 x 28] @ (0; 0) [KM]
>                     < no name > [MenuItem 153 x 28] @ (0; 56) [KM] [Vis]
>                     #GameUI_GameMenu_FindServers [MenuItem 153 x 28] @ (0; 84) [KM] [Vis]
>                     #GameUI_GameMenu_CreateServer [MenuItem 153 x 28] @ (0; 112) [KM] [Vis]
>                     < no name > [MenuItem 153 x 28] @ (0; 140) [KM] [Vis]
>                     #GameUI_GameMenu_ChangeGame [MenuItem 153 x 28] @ (0; 0) [KM]
>                     #GameUI_GameMenu_Options [MenuItem 153 x 28] @ (0; 168) [KM] [Vis]
>                     #BHL_GameMenu_AdvOptions [MenuItem 153 x 28] @ (0; 196) [KM] [Vis]
>                     #GameUI_GameMenu_Quit [MenuItem 153 x 28] @ (0; 224) [KM] [Vis]
>         ClientGameUIViewport [CGameUIViewport 0 x 0] @ (0; 0) [KM] [Vis]
>         GameConsole [CGameConsoleDialog 560 x 400] @ (40; 40) [KMP] [Vis]
>             < no name > [Panel 550 x 23] @ (0; 0) [KM] [Vis]
>             < no name > [Button 18 x 18] @ (535; 8) [KM] [Vis]
>             ConsoleSubmit [Button 64 x 24] @ (488; 368) [KM] [Vis]
>             ConsoleHistory [RichText 544 x 324] @ (8; 36) [KM] [Vis]
>                 ScrollBar [ScrollBar 18 x 322] @ (524; 0) [KM] [Vis]
>                     < no name > [ScrollBarSlider 18 x 287] @ (0; 18) [KM] [Vis]
>                     < no name > [Button 17 x 18] @ (0; 0) [KM] [Vis]
>                     < no name > [Button 17 x 18] @ (0; 304) [KM] [Vis]
>                 EditMenu [Menu 42 x 24] @ (103; 105) [KMP]
>             < no name > [Panel 544 x 5] @ (8; 0) [KM] [Vis]
>             < no name > [Panel 534 x 5] @ (8; 395) [KM] [Vis]
>             < no name > [Panel 5 x 384] @ (0; 8) [KM] [Vis]
>             < no name > [Panel 5 x 374] @ (555; 8) [KM] [Vis]
>             < no name > [Panel 8 x 8] @ (0; 0) [KM] [Vis]
>             < no name > [Panel 8 x 8] @ (552; 0) [KM] [Vis]
>             < no name > [Panel 8 x 8] @ (0; 392) [KM] [Vis]
>             < no name > [Panel 18 x 18] @ (542; 382) [KM] [Vis]
>             < no name > [Button 18 x 18] @ (0; 0) [KM]
>             < no name > [FrameSystemButton 18 x 18] @ (7; 8) [KM] [Vis]
>                 < no name > [Menu 75 x 68] @ (0; 0) [KMP]
>             < no name > [Button 18 x 18] @ (0; 0) [KM]
>             < no name > [Button 18 x 18] @ (0; 0) [KM]
>             ConsoleEntry [TextEntry 472 x 24] @ (8; 368) [KM] [Vis]
>             CompletionList [Menu 99 x 24] @ (48; 440) [KMP]

**Comment by gundogfan** [comment]
And 4554's:

> ] version
> Protocol version 48
> Exe version 1.1.2.1 (valve)
> Exe build: 16:05:41 Jun 15 2009 (4554)

> ] about
> BugfixedHL-Rebased
> Bugfixed and improved Half-Life Client
> Version: 1.6.1-dev+master.8806780
> Engine: 1.1.2.1,48,4554

> ] vgui_dumptree 
> Usage:
>     vgui_dumptree - show list of visible panels
>     vgui_dumptree all - show list of all panels
> Color coding:
>     Green - visible
>     Red - hidden
> 
> StaticPanel [Panel 1600 x 900] @ (0; 0) [KM] [Vis]
>     BaseClientPanel [EditablePanel 1600 x 900] @ (0; 0) [K]
>     BaseGameUIPanel [EditablePanel 1600 x 900] @ (0; 0) [KM] [Vis]
>         BasePanel [Panel 1600 x 900] @ (0; 0) [KM] [Vis]
>             TaskBar [CTaskbar 1600 x 64] @ (0; 836) [KM] [Vis]
>                 GameMenuButton [Button 240 x 36] @ (32; 16) [KM] [Vis]
>                 PlatformMenuButton [Button 240 x 36] @ (1328; 6) [KM]
>                 PlayerListDialog [CPlayerListDialog 467 x 388] @ (566; 256) [KMP]
>                 CServerBrowserDialog [CServerBrowserDialog 640 x 422] @ (462; 249) [KMP]
>                 GameMenu [Menu 212 x 280] @ (32; 556) [KMP] [Vis]
>                     MenuScrollBar [ScrollBar 64 x 24] @ (0; 0) [KM]
>                     #GameUI_GameMenu_ResumeGame [MenuItem 212 x 28] @ (0; 0) [KM] [Vis]
>                     #GameUI_GameMenu_Disconnect [MenuItem 212 x 28] @ (0; 28) [KM] [Vis]
>                     #GameUI_GameMenu_LeaveGame [MenuItem 212 x 28] @ (0; 0) [KM]
>                     #GameUI_GameMenu_PlayerList [MenuItem 212 x 28] @ (0; 56) [KM] [Vis]
>                     < no name > [MenuItem 212 x 28] @ (0; 84) [KM] [Vis]
>                     #GameUI_GameMenu_NewGame [MenuItem 212 x 28] @ (0; 0) [KM]
>                     #GameUI_GameMenu_LoadGame [MenuItem 212 x 28] @ (0; 28) [KM]
>                     #GameUI_GameMenu_SaveGame [MenuItem 212 x 28] @ (0; 0) [KM]
>                     < no name > [MenuItem 212 x 28] @ (0; 56) [KM]
>                     #GameUI_GameMenu_FindServers [MenuItem 212 x 28] @ (0; 112) [KM] [Vis]
>                     #GameUI_GameMenu_CreateServer [MenuItem 212 x 28] @ (0; 140) [KM] [Vis]
>                     < no name > [MenuItem 212 x 28] @ (0; 168) [KM] [Vis]
>                     #GameUI_GameMenu_ChangeGame [MenuItem 212 x 28] @ (0; 168) [KM]
>                     #GameUI_GameMenu_Options [MenuItem 212 x 28] @ (0; 196) [KM] [Vis]
>                     #BHL_GameMenu_AdvOptions [MenuItem 212 x 28] @ (0; 224) [KM] [Vis]
>                     #GameUI_GameMenu_Quit [MenuItem 212 x 28] @ (0; 252) [KM] [Vis]
>         ClientGameUIViewport [CGameUIViewport 0 x 0] @ (0; 0) [KM] [Vis]
>         GameConsole [CGameConsoleDialog 560 x 400] @ (40; 40) [KMP] [Vis]
>             < no name > [Panel 550 x 23] @ (0; 0) [KM] [Vis]
>             < no name > [Button 18 x 18] @ (535; 8) [KM] [Vis]
>             ConsoleSubmit [Button 64 x 24] @ (488; 368) [KM] [Vis]
>             ConsoleHistory [RichText 544 x 324] @ (8; 36) [KM] [Vis]
>                 ScrollBar [ScrollBar 18 x 322] @ (525; 0) [KM] [Vis]
>                     < no name > [ScrollBarSlider 18 x 287] @ (0; 18) [KM] [Vis]
>                     < no name > [Button 17 x 18] @ (0; 0) [KM] [Vis]
>                     < no name > [Button 17 x 18] @ (0; 304) [KM] [Vis]
>                 EditMenu [Menu 42 x 24] @ (106; 221) [KMP]
>             < no name > [Panel 544 x 5] @ (8; 0) [KM] [Vis]
>             < no name > [Panel 534 x 5] @ (8; 395) [KM] [Vis]
>             < no name > [Panel 5 x 384] @ (0; 8) [KM] [Vis]
>             < no name > [Panel 5 x 374] @ (555; 8) [KM] [Vis]
>             < no name > [Panel 8 x 8] @ (0; 0) [KM] [Vis]
>             < no name > [Panel 8 x 8] @ (552; 0) [KM] [Vis]
>             < no name > [Panel 8 x 8] @ (0; 392) [KM] [Vis]
>             < no name > [Panel 18 x 18] @ (542; 382) [KM] [Vis]
>             < no name > [Button 18 x 18] @ (0; 0) [KM]
>             < no name > [FrameSystemButton 18 x 18] @ (7; 8) [KM] [Vis]
>                 < no name > [Menu 75 x 68] @ (0; 0) [KMP]
>             < no name > [Button 18 x 18] @ (0; 0) [KM]
>             < no name > [Button 18 x 18] @ (0; 0) [KM]
>             ConsoleEntry [TextEntry 472 x 24] @ (8; 368) [KM] [Vis]
>             CompletionList [Menu 139 x 68] @ (48; 440) [KMP]

**Comment by gundogfan** [comment]
Here's a video where I show case 1 (open the game, join sv, change 0 to 1, kill) and 2 (open game, join sv, disconnect, change 0 to 1, kill):

https://user-images.githubusercontent.com/70611792/131263800-06b79fee-ed27-4563-b6ac-b363ad2d6e53.mp4

Sorry for the quality, videos on GitHub can be up to 10mb only.

**Comment by gundogfan** [comment]
I recorded a video showing case 1 (open hl, join a sv, change 0 to 1, kill) and case 2 (open hl, join a sv, disconnect, change 0 to 1, join a sv again, kill)

https://mega.nz/file/qpERyawK#iZYMjd0wrOZuXZEWAIf4D3FDI6R8pgl46DtNEXiHr_M

Sorry bout the quality, it was supossed to be uploaded to GitHub which allows videos up to 10mb but for some reason the video can't be seen here at all, so I uploaded it to Mega.

**Comment by tmp64** [comment]
Fixed in 9e9860f02308aba9c5579ef61fe742511a9d047c and 34f7e8c4260602b59236dcc6e403db2ced02f168.
`m_iFlags` was uninitialized (contained garbage) and in debug build a specific bit `HUD_ACTIVE` was set and so I didn't have the issue
