### ISSUE TITLE
Crash when testing microphone

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#89]
The game crashes when I click on "Test Microphone" in Options/Voice both on 4554 and 8684.

[Test Microphone crash 8684.zip](https://github.com/tmp64/BugfixedHL-Rebased/files/7102091/Test.Microphone.crash.8684.zip)
[Test Microphone crash 4554.zip](https://github.com/tmp64/BugfixedHL-Rebased/files/7102092/Test.Microphone.crash.4554.zip)

**Comment by tmp64** [comment]
Fixed, thanks!
