### ISSUE TITLE
BHL Server not working

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#91]
I installed BHL on my server (Linux) but it doesn't load, it crashes instead, showing this message on console:

> Game DLL version mismatch
> DLL version is 140, engine version is 140
> The game DLL for valve appears to be outdated, check for updates

This is my server's info:

> Protocol version 48
> Exe version 1.1.2.2/Stdio (valve)
> ReHLDS version: 3.8.0.702-dev
> Build date: 18:22:55 Nov  8 2020 (2402)
> Build from: https://github.com/dreamstalker/rehlds/commit/543728d

> AMX Mod X 1.9.0.5271 (http://www.amxmodx.org)
> Compiled: Jun 24 2020 13:53:30
> Built from: https://github.com/alliedmodders/amxmodx/commit/5eea3e5
> Build ID: 5271:5eea3e5
> Core mode: JIT+ASM32

EDIT: I think this is due to ReHLDS which is based on builds 6152/6153. In this case, is it possible to add support?

**Comment by gundogfan** [comment]
Seems to be a problem with that version of ReHLDS, didn't happen with 3.10+. Closed.

**Comment by tmp64** [comment]
What's your Linux distribution? Could be a problem with libstdc++

**Comment by gundogfan** [comment]
Problem solved. I told my hosting provider to delete libstdc++ from root (gamedir) which I didn't have access too, and I guess that fixed it.
